= Overview =

The ACME responder is a PKI subsystem that implements an ACME v2 protocol as defined in link:https://tools.ietf.org/html/rfc8555[RFC 8555].

= Supported Deployments =

The ACME responder can be deployed in the following methods:

* as a web application running in Tomcat
* as a container running in Podman, Docker, or OpenShift

See also link:ACME-Installation-Guide[ACME Installation Guide].

= Supported Databases =

The ACME responder uses a database to store the account records, order records, authorization records, and certificate records. The responder can be configured with the following databases:

* 389 DS / Red Hat Directory Server database
* in-memory database (experimental)
* PostgreSQL database (experimental)
* OpenLDAP database (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Database.md[Configuring ACME Database].

= Supported Certificate Issuers =

The ACME responder uses a certificate issuer to issue the actual certificates. The responder can be configured with the following certificate issuers:

* Dogtag PKI CA / Red Hat Certificate System CA
* local NSS database (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Issuer.md[Configuring ACME Issuer].

= Supported Realms =

The ACME responder uses a realm to authenticate and authorize users that manage the ACME responder itself. The responder can be configured with the following realms:

* 389 DS / Red Hat Directory Server realm
* in-memory realm (experimental)
* PostgreSQL realm (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Realm.md[Configuring ACME Realm].

= Supported Clients =

The ACME responder has officially been tested against:

* link:https://certbot.eff.org[certbot]
* link:https://httpd.apache.org/docs/trunk/mod/mod_md.html[mod_md]

However, in general it should be compatible with any link:https://tools.ietf.org/html/rfc8555[RFC 8555]-compliant clients.
See also link:https://github.com/dogtagpki/pki/blob/master/docs/user/acme/Using_PKI_ACME_Responder.md[Using PKI ACME Responder].

