= Overview =

The ACME responder is a web service that provides automatic certificate enrollment, renewal, and revocation via ACME v2 protocol as defined in link:https://tools.ietf.org/html/rfc8555[RFC 8555].

Availability:

* PKI 10.9 (tech preview)
* PKI 10.10 or later (fully supported)

See also link:ACME-Responder-Demo[ACME Responder Demo].

= Supported Domain Validations =

The ACME responder supports the following domain validation methods:

* HTTP-01
* DNS-01

= Supported Deployments =

The ACME responder can be deployed in the following methods:

* As a web application running in Tomcat
* As a container running in Podman, Docker, or OpenShift

See also link:ACME-Installation-Guide[ACME Installation Guide].

= Supported Databases =

The ACME responder uses a database to store the account records, order records, authorization records, and certificate records. The responder can be configured with the following databases:

* link:https://directory.fedoraproject.org[389 Directory Server] database
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server[Red Hat Directory Server] database
* In-memory database (experimental)
* link:https://www.postgresql.org[PostgreSQL] database (experimental)
* link:https://www.openldap.org[OpenLDAP] database (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Database.md[Configuring ACME Database].

= Supported Certificate Issuers =

The ACME responder uses a certificate issuer to issue the actual certificates. The responder can be configured with the following certificate issuers:

* link:Certificate-Authority[Dogtag PKI CA]
* link:https://access.redhat.com/documentation/en-us/red_hat_certificate_system[Red Hat Certificate System CA]
* Local NSS database (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Issuer.md[Configuring ACME Issuer].

= Supported Authentication/Authorization Realms =

The ACME responder uses a realm to authenticate and authorize users that manage the ACME responder itself. The responder can be configured with the following realms:

* link:https://directory.fedoraproject.org[389 Directory Server] realm
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server[Red Hat Directory Server] realm
* In-memory realm (experimental)
* link:https://www.postgresql.org[PostgreSQL] realm (experimental)

See also link:https://github.com/dogtagpki/pki/blob/master/docs/installation/acme/Configuring_ACME_Realm.md[Configuring ACME Realm].

= Supported Clients =

The ACME responder has officially been tested against:

* link:https://github.com/dogtagpki/pki/blob/master/docs/user/acme/Using_PKI_ACME_Responder_with_Certbot.md[certbot]
* link:https://httpd.apache.org/docs/trunk/mod/mod_md.html[mod_md]

However, in general it should be compatible with any link:https://tools.ietf.org/html/rfc8555[RFC 8555]-compliant clients.
See also link:https://github.com/dogtagpki/pki/blob/master/docs/user/acme/Using_PKI_ACME_Responder.md[Using PKI ACME Responder].

