= AgentCertAuthentication =

= CertUserDBAuthentication =

See also link:https://github.com/dogtagpki/pki/blob/master/base/server/cmscore/src/com/netscape/cmscore/authentication/CertUserDBAuthentication.java[CertUserDBAuthentication.java].

= ChallengePhraseAuthentication =

= CMCAuth =

= CMCUserSignedAuth =

= CMC Shared Token Authentication =

See link:Configuring-CMC-Shared-Token-Authentication[Configuring CMC Shared Token Authentication].

= DirBasedAuthentication =

See link:Configuring-Directory-Authenticated-Certificate-Profiles[Configuring Directory-Authenticated Certificate Profiles].

= HashAuthentication =

= NullAuthentication =

= PasswdUserDBAuthentication =

= SSLclientCertAuthentication =

= SSLClientCertAuthentication =

= TokenAuthentication =

= ProfileAuthenticator =

== FlatFileAuth ==

----
auths.instance.flatFileAuth.pluginName=FlatFileAuth
auths.instance.flatFileAuth.authAttributes=PWD
auths.instance.flatFileAuth.deferOnFailure=true
auths.instance.flatFileAuth.fileName=/var/lib/pki/pki-tomcat/conf/ca/flatfile.txt
auths.instance.flatFileAuth.keyAttributes=UID
----

= See Also =

* link:Authentication-Plugins[Authentication Plugins]
* link:Configuring-Authentication-Plugins[Configuring Authentication Plugins]
