= Overview =

CA audit events can be configured in log.instance.SignedAudit.events property.

= Default Events =

* link:https://github.com/dogtagpki/pki/blob/master/docs/admin/Default_CA_Audit_Events.md[Default CA Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_6_BRANCH/docs/admin/Default_CA_Audit_Events.md[PKI 10.6 Default CA Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_5_BRANCH/docs/admin/Default_CA_Audit_Events.md[PKI 10.5 Default CA Audit Events]

= Signing Info Events =

There are two types of CAs:

* the host CA is the primary CA that runs in the CA subsystem
* link:Lightweight-CA[Lightweight CA] are subordinate CAs under the host CA that are also running in the same CA subsystem

Each of the above CA's has a unique ID called '''authority ID'''. For host CA, the authority ID can be omitted.

When the PKI server is started, the server will generate signing info logs for each CA to indicate which keys are used for certificate signing, OCSP signing, and CRL signing. When a new lightweight sub-CA is added, the server will also generate the signing info logs for the new sub-CA.

== CERT_SIGNING_INFO ==

The `CERT_SIGNING_INFO` indicates which key is used to sign certificates.

For the host CA, the log will not include an authority ID:

----
[AuditEvent=CERT_SIGNING_INFO][SubjectID=$System$][Outcome=Success][SKI=5C:A8:93
:F7:73:08:0D:41:A6:99:89:34:F9:BE:F1:6E:0D:7C:D4:21] certificate signing info
----

For lightweight sub-CA, the log will include the authority ID:

----
[AuditEvent=CERT_SIGNING_INFO][SubjectID=$System$][Outcome=Success][SKI=5C:A8:93
:F7:73:08:0D:41:A6:99:89:34:F9:BE:F1:6E:0D:7C:D4:21][AuthorityID=f6276562-a11c-4
a68-b752-2679b2a40962] certificate signing info
----

== OCSP_SIGNING_INFO ==

The `OCSP_SIGNING_INFO` indicates which key is used to sign OCSP responses.

For the host CA, the log will not include an authority ID:

----
[AuditEvent=OCSP_SIGNING_INFO][SubjectID=$System$][Outcome=Success][SKI=B4:D3:3D
:4A:94:D7:A8:AD:65:E2:2B:F1:C5:49:EF:7B:2B:D5:62:93] OCSP signing info
----

For lightweight sub-CA, the log will include the authority ID:

----
[AuditEvent=OCSP_SIGNING_INFO][SubjectID=$System$][Outcome=Success][SKI=5C:A8:93
:F7:73:08:0D:41:A6:99:89:34:F9:BE:F1:6E:0D:7C:D4:21][AuthorityID=f6276562-a11c-4
a68-b752-2679b2a40962] OCSP signing info
----

== CRL_SIGNING_INFO ==

The `CRL_SIGNING_INFO` indicates which key is used to sign CRLs.

For the host CA, the log will not include an authority ID:

----
[AuditEvent=CRL_SIGNING_INFO][SubjectID=$System$][Outcome=Success][SKI=5C:A8:93:
F7:73:08:0D:41:A6:99:89:34:F9:BE:F1:6E:0D:7C:D4:21] CRL signing info
----

Lightweight sub-CA does not support CRL, so no `CRL_SIGNING_INFO` log will be generated for the CA.

= Certificate Events =

== PROFILE_CERT_REQUEST ==

This event is triggered when a profile certificate request is made (before approval process).

Properties:

* SubjectID must be the UID of user that triggered this event (if CMC enrollment requests signed by an agent, SubjectID should be that of the agent)
* CertSubject must be the certificate subject name of the certificate request
* ReqID must be the certificate request ID
* ProfileID must be one of the certificate profiles defined by the administrator

For example, use PKI CLI to submit certificate request:

----
$ pki -c Secret.123 client-cert-request UID=testuser
----

The server will generate the following audit logs:

----
[AuditEvent=PROFILE_CERT_REQUEST][SubjectID=$NonRoleUser$][Outcome=Success][ReqI
D=7][ProfileID=caUserCert][CertSubject=UID=testuser] certificate request made wi
th certificate profiles
----

== CERT_REQUEST_PROCESSED ==

This event is triggered when certificate request has just been through the approval process.

Properties:

* SubjectID must be the UID of the agent who approves, rejects, or cancels the certificate request
* ReqID must be the request ID
* InfoName must be value "certificate" (in case of approval), "rejectReason" (in case of reject), or "cancelReason" (in case of cancel)
* InfoValue must contain the certificate (in case of success), a reject reason in text, or a cancel reason in text

=== Case 1: Approved request ===

Use PKI CLI to approve a certificate request:

----
$ pki -d ~/.dogtag/pki-tomcat/ca/alias -c Secret.123 -n caadmin ca-cert-request-review 7 --action approve
----

In PKI 10.4.5 or later the server will generate a log with the certificate serial number:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Success][ReqID=7]
[CertSerialNum=7] certificate request succeeded
----

Prior to 10.4.5 the server will generate a log with the base64-encoded certificate data:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Success][ReqID=7]
[InfoName=certificate][InfoValue=MIIDBD...] certificate request processed
----

See also:

* link:https://github.com/dogtagpki/pki/issues/2959[Ticket #2959: Missing authority ID in LWCA signing audit events.]

=== Case 2: Rejected request ===

Use PKI CLI to reject a certificate request:

----
$ pki -d ~/.dogtag/pki-tomcat/ca/alias -c Secret.123 -n caadmin ca-cert-request-review 7 --action reject
----

In PKI 10.4.5 or later the server will generate a log with [Outcome=Failure]:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Failure][ReqID=7]
[InfoName=rejectReason][InfoValue=<null>] certificate request processed
----

Prior to PKI 10.4.5 the server will generate a log with [Outcome=Success]:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Success][ReqID=7]
[InfoName=rejectReason][InfoValue=<null>] certificate request processed
----

=== Case 3: Canceled request ===

Use PKI CLI to cancel a certificate request:

----
$ pki -d ~/.dogtag/pki-tomcat/ca/alias -c Secret.123 -n caadmin ca-cert-request-review 7 --action cancel
----

In PKI 10.4.5 or later the server will generate a log with [Outcome=Failure]:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Failure][ReqID=7]
[InfoName=cancelReason][InfoValue=<null>] certificate request processed
----

Prior to 10.4.5 the server will generate the a log with [Outcome=Success]:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Success][ReqID=7]
[InfoName=cancelReason][InfoValue=<null>] certificate request processed
----

=== Case 4: Invalid request ===

Use PKI CLI to submit an invalid certificate request:

----
$ pki -c Secret.123 client-cert-request UID=testuser --profile caServerCert
----

The server will generate the following logs:

----
[AuditEvent=CERT_REQUEST_PROCESSED][SubjectID=$NonRoleUser$][Outcome=Failure][Re
qID=7][InfoName=rejectReason][InfoValue=Request 7 Rejected - Subject Name Not Ma
tched UID=testuser] certificate request processed
----

== CERT_STATUS_CHANGE_REQUEST ==

`CERT_STATUS_CHANGE_REQUEST` event is generated when a certificate status change request (e.g. revocation) is made (before approval process).

`CERT_STATUS_CHANGE_REQUEST_PROCESSED` event is generated when certificate status is changed (revoked, expired, on-hold, off-hold).

For example, execute the following command to put a certificate on-hold:

----
$ pki -d ~/.dogtag/pki-tomcat/ca/alias -c Secret.123 -n caadmin ca-cert-hold 0x4 --force
----

The server will generate the following logs:

----
[AuditEvent=CERT_STATUS_CHANGE_REQUEST][SubjectID=caadmin][Outcome=Success][ReqI
D=9][CertSerialNum=0x4][RequestType=on-hold] certificate revocation/unrevocation
 request made
[AuditEvent=CERT_STATUS_CHANGE_REQUEST_PROCESSED][SubjectID=caadmin][Outcome=Suc
cess][ReqID=9][CertSerialNum=0x4][RequestType=on-hold][RevokeReasonNum=6][Approv
al=complete] certificate status change request processed
----

== CMC_SIGNED_REQUEST_SIG_VERIFY ==

This even is triggered when CMC (agent-pre-signed) certificate requests or revocation requests are submitted and signature is verified.

Properties:

* SubjectID must be the UID of the person who submits the certificate enrollment or revocation request
* ReqType must be the request type (enrollment, or revocation)
* CertSubject must be the certificate subject name of the certificate request
* SignerInfo reflects the person who actually signs the CMC request

For example, prepare a root CA and link:https://github.com/dogtagpki/pki/blob/master/docs/installation/ca/Installing_CA_with_External_CA_Signing_Certificate.md[install a subordinate CA with external CA signing certificate]. Use CMC on the root CA to issue the subordinate CA signing certificate. The root CA will generate the following log:

----
[AuditEvent=CMC_SIGNED_REQUEST_SIG_VERIFY][SubjectID=$NonRoleUser$][Outcome=Succ
ess][ReqType=enrollment][CertSubject=CN=CA Signing Certificate,OU=pki-tomcat,O=E
XAMPLE][SignerInfo=PKI Administrator] agent pre-approved CMC request signature v
erification
----

= CRL Events =

== SCHEDULE_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `SCHEDULE_CRL_GENERATION` event when the CRL generation is scheduled manually.

For example, use the Web UI to update the CRL. The server will generate the following log immediately:

----
[AuditEvent=SCHEDULE_CRL_GENERATION][SubjectID=<username>][Outcome=Success] sche
dule for CRL generation
----

If the scheduling fails, the server will log the failure reason:

----
[AuditEvent=SCHEDULE_CRL_GENERATION][SubjectID=<username>][Outcome=Failure][Fail
ureReason=<reason>] schedule for CRL generation
----

== DELTA_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `DELTA_CRL_GENERATION` event when the delta CRL generation is complete.

For example, enable delta CRL, use the Web UI to update the CRL. The server will generate the following log when the delta CRL generation is complete:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Success][CRLnum=<C
RL number>] Delta CRL generation
----

If noCRLIfNoRevokedCert is true and there is no revoked certificates, the server will generate the following log:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Success][Info=No R
evoked Certificates] Delta CRL generation
----

If the delta CRL generation fails, the server will log the failure reason:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Failure][FailureRe
ason=<reason>] Delta CRL generation
----

== DELTA_CRL_PUBLISHING ==

Since version 10.4.x the PKI Server will generate a `DELTA_CRL_PUBLISHING` event when the delta CRL publishing is complete.

For example, enable delta CRL, use the Web UI to update the CRL. The server will generate the following log when the delta CRL publishing is complete:

----
[AuditEvent=DELTA_CRL_PUBLISHING][SubjectID=$System$][Outcome=Success][CRLnum=<C
RL number>] Delta CRL publishing
----

If the delta CRL publishing fails, the server will log the failure reason:

----
[AuditEvent=DELTA_CRL_PUBLISHING][SubjectID=$System$][Outcome=Failure][CRLnum=<C
RL number>][FailureReason=<reason>] Delta CRL publishing
----

== FULL_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `FULL_CRL_GENERATION` event when the full CRL generation is complete.

For example, use the Web UI to update the CRL. The server will generate the following log when the full CRL generation is complete:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Success][CRLnum=<CR
L number>] Full CRL generation
----

If noCRLIfNoRevokedCert is true and there is no revoked certificates, the server will generate the following log:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Success][Info=No Re
voked Certificates] Full CRL generation
----

If the full CRL generation fails, the server will log the failure reason:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Failure][FailureRea
son=<reason>] Full CRL generation
----

== FULL_CRL_PUBLISHING ==

Since version 10.4.x the PKI Server will generate a `FULL_CRL_PUBLISHING` event when the full CRL publishing is complete.

For example, use the Web UI to update the CRL. The server will generate the following log when the full CRL publishing is complete:

----
[AuditEvent=FULL_CRL_PUBLISHING][SubjectID=$System$][Outcome=Success][CRLnum=<CR
L number>] Full CRL publishing
----

If the full CRL publishing fails, the server will log the failure reason:

----
[AuditEvent=FULL_CRL_PUBLISHING][SubjectID=$System$][Outcome=Failure][CRLnum=<CR
L number>][FailureReason=<reason>] Full CRL publishing
----

== CRL_RETRIEVAL ==

== CRL_VALIDATION ==

= OCSP Events =

== OCSP_GENERATION ==

Since version 10.5 an `OCSP_GENERATION` event will be generated for each OCSP response generated by CA's internal OCSP responder.

For example, use the link:https://www.dogtagpki.org/wiki/OCSPClient[OCSPClient] to submit an OCSP request:

----
$ OCSPClient \
    -d ~/.dogtag/pki-tomcat/ca/alias \
    -h $HOSTNAME \
    -p 8080 \
    -t /ca/ocsp \
    -c ca_signing \
    --serial 1
CertID.serialNumber=1
CertStatus=Good
----

The server will generate the following log when the OCSP response generation is complete:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Success] OCSP resp
onse generation
----

If the OCSP response generation fails, the server will log the failure reason:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=<reason>] OCSP response generation
----

For example, if the CA internal OCSP responder is disabled, the following log will be generated:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=OCSP service disabled] OCSP response generation
----

See also:

* link:https://github.com/dogtagpki/pki/issues/2959[Ticket #2959: Missing authority ID in LWCA signing audit events]
* link:OCSP-Audit-Events#ocsp_generation[OCSP_GENERATION in OCSP audit events]
* link:Configuring-Internal-OCSP-Responder[Configuring Internal OCSP Responder]

= Random Number Generator Events =

See link:https://www.dogtagpki.org/wiki/PKI_Server_Audit_Events#Random_Number_Generator_Events[Random Number Generator Events].
