= Overview =

CA audit events can be configured in log.instance.SignedAudit.events property.

= Default Events =

* link:https://github.com/dogtagpki/pki/blob/master/docs/admin/Default_CA_Audit_Events.md[Default CA Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_6_BRANCH/docs/admin/Default_CA_Audit_Events.md[PKI 10.6 Default CA Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_5_BRANCH/docs/admin/Default_CA_Audit_Events.md[PKI 10.5 Default CA Audit Events]

= Signing Info Events =

There are two types of CAs:

* the host CA is the primary CA that runs in the CA subsystem
* link:Lightweight-CA[Lightweight CA] are subordinate CAs under the host CA that are also running in the same CA subsystem

Each of the above CA's has a unique ID called '''authority ID'''. For host CA, the authority ID can be omitted.

When the PKI server is started, the server will generate signing info logs for each CA to indicate which keys are used for certificate signing, OCSP signing, and CRL signing. When a new lightweight sub-CA is added, the server will also generate the signing info logs for the new sub-CA.

== CERT_SIGNING_INFO ==

See link:CERT_SIGNING_INFO-Audit-Event[CERT_SIGNING_INFO Audit Event].

== OCSP_SIGNING_INFO ==

See link:OCSP_SIGNING_INFO-Audit-Event[OCSP_SIGNING_INFO Audit Event].

== CRL_SIGNING_INFO ==

See link:CRL_SIGNING_INFO-Audit-Event[CRL_SIGNING_INFO Audit Event].

= Certificate Events =

== PROFILE_CERT_REQUEST ==

See link:PROFILE_CERT_REQUEST-Audit-Event[PROFILE_CERT_REQUEST Audit Event].

== CERT_REQUEST_PROCESSED ==

See link:CERT_REQUEST_PROCESSED-Audit-Event[CERT_REQUEST_PROCESSED Audit Event].

== CERT_STATUS_CHANGE_REQUEST ==

See link:CERT_STATUS_CHANGE_REQUEST-Audit-Event[CERT_STATUS_CHANGE_REQUEST Audit Event].

== CERT_STATUS_CHANGE_REQUEST_PROCESSED ==

See link:CERT_STATUS_CHANGE_REQUEST_PROCESSED-Audit-Event[CERT_STATUS_CHANGE_REQUEST_PROCESSED Audit Event].

== CMC_SIGNED_REQUEST_SIG_VERIFY ==

See link:CMC_SIGNED_REQUEST_SIG_VERIFY-Audit-Event[CMC_SIGNED_REQUEST_SIG_VERIFY Audit Event].

= CRL Events =

== CONFIG_CRL_PROFILE ==

See link:CONFIG_CRL_PROFILE-Audit-Event[CONFIG_CRL_PROFILE Audit Event].

== SCHEDULE_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `SCHEDULE_CRL_GENERATION` event when the CRL generation is scheduled manually.

For example, use the Web UI to update the CRL. The server will generate the following log immediately:

----
[AuditEvent=SCHEDULE_CRL_GENERATION][SubjectID=<username>][Outcome=Success] sche
dule for CRL generation
----

If the scheduling fails, the server will log the failure reason:

----
[AuditEvent=SCHEDULE_CRL_GENERATION][SubjectID=<username>][Outcome=Failure][Fail
ureReason=<reason>] schedule for CRL generation
----

== DELTA_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `DELTA_CRL_GENERATION` event when the delta CRL generation is complete.

For example, enable delta CRL, use the Web UI to update the CRL. The server will generate the following log when the delta CRL generation is complete:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Success][CRLnum=<C
RL number>] Delta CRL generation
----

If noCRLIfNoRevokedCert is true and there is no revoked certificates, the server will generate the following log:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Success][Info=No R
evoked Certificates] Delta CRL generation
----

If the delta CRL generation fails, the server will log the failure reason:

----
[AuditEvent=DELTA_CRL_GENERATION][SubjectID=$System$][Outcome=Failure][FailureRe
ason=<reason>] Delta CRL generation
----

== DELTA_CRL_PUBLISHING ==

Since version 10.4.x the PKI Server will generate a `DELTA_CRL_PUBLISHING` event when the delta CRL publishing is complete.

For example, enable delta CRL, use the Web UI to update the CRL. The server will generate the following log when the delta CRL publishing is complete:

----
[AuditEvent=DELTA_CRL_PUBLISHING][SubjectID=$System$][Outcome=Success][CRLnum=<C
RL number>] Delta CRL publishing
----

If the delta CRL publishing fails, the server will log the failure reason:

----
[AuditEvent=DELTA_CRL_PUBLISHING][SubjectID=$System$][Outcome=Failure][CRLnum=<C
RL number>][FailureReason=<reason>] Delta CRL publishing
----

== FULL_CRL_GENERATION ==

Since version 10.4.x the PKI Server will generate a `FULL_CRL_GENERATION` event when the full CRL generation is complete.

For example, use the Web UI to update the CRL. The server will generate the following log when the full CRL generation is complete:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Success][CRLnum=<CR
L number>] Full CRL generation
----

If noCRLIfNoRevokedCert is true and there is no revoked certificates, the server will generate the following log:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Success][Info=No Re
voked Certificates] Full CRL generation
----

If the full CRL generation fails, the server will log the failure reason:

----
[AuditEvent=FULL_CRL_GENERATION][SubjectID=$System$][Outcome=Failure][FailureRea
son=<reason>] Full CRL generation
----

== FULL_CRL_PUBLISHING ==

Since version 10.4.x the PKI Server will generate a `FULL_CRL_PUBLISHING` event when the full CRL publishing is complete.

For example, use the Web UI to update the CRL. The server will generate the following log when the full CRL publishing is complete:

----
[AuditEvent=FULL_CRL_PUBLISHING][SubjectID=$System$][Outcome=Success][CRLnum=<CR
L number>] Full CRL publishing
----

If the full CRL publishing fails, the server will log the failure reason:

----
[AuditEvent=FULL_CRL_PUBLISHING][SubjectID=$System$][Outcome=Failure][CRLnum=<CR
L number>][FailureReason=<reason>] Full CRL publishing
----

== CRL_RETRIEVAL ==

== CRL_VALIDATION ==

= OCSP Events =

== OCSP_GENERATION ==

Since version 10.5 an `OCSP_GENERATION` event will be generated for each OCSP response generated by CA's internal OCSP responder.

For example, use the link:Using-OCSPClient[OCSPClient] to submit an OCSP request:

----
$ OCSPClient \
    -d ~/.dogtag/pki-tomcat/ca/alias \
    -h $HOSTNAME \
    -p 8080 \
    -t /ca/ocsp \
    -c ca_signing \
    --serial 1
CertID.serialNumber=1
CertStatus=Good
----

The server will generate the following log when the OCSP response generation is complete:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Success] OCSP resp
onse generation
----

If the OCSP response generation fails, the server will log the failure reason:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=<reason>] OCSP response generation
----

For example, if the CA internal OCSP responder is disabled, the following log will be generated:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=OCSP service disabled] OCSP response generation
----

See also:

* link:https://github.com/dogtagpki/pki/issues/2959[Ticket #2959: Missing authority ID in LWCA signing audit events]
* link:OCSP-Audit-Events#ocsp_generation[OCSP_GENERATION in OCSP audit events]
* link:Configuring-Internal-OCSP-Responder[Configuring Internal OCSP Responder]

= Random Number Generator Events =

See link:https://github.com/dogtagpki/pki/wiki/Signed-Audit-Events#random-number-generator-events[Random Number Generator Events].
