= Request =

* **Operation:** `GET /ca/rest/authorities/<id>/chain`
* **Headers:**
** `Accept`: `application/pkcs7-mime`, `application/x-pem-file`

= Response =

----
$ curl \
    -k \
    -s \
    -H "Accept: application/x-pem-file" \
    https://localhost.localdomain:8443/ca/rest/authorities/b6c33f78-74ce-4ce8-9368-132778770572/chain
-----BEGIN PKCS7-----
MIIErAYJKoZIhvcNAQcCoIIEnTCCBJkCAQExADALBgkqhkiG9w0BBwGgggSBMIIEfTCCAuWgAwIB
AgIQZU2UOsOp00CCc0s5+cMOMjANBgkqhkiG9w0BAQsFADBIMRAwDgYDVQQKDAdFWEFNUExFMRMw
EQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQDDBZDQSBTaWduaW5nIENlcnRpZmljYXRlMB4XDTIz
MTAyNDAxNDkwMFoXDTQzMTAyNDAxNDkwMFowSDEQMA4GA1UECgwHRVhBTVBMRTETMBEGA1UECwwK
cGtpLXRvbWNhdDEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTCCAaIwDQYJKoZIhvcN
AQEBBQADggGPADCCAYoCggGBANglqsosqV9PlEH1bJ2oULYmlSEpYDwx8qKDB5G29ZIECOMQGpCR
euw/Ex4W6aZlWd3g1uxHJn3+zfQTWPuXyq8FPhVmW3XGyIHWTEXU5pPX6M3Stp+7hBGfCBuRl00Z
UiVBieMHzlZsnhsjrMc6zxrxUN1DgnXjaS7RB4fqPfgokhZS/EFA7auKm5B+YaRznxHBTvQK8s45
aLPPY7jBZ+JdzxE1RgKG4bHLgPKEW37w2y1gOHBpN/wc9cR7NbhDbJx99aChqvRnd48yYuqwH5mR
3JmqyXqBeB4jsP5T5tGXhs2PEKp8umAXaPLtw6mrB7ruNZehW5dRQLgbx2Fo3PTPQ/n3HpLVSpxR
vCosNGVE1e7wW7KcKUWo90HF7po0ZxcSwvCFnUQsrfQ9nhTqQik/I1HMAsuI4ipwUuD2BQmlYzOk
FdqUkdh8JFxeHw+M/JH9uzBDKaG/u/YlEoiIW1ZQyDxbozMJE3wHxHsveYEZyQNTTBJqUM0g3frF
34z1mwIDAQABo2MwYTAfBgNVHSMEGDAWgBT8bh/F26l1ddxUzlLagnRl0HvKJTAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU/G4fxdupdXXcVM5S2oJ0ZdB7yiUwDQYJ
KoZIhvcNAQELBQADggGBAHW6O6C3dCMhzYTkrJrQio8CPAWGAhytBMzRxB/BCl0YsqWQV5qqBRhH
bkabu9cmNiNOFRjiRRKIVErCj9cVWKH5DADWYq/MmB68T+ZlBOlURGamQOmIAwK8ekC6SKLt+RiW
BKbYVz0dSAJZHWcBu2OQ8U5CAZ+eBxshqAPDiL1uq8VpMq72k2+wl+S+s1hmQOryMWdf3wz7aohZ
PQmmPPD2yLV4tiR4GwNEwt62GKQoI9Dzq8DNl52ZBngXf6cVwsn7EbM1os+SzEvnHPu2P8y87PbX
GO0KP+lgCMXkwf6FYPMCwNmTBTrFKWzfMnMHPVq22XFqi2c5zfQI9gIbiutH++wqp0aacb+urQtY
MHKdMFtN/Nwu+N07vJT3QM7Q22mMZ7JW6h5mfBFZjbLcwBAih1xfJS7v4DN3DznwXqTlFtRJYKin
VzF9QbWiyE+rO1kqmUlnUJYdNsazLO9JwTSP4G4/SYVaSFBDfO9LOd1KOqPw2/Nw2l3voI5pMovx
hzEA
-----END PKCS7-----
----