= Request =

* **Operation:** `GET /ca/rest/authorities/<id>/cert`
* **Headers:**
** `Accept`: `application/pkix-cert`, `application/x-pem-file`

= Response =

----
$ curl \
    -k \
    -s \
    -H "Accept: application/x-pem-file" \
    https://localhost.localdomain:8443/ca/rest/authorities/b6c33f78-74ce-4ce8-9368-132778770572/cert
-----BEGIN CERTIFICATE-----
MIIEfTCCAuWgAwIBAgIQZU2UOsOp00CCc0s5+cMOMjANBgkqhkiG9w0BAQsFADBIMRAwDgYDVQQK
DAdFWEFNUExFMRMwEQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQDDBZDQSBTaWduaW5nIENlcnRp
ZmljYXRlMB4XDTIzMTAyNDAxNDkwMFoXDTQzMTAyNDAxNDkwMFowSDEQMA4GA1UECgwHRVhBTVBM
RTETMBEGA1UECwwKcGtpLXRvbWNhdDEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTCC
AaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBANglqsosqV9PlEH1bJ2oULYmlSEpYDwx8qKD
B5G29ZIECOMQGpCReuw/Ex4W6aZlWd3g1uxHJn3+zfQTWPuXyq8FPhVmW3XGyIHWTEXU5pPX6M3S
tp+7hBGfCBuRl00ZUiVBieMHzlZsnhsjrMc6zxrxUN1DgnXjaS7RB4fqPfgokhZS/EFA7auKm5B+
YaRznxHBTvQK8s45aLPPY7jBZ+JdzxE1RgKG4bHLgPKEW37w2y1gOHBpN/wc9cR7NbhDbJx99aCh
qvRnd48yYuqwH5mR3JmqyXqBeB4jsP5T5tGXhs2PEKp8umAXaPLtw6mrB7ruNZehW5dRQLgbx2Fo
3PTPQ/n3HpLVSpxRvCosNGVE1e7wW7KcKUWo90HF7po0ZxcSwvCFnUQsrfQ9nhTqQik/I1HMAsuI
4ipwUuD2BQmlYzOkFdqUkdh8JFxeHw+M/JH9uzBDKaG/u/YlEoiIW1ZQyDxbozMJE3wHxHsveYEZ
yQNTTBJqUM0g3frF34z1mwIDAQABo2MwYTAfBgNVHSMEGDAWgBT8bh/F26l1ddxUzlLagnRl0HvK
JTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU/G4fxdupdXXcVM5S
2oJ0ZdB7yiUwDQYJKoZIhvcNAQELBQADggGBAHW6O6C3dCMhzYTkrJrQio8CPAWGAhytBMzRxB/B
Cl0YsqWQV5qqBRhHbkabu9cmNiNOFRjiRRKIVErCj9cVWKH5DADWYq/MmB68T+ZlBOlURGamQOmI
AwK8ekC6SKLt+RiWBKbYVz0dSAJZHWcBu2OQ8U5CAZ+eBxshqAPDiL1uq8VpMq72k2+wl+S+s1hm
QOryMWdf3wz7aohZPQmmPPD2yLV4tiR4GwNEwt62GKQoI9Dzq8DNl52ZBngXf6cVwsn7EbM1os+S
zEvnHPu2P8y87PbXGO0KP+lgCMXkwf6FYPMCwNmTBTrFKWzfMnMHPVq22XFqi2c5zfQI9gIbiutH
++wqp0aacb+urQtYMHKdMFtN/Nwu+N07vJT3QM7Q22mMZ7JW6h5mfBFZjbLcwBAih1xfJS7v4DN3
DznwXqTlFtRJYKinVzF9QbWiyE+rO1kqmUlnUJYdNsazLO9JwTSP4G4/SYVaSFBDfO9LOd1KOqPw
2/Nw2l3voI5pMovxhw==
-----END CERTIFICATE-----
----