= Request =

* **Path:** `/ca/rest/authorities/{id}/chain`
* **Method:** `GET`
* **Headers:**
** `Accept`: `application/x-pem-file`, `application/pkcs7-mime`

= Response =

.PEM
[%collapsible]
====
----
$ curl \
    -k \
    -s \
    -H "Accept: application/x-pem-file" \
    https://localhost.localdomain:8443/ca/rest/authorities/b6c33f78-74ce-4ce8-9368-132778770572/chain
-----BEGIN PKCS7-----
MIIErAYJKoZIhvcNAQcCoIIEnTCCBJkCAQExADALBgkqhkiG9w0BBwGgggSBMIIEfTCCAuWgAwIB
AgIQZU2UOsOp00CCc0s5+cMOMjANBgkqhkiG9w0BAQsFADBIMRAwDgYDVQQKDAdFWEFNUExFMRMw
EQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQDDBZDQSBTaWduaW5nIENlcnRpZmljYXRlMB4XDTIz
MTAyNDAxNDkwMFoXDTQzMTAyNDAxNDkwMFowSDEQMA4GA1UECgwHRVhBTVBMRTETMBEGA1UECwwK
cGtpLXRvbWNhdDEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTCCAaIwDQYJKoZIhvcN
AQEBBQADggGPADCCAYoCggGBANglqsosqV9PlEH1bJ2oULYmlSEpYDwx8qKDB5G29ZIECOMQGpCR
euw/Ex4W6aZlWd3g1uxHJn3+zfQTWPuXyq8FPhVmW3XGyIHWTEXU5pPX6M3Stp+7hBGfCBuRl00Z
UiVBieMHzlZsnhsjrMc6zxrxUN1DgnXjaS7RB4fqPfgokhZS/EFA7auKm5B+YaRznxHBTvQK8s45
aLPPY7jBZ+JdzxE1RgKG4bHLgPKEW37w2y1gOHBpN/wc9cR7NbhDbJx99aChqvRnd48yYuqwH5mR
3JmqyXqBeB4jsP5T5tGXhs2PEKp8umAXaPLtw6mrB7ruNZehW5dRQLgbx2Fo3PTPQ/n3HpLVSpxR
vCosNGVE1e7wW7KcKUWo90HF7po0ZxcSwvCFnUQsrfQ9nhTqQik/I1HMAsuI4ipwUuD2BQmlYzOk
FdqUkdh8JFxeHw+M/JH9uzBDKaG/u/YlEoiIW1ZQyDxbozMJE3wHxHsveYEZyQNTTBJqUM0g3frF
34z1mwIDAQABo2MwYTAfBgNVHSMEGDAWgBT8bh/F26l1ddxUzlLagnRl0HvKJTAPBgNVHRMBAf8E
BTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU/G4fxdupdXXcVM5S2oJ0ZdB7yiUwDQYJ
KoZIhvcNAQELBQADggGBAHW6O6C3dCMhzYTkrJrQio8CPAWGAhytBMzRxB/BCl0YsqWQV5qqBRhH
bkabu9cmNiNOFRjiRRKIVErCj9cVWKH5DADWYq/MmB68T+ZlBOlURGamQOmIAwK8ekC6SKLt+RiW
BKbYVz0dSAJZHWcBu2OQ8U5CAZ+eBxshqAPDiL1uq8VpMq72k2+wl+S+s1hmQOryMWdf3wz7aohZ
PQmmPPD2yLV4tiR4GwNEwt62GKQoI9Dzq8DNl52ZBngXf6cVwsn7EbM1os+SzEvnHPu2P8y87PbX
GO0KP+lgCMXkwf6FYPMCwNmTBTrFKWzfMnMHPVq22XFqi2c5zfQI9gIbiutH++wqp0aacb+urQtY
MHKdMFtN/Nwu+N07vJT3QM7Q22mMZ7JW6h5mfBFZjbLcwBAih1xfJS7v4DN3DznwXqTlFtRJYKin
VzF9QbWiyE+rO1kqmUlnUJYdNsazLO9JwTSP4G4/SYVaSFBDfO9LOd1KOqPw2/Nw2l3voI5pMovx
hzEA
-----END PKCS7-----
----
====

.DER
[%collapsible]
====
----
$ curl \
    -k \
    -s \
    -H "Accept: application/pkcs7-mime" \
    -o - \
    https://localhost.localdomain:8443/ca/rest/authorities/803ff016-8e45-4d82-aa36-df23f314ae31/chain \
    | openssl pkcs7 -print_certs -inform der
subject=O = EXAMPLE, OU = pki-tomcat, CN = CA Signing Certificate
issuer=O = EXAMPLE, OU = pki-tomcat, CN = CA Signing Certificate
-----BEGIN CERTIFICATE-----
MIIEfTCCAuWgAwIBAgIQZU2UOsOp00CCc0s5+cMOMjANBgkqhkiG9w0BAQsFADBI
MRAwDgYDVQQKDAdFWEFNUExFMRMwEQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQD
DBZDQSBTaWduaW5nIENlcnRpZmljYXRlMB4XDTIzMTAyNDAxNDkwMFoXDTQzMTAy
NDAxNDkwMFowSDEQMA4GA1UECgwHRVhBTVBMRTETMBEGA1UECwwKcGtpLXRvbWNh
dDEfMB0GA1UEAwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTCCAaIwDQYJKoZIhvcN
AQEBBQADggGPADCCAYoCggGBANglqsosqV9PlEH1bJ2oULYmlSEpYDwx8qKDB5G2
9ZIECOMQGpCReuw/Ex4W6aZlWd3g1uxHJn3+zfQTWPuXyq8FPhVmW3XGyIHWTEXU
5pPX6M3Stp+7hBGfCBuRl00ZUiVBieMHzlZsnhsjrMc6zxrxUN1DgnXjaS7RB4fq
PfgokhZS/EFA7auKm5B+YaRznxHBTvQK8s45aLPPY7jBZ+JdzxE1RgKG4bHLgPKE
W37w2y1gOHBpN/wc9cR7NbhDbJx99aChqvRnd48yYuqwH5mR3JmqyXqBeB4jsP5T
5tGXhs2PEKp8umAXaPLtw6mrB7ruNZehW5dRQLgbx2Fo3PTPQ/n3HpLVSpxRvCos
NGVE1e7wW7KcKUWo90HF7po0ZxcSwvCFnUQsrfQ9nhTqQik/I1HMAsuI4ipwUuD2
BQmlYzOkFdqUkdh8JFxeHw+M/JH9uzBDKaG/u/YlEoiIW1ZQyDxbozMJE3wHxHsv
eYEZyQNTTBJqUM0g3frF34z1mwIDAQABo2MwYTAfBgNVHSMEGDAWgBT8bh/F26l1
ddxUzlLagnRl0HvKJTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAd
BgNVHQ4EFgQU/G4fxdupdXXcVM5S2oJ0ZdB7yiUwDQYJKoZIhvcNAQELBQADggGB
AHW6O6C3dCMhzYTkrJrQio8CPAWGAhytBMzRxB/BCl0YsqWQV5qqBRhHbkabu9cm
NiNOFRjiRRKIVErCj9cVWKH5DADWYq/MmB68T+ZlBOlURGamQOmIAwK8ekC6SKLt
+RiWBKbYVz0dSAJZHWcBu2OQ8U5CAZ+eBxshqAPDiL1uq8VpMq72k2+wl+S+s1hm
QOryMWdf3wz7aohZPQmmPPD2yLV4tiR4GwNEwt62GKQoI9Dzq8DNl52ZBngXf6cV
wsn7EbM1os+SzEvnHPu2P8y87PbXGO0KP+lgCMXkwf6FYPMCwNmTBTrFKWzfMnMH
PVq22XFqi2c5zfQI9gIbiutH++wqp0aacb+urQtYMHKdMFtN/Nwu+N07vJT3QM7Q
22mMZ7JW6h5mfBFZjbLcwBAih1xfJS7v4DN3DznwXqTlFtRJYKinVzF9QbWiyE+r
O1kqmUlnUJYdNsazLO9JwTSP4G4/SYVaSFBDfO9LOd1KOqPw2/Nw2l3voI5pMovx
hw==
-----END CERTIFICATE-----

subject=O = EXAMPLE, CN = Certificate Authority
issuer=O = EXAMPLE, OU = pki-tomcat, CN = CA Signing Certificate
-----BEGIN CERTIFICATE-----
MIIEkjCCAvqgAwIBAgIRAK5TrveZZxASl77bzVW7VsowDQYJKoZIhvcNAQELBQAw
SDEQMA4GA1UECgwHRVhBTVBMRTETMBEGA1UECwwKcGtpLXRvbWNhdDEfMB0GA1UE
AwwWQ0EgU2lnbmluZyBDZXJ0aWZpY2F0ZTAeFw0yMzEwMjQxNzQzMDJaFw00MzEw
MjQwMTQ5MDBaMCIxEDAOBgNVBAoMB0VYQU1QTEUxDjAMBgNVBAMMBVRlc3Q5MIIB
ojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA2HwFNCXYfMdmNUmvglICXyPG
IURv7cznD+aA5IxBmKTJZbDpCWUxBpzdSuORuB3D8BXKDW8Mo5rBC32p6d3IyDaq
Csh7iGRLlFk39N8lweQJh39gaOCLTc/dpeeUFUYkDMjWWUDQIbVhbVAiWcQk4kvo
75QAEjZm8WIutRZxu17AJiS+xEsW95h/uknDi/sGO4TpviEyat0j1UHxOX/1Rvnz
cljyUfOLMlGYg7CB6HOF3SXG2PFUOVcMGIUPqd2QxejfUEKQRJeuoyRCPOE4ytNo
FUh9AnhAV96Zns1tQ6YogIn0pCEu7Sk93Nd/uvRhTXyRdkOZmSN9B86o5OrPvoS5
OAgqbA1torbEOgJ6OZ06WENkJXwW4FWITTt26ermXBm/wSpC4oBE4vsDv8uJ2CBg
ezdQAFOO/mEonq85TtCmHpowNajWTgSYC6pwccPkJ6oz8h7I8wuEgi+GiyOOoFlE
u7Wlwgtb7Xm2neFn/esAH5smunfYSheSmVJ80s8FAgMBAAGjgZwwgZkwHwYDVR0j
BBgwFoAU/G4fxdupdXXcVM5S2oJ0ZdB7yiUwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAcYwHQYDVR0OBBYEFJoKwOt2wtusIzCnIONdqsdtqzbvMDYGCCsG
AQUFBwEBBCowKDAmBggrBgEFBQcwAYYaaHR0cDovL2ZlZG9yYTo4MDgwL2NhL29j
c3AwDQYJKoZIhvcNAQELBQADggGBAFekP8R6mJd8CE7VJlLkfz7Hf2dKR8zg5Adx
qCDFN3b3uhQVmT/5HrRhUg+YLbQJ6AuktESa35bEBeqJzdQWvG0EEAQWWCmR92ii
7A7R0lAQzRL1MzQ0K18MuNr21MUUoXXlSZfSjl9rtatZS7c04xp7/QzR2OBb3/aU
LLgy6pOxSLjf6YvTN89x2ly5vzJMT4Xa96JgJKKR2IL087uzpxq8FsxJfmw0IcKP
oxieqn181n77LsqVS595foOqLb1sr4LZvUs9GyF/umKEoG8sUym0CsaJ0SgEJnxZ
AwdmLYXo3XKC9Px3ZCtmk2YKWrsF3JJid4pnwymdAV0cKoab7jrUCAsODLqx/r/N
lhN/n2uy9Hs5167Z/3LAd/+c/8pdqtAgBzTUDO2dIHTZYK144Ru9POpkz+TfVfbY
45zNFun9dUFDdgL03wYIolkaU8iPoRhzW1kpK0lc8cKs+/2nGHVKP69lenibwQ5R
SqQIygQ6E2tjEdg/rnRYUesZQ4PnZw==
-----END CERTIFICATE-----
----
====
