= Overview =

This page describes the process to enroll a certificate using a directory-authenticated profile (e.g. `caDirUserCert`).

= Prerequisites =

* link:Configuring-Directory-Authenticated-Certificate-Profiles[Configure] a profile to authenticate against users in DS.

= Enrollment using pki client-cert-request =

The `pki client-cert-request` command can be used to generate a key in an NSS database (default: `~/.dogtag/nssdb`), create a certificate request, then submit it to the CA.

To enroll a certificate for a user in DS, specify the username (e.g. `testuser`) in the following command, and it will prompt for the LDAP password:

----
$ pki client-cert-request \
    --profile caDirUserCert \
    --username testuser \
    --password
Password: ********
-----------------------------
Submitted certificate request
-----------------------------
  Request ID: 16
  Type: enrollment
  Request Status: complete
  Operation Result: success
  Certificate ID: 0xc
----

The certificate will be issued immediately.

= Enrollment using XML Request =

The enrollment can also be done manually using an XML request.

First, link:Generating-Certificate-Request[generate] a certificate request with subject DN `UID=<username>` and store it into a file (e.g. `testuser.csr`).

Then retrieve the template for the XML request for the profile:

----
$ pki ca-cert-request-profile-show caDirUserCert --output request.xml
----

Insert the username of the DS user with the following command:

----
$ xmlstarlet edit --inplace \
    -s "/CertEnrollmentRequest/Attributes" --type elem --name "Attribute" -v "testuser" \
    -i "/CertEnrollmentRequest/Attributes/Attribute[not(@name)]" -t attr -n "name" -v "uid" \
    request.xml
----

Insert the password of the DS user with the following command:

----
$ xmlstarlet edit --inplace \
    -s "/CertEnrollmentRequest/Attributes" --type elem --name "Attribute" -v "Secret.123" \
    -i "/CertEnrollmentRequest/Attributes/Attribute[not(@name)]" -t attr -n "name" -v "pwd" \
    request.xml
----

Insert CSR with the following command:

----
$ xmlstarlet edit --inplace \
    -u "/CertEnrollmentRequest/Input/Attribute[@name='cert_request']/Value" \
    -v "$(cat testuser.csr)" \
    request.xml
----

The final XML request should look like the following:

----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<CertEnrollmentRequest>
    <Attributes>
        <Attribute name="uid">testuser</Attribute>
        <Attribute name="pwd">Secret.123</Attribute>
    </Attributes>
    ...
    <Input ...>
        ...
        <Attribute name="cert_request">
            <Value>-----BEGIN CERTIFICATE REQUEST-----
MIIBfTCB5wIBADAaMRgwFgYKCZImiZPyLGQBARMIdGVzdHVzZXIwgZ8wDQYJKoZI
hvcNAQEBBQADgY0AMIGJAoGBALvbVD1U6nzYh61tjjKC24mBqeKjABpEpl5CqyrT
guX5PtHdrlOUbWOro8vNzXMWccm3IVEgJHTQyQdxenIkIGcwMXu9XlwI6zph1UaT
oJ1CRh8z2Tn5Ncg6LvOejDJg+XtKEXEOTq0qzztBXTEe9uuKYb9AKc6iSmtfM7ZO
nCZPAgMBAAGgJDAiBggrBgEFBQcHFzEWBBTmaclfLv+kkK5z5kTMP54dlnecUDAN
BgkqhkiG9w0BAQQFAAOBgQBeVpuaZ1Sr1tHznU/0xSQ3OvEd3poJ0mk44KRYFdwu
NbeZaGtvhYFwLfQH0mMOWrzvrh0a2eXWC8z51iuqvNJCHDX+rUGIYpZH8mtY3jMp
8mlDWClrcpAdmJTj0ztFggmBd0Zvl4EqPqp0SY5YYLxwEwcKXT/g8bDdS5UM68hq
QA==
-----END CERTIFICATE REQUEST-----</Value>
            ...
        </Attribute>
    </Input>
</CertEnrollmentRequest>
----

Then submit the request with the following command:

----
$ pki ca-cert-request-submit request.xml
-----------------------------
Submitted certificate request
-----------------------------
  Request ID: 16
  Type: enrollment
  Request Status: complete
  Operation Result: success
  Certificate ID: 0xc
----

The certificate will be issued immediately.

= Retrieving Certificate =

To retrieve the certificate into a file:

----
$ pki ca-cert-export <certificate ID> --output-file <filename>
----

= Importing Certificate =

To import the certificate into NSS database:

----
$ pki client-cert-import <nickname> --serial <certificate ID>
----

Verify with the following command:

----
$ pki client-cert-find
----------------------
2 certificate(s) found
----------------------
  Serial Number: 0x1
  Nickname: CA Signing Certificate - EXAMPLE
  Subject DN: CN=CA Signing Certificate,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,O=EXAMPLE

  Serial Number: 0xc
  Nickname: testuser
  Subject DN: UID=testuser,OU=People,DC=example,DC=com
  Issuer DN: CN=CA Signing Certificate,O=EXAMPLE
----------------------------
Number of entries returned 2
----------------------------
----
