= Overview =

By default the CI will perform the tests using link:https://copr.fedorainfracloud.org/coprs/g/pki/master[@pki/master] repository. Sometimes it's necessary to perform the tests using a different repository (e.g. to test dependency changes). This can be done by creating a GitHub secret called `BASE64_REPO` to store the base64-encoded value of the test repository name. To reset the test repository simply remove the secret.

= Configuring Test Repository =

For example, to test using link:https://copr.fedorainfracloud.org/coprs/edewata/pki[edewata/pki] repository:

----
$ echo "edewata/pki" | base64
ZWRld2F0YS9wa2kK
----

Then create the secret:

* Go to *Settings* -> *Secrets*.
* Click *New repository secret*.
* Enter `BASE64_REPO` as the secret name.
* Enter the base64-encoded value as the secret value.
* Click *Add secret*

= Before Testing =

Sometimes old versions of packages in COPR can get selected instead of the test packages, so it is a good idea to delete any non-relevant builds from your test repo before starting.   

= Resetting Test Repository =

To reset the test repository, remove the secret:

* Go to *Settings* -> *Secrets*.
* Click *Remove* next to `BASE64_REPO`.
* Click *Yes, remove this secret*.
