= Overview =

Each PKI subsystem provides a logging service using link:https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/package-summary.html[java.util.logging] (JUL) framework. The logging service which can be used to troubleshoot issues in the subsystem (e.g. database access, certificate issuance, key archival).

For older versions see:

* link:https://www.dogtagpki.org/wiki/PKI_10.6_Subsystem_Debug_Log[PKI 10.6 Subsystem Debug Log]
* link:https://www.dogtagpki.org/wiki/PKI_10.5_Subsystem_Debug_Log[PKI 10.5 Subsystem Debug Log]
* link:https://www.dogtagpki.org/wiki/PKI_10.3_Subsystem_Debug_Log[PKI 10.3 Subsystem Debug Log]

= Configuration =

The logging configuration is located at:

* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/webapps/ca/WEB-INF/classes/logging.properties[/usr/share/pki/ca/webapps/ca/WEB-INF/classes/logging.properties]
* link:https://github.com/dogtagpki/pki/blob/master/base/kra/shared/webapps/kra/WEB-INF/classes/logging.properties[/usr/share/pki/kra/webapps/kra/WEB-INF/classes/logging.properties]
* link:https://github.com/dogtagpki/pki/blob/master/base/ocsp/shared/webapps/ocsp/WEB-INF/classes/logging.properties[/usr/share/pki/ocsp/webapps/ocsp/WEB-INF/classes/logging.properties]
* link:https://github.com/dogtagpki/pki/blob/master/base/tks/shared/webapps/tks/WEB-INF/classes/logging.properties[/usr/share/pki/tks/webapps/tks/WEB-INF/classes/logging.properties]
* link:https://github.com/dogtagpki/pki/blob/master/base/tps/shared/webapps/tps/WEB-INF/classes/logging.properties[/usr/share/pki/tps/webapps/tps/WEB-INF/classes/logging.properties]
* link:https://github.com/dogtagpki/pki/blob/master/base/acme/webapps/acme/WEB-INF/classes/logging.properties[/usr/share/pki/acme/webapps/acme/WEB-INF/classes/logging.properties]

The logging levels for PKI classes are overridden by the `debug.level` parameter in:

* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/conf/CS.cfg[/var/lib/pki/pki-tomcat/ca/conf/CS.cfg]
* link:https://github.com/dogtagpki/pki/blob/master/base/kra/shared/conf/CS.cfg[/var/lib/pki/pki-tomcat/kra/conf/CS.cfg]
* link:https://github.com/dogtagpki/pki/blob/master/base/ocsp/shared/conf/CS.cfg[/var/lib/pki/pki-tomcat/ocsp/conf/CS.cfg]
* link:https://github.com/dogtagpki/pki/blob/master/base/tks/shared/conf/CS.cfg[/var/lib/pki/pki-tomcat/tks/conf/CS.cfg]
* link:https://github.com/dogtagpki/pki/blob/master/base/tps/shared/conf/CS.cfg[/var/lib/pki/pki-tomcat/tps/conf/CS.cfg]

Note: There is no `CS.cfg` for ACME, so the logging level has to be configured in `logging.properties`. This will be addressed in the future.

By default the subsystem will log `INFO` messages or higher:

----
# in logging.properties
org.dogtagpki.level = INFO
com.netscape.level = INFO
netscape.level = INFO

# in CS.cfg
debug.level=10
----

The `debug.level` is mapped into JUL log level as follows:

|===
| PKI Log Level | SLF4J Log Level | JUL Log Level

| 0-1 (OBNOXIOUS)
| TRACE
| FINEST

| 2-5 (VERBOSE)
| DEBUG
| FINE

| 6-10 (INFORM)
| INFO
| INFO

| 11-15
| WARN
| WARNING

| >15
| ERROR
| SEVERE
|===

The subsystem will store the messages in `/var/lib/pki/pki-tomcat/logs/<subsystem>/debug.YYYY-MM-DD.log` which will be rotated daily and purged after 7 days.

= Displaying Current Debug Level =

To show the current debug level in subsystems other than ACME, execute the following command:

----
$ pki-server ca-config-show debug.level
10
----

For ACME, see the `*.level` properties in `/usr/share/pki/acme/webapps/acme/WEB-INF/classes/logging.properties`.

= Changing Debug Level =

To change the debug level (e.g. to log `FINE` messages or higher) in subsystems other than ACME, execute the following command:

----
$ pki-server ca-config-set debug.level 5
----

For ACME, change the `*.level` properties in `/usr/share/pki/acme/webapps/acme/WEB-INF/classes/logging.properties`.

Then restart the server.
