= Overview =

PKI server provides logging service using link:https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/package-summary.html[java.util.logging] (JUL) framework.

The configuration is located at `/var/lib/pki/pki-tomcat/conf/logging.properties` which by default is a link to link:https://github.com/dogtagpki/pki/blob/master/base/server/share/conf/logging.properties[/usr/share/pki/server/conf/logging.properties].

By default the server will only log WARNING or SEVERE messages:

----
.level = WARNING

org.mozilla.jss.level = WARNING
org.dogtagpki.level = WARNING
com.netscape.level = WARNING
netscape.level = WARNING
----

If the server is running as a systemd service, the messages will be logged in systemd journal.
If the server is being run using the `pki-server run` command, the messages will be logged on the console.

Note: The server may generate the following files in `/var/lib/pki/pki-tomcat/logs` but they are not actually used:

* `catalina.YYYY-MM-DD.log`
* `host-manager.YYYY-MM-DD.log`
* `localhost.YYYY-MM-DD.log`
* `manager.YYYY-MM-DD.log`

= Configuring Server Logging =

To change the server logging configuration, replace the `logging.properties` link with a copy of the default configuration:

----
$ rm -f /var/lib/pki/pki-tomcat/conf/logging.properties
$ cp /usr/share/pki/server/conf/logging.properties /var/lib/pki/pki-tomcat/conf
$ chown pkiuser.pkiuser /var/lib/pki/pki-tomcat/conf/logging.properties
----

Edit the `logging.properties` copy as needed, for example:

----
org.mozilla.jss.level = INFO
org.dogtagpki.level = INFO
com.netscape.level = INFO
netscape.level = INFO
----

Finally, restart the server.

= See Also =

* link:http://tomcat.apache.org/tomcat-9.0-doc/logging.html[Apache Tomcat 9 Logging]
