= Overview =

This page describes the process to switch the ID generators in an existing CA from the legacy **Sequential Serial Numbers** or **Random Serial Numbers v1** to **Random Serial Numbers v3**.

WARNING: Switching back from **Random Serial Numbers v3** to the legacy **Sequential Serial Numbers** or **Random Serial Numbers v1** is not supported.

= Configuration Process =

== Stopping PKI Server ==

To stop PKI server:

----
$ pki-server stop --wait
----

== Configuring Certificate Request ID Generator ==

To disable the legacy ID generator for certificate requests:

----
$ pki-server ca-config-unset dbs.beginRequestNumber
$ pki-server ca-config-unset dbs.endRequestNumber
$ pki-server ca-config-unset dbs.requestIncrement
$ pki-server ca-config-unset dbs.requestLowWaterMark
$ pki-server ca-config-unset dbs.requestCloneTransferNumber
$ pki-server ca-config-unset dbs.requestRangeDN
----

To enable the RSNv3 ID generator for certificate requests:

----
$ pki-server ca-config-set dbs.request.id.generator random
$ pki-server ca-config-set dbs.request.id.length 128
----

== Configuring Certificate ID Generator ==

To disable the legacy ID generator for certificates:

----
$ pki-server ca-config-unset dbs.beginSerialNumber
$ pki-server ca-config-unset dbs.endSerialNumber
$ pki-server ca-config-unset dbs.serialIncrement
$ pki-server ca-config-unset dbs.serialLowWaterMark
$ pki-server ca-config-unset dbs.serialCloneTransferNumber
$ pki-server ca-config-unset dbs.serialRangeDN
----

To enable the RSNv3 ID generator for certificates:

----
$ pki-server ca-config-set dbs.cert.id.generator random
$ pki-server ca-config-set dbs.cert.id.length 128
----

== Restarting PKI Server ==

To restart PKI server:

----
$ pki-server start --wait
----
