= Overview =

This document describes how to configure directory-authenticated certificate profiles:

* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caDirUserCert.cfg[caDirUserCert]: Dual-Use User Certificate Enrollment
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caECDirUserCert.cfg[caECDirUserCert]: Dual-Use ECC User Certificate Enrollment
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caDirUserRenewal.cfg[caDirUserRenewal]: User Certificate Self-Renewal

= Prerequisites =

Prepare a DS instance with users for authentication using passwords, for example:

----
$ ldapadd -H ldap://$HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: ou=People,dc=example,dc=com
objectclass: top
objectclass: organizationalUnit
ou: People

dn: uid=testuser,ou=People,dc=example,dc=com
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
uid: testuser
cn: Test User
sn: User
userPassword: Secret.123
EOF
----

Verify the authentication using the following command:

----
$ ldapsearch \
    -H ldap://$HOSTNAME \
    -x \
    -D "uid=testuser,ou=People,dc=example,dc=com" \
    -w Secret.123 \
    -b "dc=example,dc=com" \
    "(objectClass=*)"
----

= Configuring Directory-Authenticated Profile =

By default the directory-authenticated profiles (e.g. `/var/lib/pki/pki-tomcat/ca/profiles/ca/caDirUserCert.cfg`) are configured with `UserDirEnrollment` authentication manager:

----
auth.instance_id=UserDirEnrollment
----

Add the `UserDirEnrollment` authentication manager into `/var/lib/pki/pki-tomcat/ca/conf/CS.cfg`:

----
auths.instance.UserDirEnrollment.pluginName=UidPwdDirAuth
auths.instance.UserDirEnrollment.ldap.basedn=dc=example,dc=com
auths.instance.UserDirEnrollment.ldap.ldapauth.authtype=BasicAuth
auths.instance.UserDirEnrollment.ldap.ldapauth.bindDN=cn=Directory Manager
auths.instance.UserDirEnrollment.ldap.ldapauth.bindPWPrompt=internaldb
auths.instance.UserDirEnrollment.ldap.ldapconn.host=pki.example.com
auths.instance.UserDirEnrollment.ldap.ldapconn.port=389
auths.instance.UserDirEnrollment.ldap.ldapconn.secureConn=false
----

The `UidPwdDirAuth` plugin is already defined in the `CS.cfg`:

----
auths.impl.UidPwdDirAuth.class=com.netscape.cms.authentication.UidPwdDirAuthentication
----

Customize the profile (e.g. `/var/lib/pki/pki-tomcat/ca/profiles/ca/caDirUserCert.cfg`) as needed. To simplify testing the validity range can be changed to 30 days:

----
policyset.userCertSet.2.default.params.range=30
----

Restart PKI server:

----
$ systemctl restart pki-tomcatd@pki-tomcat.service
----

= Enrollment =

See link:Certificate-Enrollment-with-Directory-Authenticated-Profile[Certificate Enrollment with Directory Authenticated Profile].

= Renewal =

See link:Certificate-Renewal-with-Directory-Authenticated-Profile[Certificate Renewal with Directory-Authenticated Profile].

= See Also =

* link:Authentication-Managers[Authentication Managers]
* link:Certificate-Profiles[Certificate Profiles]
* link:https://github.com/dogtagpki/pki/blob/master/docs/user/tools/Using-PKI-CA-Certificate-CLI.adoc[PKI CA Certificate CLI]
* link:https://github.com/dogtagpki/pki/issues/2022[Ticket #2022: pki cli client-cert-request should support dir based auth]
