= Overview =

This page describes the process to configure OCSP responder to get the revocation information from an LDAP server.

To configure CA to publish the revocation information to an LDAP server, see:

* link:Publishing-CA-Certificate-to-LDAP-Server[Publishing CA Certificate to LDAP Server]
* link:Publishing-CRL-to-LDAP-Server[Publishing CRL to LDAP Server]

= Preparing LDAP Server =

Ensure the CRL publishing subtree can be accessed anonymously:

----
$ ldapmodify
    -H ldap://$HOSTNAME:389 \
    -x \
    -D "cn=Directory Manager" \
    -w Secret.123
dn: dc=crl,dc=pki,dc=example,dc=com
changetype: modify
add: aci
aci: (targetattr!="userPassword || aci")
 (version 3.0; acl "Enable anonymous access"; allow (read, search, compare) userdn="ldap:///anyone";)
----

Verify with the following command:

----
$ ldapsearch \
    -H ldap://$HOSTNAME:389 \
    -x \
    -b "dc=crl,dc=pki,dc=example,dc=com"
----

= Configuring Revocation Info Store =

The revocation info store configuration is stored in `/var/lib/pki/pki-tomcat/ocsp/conf/CS.cfg`.

To configure the LDAP store:

----
$ pki-server ocsp-config-set ocsp.store.ldapStore.numConns 1
$ pki-server ocsp-config-set ocsp.store.ldapStore.host0 localhost.localdomain
$ pki-server ocsp-config-set ocsp.store.ldapStore.port0 389
$ pki-server ocsp-config-set ocsp.store.ldapStore.baseDN0 "dc=crl,dc=pki,dc=example,dc=com"
$ pki-server ocsp-config-set ocsp.store.ldapStore.byName true
$ pki-server ocsp-config-set ocsp.store.ldapStore.caCertAttr "cACertificate;binary"
$ pki-server ocsp-config-set ocsp.store.ldapStore.crlAttr "certificateRevocationList;binary"
$ pki-server ocsp-config-set ocsp.store.ldapStore.includeNextUpdate false
$ pki-server ocsp-config-set ocsp.store.ldapStore.notFoundAsGood true
----

To enable the LDAP store:

----
$ pki-server ocsp-config-set ocsp.storeId ldapStore
----

By default the CRL cache will refresh every 24 hours. To simplify testing, the refresh can be configured to happen more frequently, e.g. every `60` seconds:

----
$ pki-server ocsp-config-set ocsp.store.ldapStore.refreshInSec0 60
----

Finally, restart the server.
