= Overview =

By default the CI will perform tests using latest Fedora version. Sometimes it's necessary to test against a different Fedora version. This can be done by creating a GitHub secret called `BASE64_OS` to store the base64-encoded value of the Fedora version. To reset the test OS simply remove the secret.

**Availability:** Since PKI 11.4

= Configuring Test OS =

For example, to test against Fedora Rawhide, execute the following command:

----
$ echo -n "rawhide" | base64
cmF3aGlkZQ==
----

Then create the secret:

* Go to *Settings* -> *Secrets*.
* Click *New repository secret*.
* Enter `BASE64_OS` as the secret name.
* Enter the base64-encoded value as the secret value.
* Click *Add secret*

= Before Testing =

It is a good idea to delete any caches that may exist in your repo before starting:

* Go to *Actions* -> Click *Caches* in the left menu.
* Delete caches as appropriate.

= Resetting Test OS =

To reset the test OS, remove the secret:

* Go to *Settings* -> *Secrets*.
* Click *Remove* next to `BASE64_OS`.
* Click *Yes, remove this secret*.
