= Overview =

This document describes how to configure directory-authenticated certificate profiles:

* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caDirUserCert.cfg[caDirUserCert]: Directory-Authenticated User Dual-Use Certificate Enrollment
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caECDirUserCert.cfg[caECDirUserCert]: Directory-Authenticated User ECC Certificate Enrollment
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caDirUserRenewal.cfg[caDirUserRenewal]: Directory-Authenticated User Certificate Self-Renew profile
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caDirPinUserCert.cfg[caDirPinUserCert]: Directory-Pin-Authenticated User Dual-Use Certificate Enrollment
* link:https://github.com/dogtagpki/pki/blob/master/base/ca/shared/profiles/ca/caECDirPinUserCert.cfg[caECDirPinUserCert]: Directory-Pin-Authenticated User Dual-Use ECC Certificate Enrollment

= Prerequisites =

Prepare a publicly accessible subtree in the DS that contains users.
Each user must be able to authenticate using a password.
For example:

----
$ ldapadd -H ldap://$HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: ou=people,dc=example,dc=com
objectclass: top
objectclass: organizationalUnit
ou: people
aci: (target = "ldap:///ou=people,dc=example,dc=com")
 (targetattr=objectClass||dc||ou||uid||cn||sn||givenName)
 (version 3.0; acl "Allow anyone to read and search basic attributes"; allow (search, read) userdn = "ldap:///anyone";)
aci: (target = "ldap:///ou=people,dc=example,dc=com")
 (targetattr=*)
 (version 3.0; acl "Allow anyone to read and search itself"; allow (search, read) userdn = "ldap:///self";)

dn: uid=testuser,ou=people,dc=example,dc=com
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
uid: testuser
cn: Test User
sn: User
userPassword: Secret.123
EOF
----

Verify the authentication using the following command:

----
$ ldapsearch \
    -H ldap://$HOSTNAME \
    -x \
    -D "uid=testuser,ou=People,dc=example,dc=com" \
    -w Secret.123 \
    -b "dc=example,dc=com" \
    "(objectClass=*)"
----

= Configuring caDirUserCert Profile =

The `caDirUserCert` profile is stored in `/var/lib/pki/pki-tomcat/ca/profiles/ca/caDirUserCert.cfg`.

By default the profile is disabled. To enable the profile update the following parameter:

----
enable=true
----

By default the certificate will be valid for 180 days. For testing the validity range can be shortened, e.g. to 5 minutes:

----
policyset.userCertSet.2.default.params.range=5
policyset.userCertSet.2.default.params.rangeUnit=minute
----

By default the profile is configured with `UserDirEnrollment` authentication manager:

----
auth.instance_id=UserDirEnrollment
----

Add the `UserDirEnrollment` authentication manager into `/var/lib/pki/pki-tomcat/ca/conf/CS.cfg`:

----
auths.instance.UserDirEnrollment.pluginName=UidPwdDirAuth
auths.instance.UserDirEnrollment.ldap.basedn=dc=example,dc=com
auths.instance.UserDirEnrollment.ldap.ldapauth.authtype=BasicAuth
auths.instance.UserDirEnrollment.ldap.ldapauth.bindDN=cn=Directory Manager
auths.instance.UserDirEnrollment.ldap.ldapauth.bindPWPrompt=internaldb
auths.instance.UserDirEnrollment.ldap.ldapconn.host=pki.example.com
auths.instance.UserDirEnrollment.ldap.ldapconn.port=389
auths.instance.UserDirEnrollment.ldap.ldapconn.secureConn=false
----

The `UidPwdDirAuth` authentication plugin is already defined in the `CS.cfg`:

----
auths.impl.UidPwdDirAuth.class=com.netscape.cms.authentication.UidPwdDirAuthentication
----

Finally, restart PKI server:

----
$ systemctl restart pki-tomcatd@pki-tomcat.service
----

= Enrollment =

See link:Certificate-Enrollment-with-Directory-Authenticated-Profile[Certificate Enrollment with Directory Authenticated Profile].

= Renewal =

See link:Certificate-Renewal-with-Directory-Authenticated-Profile[Certificate Renewal with Directory-Authenticated Profile].

= See Also =

* link:Configuring-Authentication-Managers[Configuring Authentication Managers]
* link:Certificate-Profiles[Certificate Profiles]
* link:https://github.com/dogtagpki/pki/blob/master/docs/user/tools/Using-PKI-CA-Certificate-CLI.adoc[PKI CA Certificate CLI]
* link:https://github.com/dogtagpki/pki/issues/2022[Ticket #2022: pki cli client-cert-request should support dir based auth]
