= Overview =

This page describes the process to configure SCEP responder in CA.

For older versions see:

* link:Configuring-SCEP-Responder-in-PKI-9[Configuring SCEP Responder in PKI 9]

= SCEP Profile =

The SCEP responder uses caRouterCert profile stored in `/var/lib/pki/pki-tomcat/ca/profiles/ca/caRouterCert.cfg`:

----
auth.instance_id=flatFileAuth
----

Disable `deferOnFailure` in `/var/lib/pki/pki-tomcat/ca/conf/CS.cfg`:

----
auths.instance.flatFileAuth.deferOnFailure=false
----

Edit `/var/lib/pki/pki-tomcat/ca/conf/flatfile.txt` to enter the client's IP address and password:

----
UID:<IP address>
PWD:<password>

UID:<IP address>
PWD:<password>

...
----

= SCEP Configuration =

The SCEP configuration is stored in `/var/lib/pki/pki-tomcat/ca/conf/CS.cfg`:

----
ca.scep.enable=false
ca.scep.hashAlgorithm=SHA256
ca.scep.allowedHashAlgorithms=SHA256,SHA512
ca.scep.encryptionAlgorithm=DES3
ca.scep.allowedEncryptionAlgorithms=DES3
ca.scep.nonceSizeLimit=16
----

To enable the SCEP responder:

----
ca.scep.enable=true
----

Then restart the server:

----
$ systemctl restart pki-tomcatd@pki-tomcat.service
----

The SCEP service can be accessed at http://pki.example.com:8080/ca/cgi-bin/pkiclient.exe.

= See Also =

* link:SCEP-Responder[SCEP Responder]
* link:Certificate-Enrollment-with-SCEP[Certificate Enrollment with SCEP]
