= Overview =

By default the CI will perform tests using latest Fedora version. Sometimes it's necessary to test against a different Fedora version.

Prior to PKI 11.5 the test OS can be configured by creating a GitHub secret called `BASE64_OS` to store the base64-encoded value of the Fedora version (e.g. `rawhide`). To reset the test OS simply remove the secret.

In PKI 11.5 or later the test OS can be configured by creating a GitHub variable called `BASE_IMAGE` to store the base image (e.g. `registry.fedoraproject.org/fedora:rawhide`) of the test containers. To reset the test OS simply remove the variable.

= Configuring Test OS =

For example, to test against Fedora Rawhide prior to PKI 11.5, base-64 encode the Fedora version with the following command:

----
$ echo "rawhide" | base64
cmF3aGlkZQo=
----

Then create the secret:

* Go to *Settings* -> *Secrets*.
* Click *New repository secret*.
* Enter `BASE64_OS` as the secret name.
* Enter the base64-encoded value as the secret value.
* Click *Add secret*

In PKI 11.5 or later create a variable:

* Go to *Settings* -> *Secrets and variables* -> *Actions* -> *Variables*.
* Click *New repository variable*.
* Enter `BASE_IMAGE` as the variable name.
* Enter `registry.fedoraproject.org/fedora:rawhide` as the variable value.
* Click *Add variable*.

= Before Testing =

It is a good idea to delete any caches that may exist in your repo before starting:

* Go to *Actions* -> Click *Caches* in the left menu.
* Delete caches as appropriate.

= Resetting Test OS =

To reset the test OS prior to PKI 11.5, remove the secret:

* Go to *Settings* -> *Secrets*.
* Click *Remove* next to `BASE64_OS`.
* Click *Yes, remove this secret*.

To reset the test OS in PKI 11.5 or later, remove the variable:

* Go to *Settings* -> *Secrets and variables* -> *Actions* -> *Variables*.
* Click *Remove* next to `BASE_IMAGE`.
* Click *Yes, remove this variable*.
