= Overview =

By default the CI will perform tests using latest Fedora version. Sometimes it's necessary to test against different Fedora versions. This can be done by creating a GitHub secret called `BASE64_MATRIX` to store the base64-encoded value of the test matrix. To reset the test matrix simply remove the secret.

NOTE: Since PKI 11.4 the `BASE64_MATRIX` parameter has been deprecated and will only support a single Fedora version. Use link:Configuring-Test-OS[BASE64_OS] instead.

= Configuring Test Matrix =

For example, to test against Fedora 34 and 35, prepare the test matrix as follows:

----
{
    "os": ["34", "35"]
}
----

Convert the value into a single line, escape the double quotes, then base64-encode the value:

----
$ echo "{\"os\": [\"34\", \"35\"]}" | base64
eyJvcyI6IFsiMzQiLCAiMzUiXX0K
----

Then create the secret:

* Go to *Settings* -> *Secrets*.
* Click *New repository secret*.
* Enter `BASE64_MATRIX` as the secret name.
* Enter the base64-encoded value as the secret value.
* Click *Add secret*

= Before Testing =

It is a good idea to delete any caches that may exist in your repo before starting:

* Go to *Actions* -> Click *Caches* in the left menu.
* Delete caches as appropriate.

= Resetting Test Matrix =

To reset the test matrix, remove the secret:

* Go to *Settings* -> *Secrets*.
* Click *Remove* next to `BASE64_MATRIX`.
* Click *Yes, remove this secret*.
