= Overview =

By default the CI will perform the tests using a DS from link:https://quay.io/repository/389ds/dirsrv[quay.io/389ds/dirsrv] container image.
Sometimes it's necessary to perform the tests using a different database (e.g. using a DS from RPM packages).

Prior to PKI 11.5 the test database can be configured by creating a GitHub secret called `BASE64_DATABASE` to store the base64-encoded value of the container image URL. To reset the test database simply remove the secret.

In PKI 11.5 or later the test database can be configured by creating a GitHub variable called `DB_IMAGE` to store the container image URL. To reset the test database simply remove the variable.

= Configuring Test Database =

For example, to configure the test database prior to PKI 11.5:

----
$ base64 << EOF
{
    "image": "edewata/dirsrv"
}
EOF
ewogICAgImltYWdlIjogImVkZXdhdGEvZGlyc3J2Igp9Cg==
----

Then create the secret:

* Go to *Settings* -> *Secrets*.
* Click *New repository secret*.
* Enter `BASE64_DATABASE` as the secret name.
* Enter the base64-encoded value as the secret value.
* Click *Add secret*

In PKI 11.5 or later create a variable:

* Go to *Settings* -> *Secrets and variables* -> *Actions* -> *Variables*.
* Click *New repository variable*.
* Enter `DB_IMAGE` as the variable name.
* Enter `edewata/dirsrv` as the variable value.
* Click *Add variable*.

= Resetting Test Database =

To reset the test database prior to PKI 11.5, remove the secret:

* Go to *Settings* -> *Secrets*.
* Click *Remove* next to `BASE64_DATABASE`.
* Click *Yes, remove this secret*.

To reset the test database in PKI 11.4 or later, remove the variable:

* Go to *Settings* -> *Secrets and variables* -> *Actions* -> *Variables*.
* Click *Remove* next to `DB_IMAGE`.
* Click *Yes, remove this variable*.
