= Contact Information =

* link:https://github.com/dogtagpki/pki/wiki/IRC[IRC]
* link:https://github.com/dogtagpki/pki/wiki/Mailing-Lists[Mailing Lists]

= What to Expect =

A word about any potential interactions between well meaning contributors and the Dogtag team. We will always do our best to respond to any input and questions as quickly as possible. Having said that, there are often times when team members are hard at work on the next release and may not respond instantaneously. This will be in no way a sign of lack of appreciation for said input. On our end we should attempt to at least acknowledge the input in a reasonable amount of time and express a promise to look into the issue as soon as possible. In return we would hope that the contributor can reciprocate with patience during the process. Also, if an IRC comment from a contributor goes unnoticed, an email to the mailing list will always be appreciated and will effectively allow members of the team to respond when they become free to do so. Gentle reminders are welcome if something has fallen through the cracks for a bit too long of course.

Speaking of the email list, it would be great to keep as much of the discussion as reasonable to the list, such that all interested members of the list can benefit from any solutions or issues presented with any given topic. If we keep the response to questions on the list, it will become apparent that community members will come to assist other community members with issues, which is a benefit to all.
