= Repositories =

|===
| Repository | Platforms

| link:https://copr.fedorainfracloud.org/coprs/g/pki/master[@pki/master]
| Fedora 33, Fedora 34, Fedora 35

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.11[@pki/10.11]
| Fedora 33, Fedora 34

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.10[@pki/10.10]
| Fedora 33, Fedora 34

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.5[@pki/10.5]
| EPEL 7 / CentOS 7
|===

= Creating a Repository =

Each PKI branch that is actively maintained should have a corresponding COPR repository. When a new branch is created from another branch, a new COPR repository can be forked from the COPR repository corresponding to the original branch.

For example, below is the process to create a new `@pki/10.12` repository for `v10.12` branch in PKI. The repository will be forked from an existing `@pki/10.11` repository.

First, open the link:https://copr.fedorainfracloud.org/coprs/g/pki/10.11[@pki/10.11] repository and click **Fork this project**. Change the **Fork owner** to `@pki` and **Fork name** to `10.12`, then click **Fork it**.

Next, open the **Packages** tab in `@pki/10.12` repository and change the **Committish** of `pki` package to `v10.12`. Change the **Committish** of other packages as well if necessary. Rebuild the packages to verify the changes.


= Automating COPR Builds =

In the source repository create a `.copr/Makefile` to generate an SRPM:

----
srpm:
	dnf install -y git
	./build.sh --with-timestamp --with-commit-id srpm
	if [[ "${outdir}" != "" ]]; then \
	    mv ${HOME}/build/pki/SRPMS/* ${outdir}; \
	fi
----

In the COPR project create a package as follows:

* Source Type: `Build from an SCM repository`
* SCM type: `git`
* Clone URL: `<repo URL>`
* Committish: `<branch>`
* Build SRPM with: `make_srpm`
* Auto-rebuild: `True`

To configure the webhook, go to **Settings** -> **Integrations** in the COPR project and follow the instruction.

= See Also =

* link:https://www.dogtagpki.org/wiki/COPR[COPR]
