= Overview =

|===
| Repository | Platforms | Webhook URL

| link:https://copr.fedorainfracloud.org/coprs/g/pki/master[@pki/master]
| Fedora 33, Fedora 34, Fedora 35, Rawhide
| link:https://copr.fedorainfracloud.org/webhooks/github/23325/1a8341cd-4949-4d58-913c-297f002f04df/[GitHub]

| link:https://copr.fedorainfracloud.org/coprs/g/pki/11.0[@pki/11.0]
| Fedora 33, Fedora 34, Fedora 35, Rawhide
| link:https://copr.fedorainfracloud.org/webhooks/github/49907/b3933596-cca1-4fba-8c79-5dc6ced2870c/[GitHub]

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.12[@pki/10.12]
| Fedora 33, Fedora 34
| link:https://copr.fedorainfracloud.org/webhooks/github/50109/54655732-f2a8-495d-9f7d-4d1249f3e2d3/[GitHub]

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.11[@pki/10.11]
| Fedora 33, Fedora 34
| link:https://copr.fedorainfracloud.org/webhooks/github/45095/cd5e17a5-b973-47f1-b666-0966d90f2b45/[GitHub]

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.10[@pki/10.10]
| Fedora 33, Fedora 34
| link:https://copr.fedorainfracloud.org/webhooks/github/34731/f31d8218-203a-48c2-ab2d-60caa9435141/[GitHub]

| link:https://copr.fedorainfracloud.org/coprs/g/pki/10.5[@pki/10.5]
| EPEL 7 / CentOS 7
| link:https://copr.fedorainfracloud.org/webhooks/github/16163/147c070b-bd94-4971-a15d-e20582a42a6c/[GitHub]
|===

= Creating a Repository =

Each PKI branch that is actively maintained should have a corresponding COPR repository. When a new PKI branch is created from another branch, a new COPR repository should be forked from the COPR repository corresponding to the original branch.

For example, below is the process to create a new `@pki/10.12` repository for `v10.12` branch in PKI. The repository will be forked from an existing `@pki/10.11` repository.

First, open the link:https://copr.fedorainfracloud.org/coprs/g/pki/10.11[@pki/10.11] repository and click **Fork this project**. Change the **Fork owner** to `@pki` and **Fork name** to `10.12`, then click **Fork it**.

Next, go to **Packages** in `@pki/10.12` repository and change the **Committish** of `pki` package to `v10.12`. Change the **Committish** of other packages as well if necessary. Rebuild the packages to verify the changes.

Finally, go to **Settings** -> **Integrations**, copy the Webhook URL for GitHub, append `?id=@pki/10.12` to the URL to make it easier to identify, then add the URL to each GitHub project.

= Automating COPR Builds =

In the source repository create a `.copr/Makefile` to generate an SRPM:

----
srpm:
	dnf install -y git
	./build.sh --with-timestamp --with-commit-id srpm
	if [[ "${outdir}" != "" ]]; then \
	    mv ${HOME}/build/pki/SRPMS/* ${outdir}; \
	fi
----

In the COPR project create a package as follows:

* Source Type: `Build from an SCM repository`
* SCM type: `git`
* Clone URL: `<repo URL>`
* Committish: `<branch>`
* Build SRPM with: `make_srpm`
* Auto-rebuild: `True`

To configure the webhook, go to **Settings** -> **Integrations** in the COPR project and follow the instruction.

= See Also =

* link:https://www.dogtagpki.org/wiki/COPR[COPR]
