= Overview =

NOTE: This page is still under construction.

This document describes the process to create a PKI systemd service with Podman using PKI 11.4 or later.

= Installing Podman =

----
$ dnf install -y podman
----

= Installing PKI server image =

----
$ podman pull quay.io/dogtagpki/pki-server
----

= Configuring SELinux =

----
$ setsebool -P container_manage_cgroup on
----

= Creating Systemd Service =

To create the systemd service, execute the following command:

----
$ ln -sf /usr/lib/systemd/system/pki-podman.service
    /etc/systemd/system/pki-podman.service
----

Then execute:

----
$ systemctl daemon-reload
----

= Starting Systemd Service =

To start the systemd service, execute the following command:

----
$ systemctl start pki-podman.service
----

It should start a `pki-server` container in Podman:

----
$ podman ps
CONTAINER ID  IMAGE                                ...     NAMES
8594b6b6e0c7  quay.io/dogtagpki/pki-server:latest  ...     pki-server
----

= Monitoring Systemd Service =

To view systemd journal:

----
$ journalctl -fu pki-podman.service
----

To view Podman logs:

----
$ podman logs -f pki-server
----

= See Also =

* link:Deploying-PKI-Server-Container[Deploying PKI Server Container]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/running_containers_as_systemd_services_with_podman[Running Containers as systemd Services with Podman]
* link:https://www.tutorialworks.com/podman-systemd/[How to Start a Container on Boot with Podman and Systemd]
* link:https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html[podman-generate-systemd - Generate systemd unit file(s) for a container or pod]
