= Overview =

NOTE: This page is still under construction.

This document describes the process to deploy PKI server container as a systemd service using PKI 11.5 or later.

= Installing Podman =

----
$ dnf install -y podman
----

= Installing PKI Server Image =

----
$ podman pull quay.io/dogtagpki/pki-server
----

= Creating Systemd Service =

To create the systemd service, execute the following command:

----
$ ln -sf /usr/lib/systemd/system/pki-server.service
    /etc/systemd/system/pki-server.service
----

Then execute:

----
$ systemctl daemon-reload
----

= Starting Systemd Service =

To start the systemd service, execute the following command:

----
$ systemctl start pki-server.service
----

It should start `pki-server` container:

----
$ podman ps
CONTAINER ID  IMAGE                                ...     NAMES
8594b6b6e0c7  quay.io/dogtagpki/pki-server:latest  ...     pki-server
----

= Monitoring Systemd Service =

To monitor the systemd service:

----
$ journalctl -fu pki-server.service
----

To monitor the container:

----
$ podman logs -f pki-server
----

= Stopping Systemd Service =

To stop the systemd service, execute the following command:

----
$ systemctl stop pki-server.service
----

It should stop `pki-server` container.

= Removing Systemd Service =

To remove the systemd service, execute the following command:

----
$ rm -f /etc/systemd/system/pki-server.service
----

Then execute:

----
$ systemctl daemon-reload
----

= See Also =

* link:Deploying-PKI-Server-Container[Deploying PKI Server Container]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/running_containers_as_systemd_services_with_podman[Running Containers as systemd Services with Podman]
* link:https://www.tutorialworks.com/podman-systemd/[How to Start a Container on Boot with Podman and Systemd]
* link:https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html[podman-generate-systemd - Generate systemd unit file(s) for a container or pod]
* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers[RHEL 8 - Building, running, and managing containers]
** link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#assembly_porting-containers-to-systemd-using-podman_building-running-and-managing-containers[Porting containers to systemd using Podman]
* link:https://github.com/containers/podman/issues/12778[Podman #12778 - support User= in systemd for running rootless services]
* link:https://access.redhat.com/discussions/5733161[How to Auto-starting rootless pods using systemd]
* link:https://www.redhat.com/sysadmin/rootless-containers-podman[Rootless containers using Podman]