= Overview =

NOTE: This page is still under construction.

This document describes the process to deploy TPS container on Podman with PKI 11.6 or later.

Current limitations:

* Replication is not yet supported (i.e. no scaling)
* HSM is not yet supported
* No security domain (i.e. other subsystems need to be set up manually)
* Long startup time (due to certs import and instance creation)

= Creating Network =

Create a network for the containers, for example:

----
$ podman network create example
----

Alternatively, use an existing network.

= Generating System Certificates =

To deploy the OCSP container, prepare the following files:

* `server.p12` which contains:
** `ca_signing` certificate (see link:Generating-CA-Signing-Certificate[Generating CA Signing Certificate])
** `tps_audit_signing` certificate and key (see link:Generating-Audit-Signing-Certificate[Generating Audit Signing Certificate])
** `subsystem` certificate and key (see link:Generating-Subsystem-Certificate[Generating Subsystem Certificate])
** `sslserver` certificate and key (see link:Generating-SSL-Server-Certificate[Generating SSL Server Certificate])
* `tps_audit_signing.csr` certificate request
* `subsystem.csr` certificate request
* `sslserver.csr` certificate request

Then store the files in a location that will be mapped to the `/certs` folder in the TPS container.

See also:

* link:Generating-System-Certificates[Generating System Certificates]
* link:PKI-PKCS12-CLI[PKI PKCS12 CLI]

= Preparing Configuration Files =

Create a folder (e.g. `conf`) to store Tomcat and TPS configuration files.
This folder will be mapped into the `/conf` folder in the TPS container.

= Preparing Logs Folder =

Create a folder (e.g. `logs`) to store Tomcat and TPS log files.
This folder will be mapped into the `/logs` folder in the TPS container.

= Preparing TPS Database =

* link:Setting-up-TPS-Database[Setting up TPS Database]
* link:Setting-up-TPS-Database-User[Setting up TPS Database User] (optional)
* link:Setting-up-TPS-Admin-User[Setting up TPS Admin User]

= Deploying TPS Container =

Run the TPS container with the following command:

----
$ podman run \
    --name tps \
    --hostname tps.example.com \
    --network example \
    --network-alias tps.example.com \
    -v $PWD/certs:/certs \
    -v $PWD/conf:/conf \
    -v $PWD/logs:/logs \
    -e PKI_DS_URL=ldap://ds.example.com:3389 \
    -e PKI_DS_PASSWORD=Secret.123 \
    -d \
    quay.io/dogtagpki/pki-tps:latest
----

Wait until the TPS service is running:

----
$ podman logs -f tps
----

= Removing TPS Container =

If the TPS container is no longer needed, it can be removed with the following command:

----
$ podman rm -f tps
----
