= Overview =

This page describes the process to prepare a DS instance for PKI server.

Normally the DS installation will automatically generate a self-signed signing certificate and a server certificate for SSL connection.
In this procedure the certificate generation and the SSL connection will be disabled by default,
but it can be enabled after installation if necessary.

For DS 1.3 or older, see link:https://github.com/dogtagpki/pki/wiki/DS-1.3-Installation[DS 1.3 Installation].

= Installing DS Packages =

To install DS packages:

----
$ dnf install -y 389-ds-base
----

= Creating DS Instance =

Generate a DS configuration file (e.g. `ds.inf`):

----
$ dscreate create-template ds.inf
----

Customize the DS configuration file as follows:

----
$ sed -i \
    -e "s/;instance_name = .*/instance_name = localhost/g" \
    -e "s/;root_password = .*/root_password = Secret.123/g" \
    -e "s/;suffix = .*/suffix = dc=example,dc=com/g" \
    -e "s/;self_sign_cert = .*/self_sign_cert = False/g" \
    ds.inf
----

where

* *instance_name* specifies the name of the DS instance. In this example it's set to `localhost`.
* *root_password* specifies the password for DS admin (i.e. `cn=Directory Manager`). In this example it's set to `Secret.123`.
* *suffix* specifies the namespace for the DS instance. In this example it's set to `dc=example,dc=com`.
* *self_sign_cert* specifies whether to create self-signed certificates for SSL connection. In this example it's set to `False`. The SSL connection can be enabled after installation in link:Enabling-SSL-Connection-in-DS[this document].

For more information see the parameter descriptions in the DS configuration file itself (i.e. `ds.inf`) and in link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[DS documentation].

To create the instance:

----
$ dscreate from-file ds.inf
----

= Creating PKI Subtree =

When the DS instance is created, it does not automatically create the root entry (e.g. `dc=example,dc=com`).

To create the root entry and PKI subtree:

----
$ ldapadd -h $HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: dc=example,dc=com
objectClass: domain
dc: example

dn: dc=pki,dc=example,dc=com
objectClass: domain
dc: pki
EOF
----

The subsystem subtrees (e.g. `dc=ca,dc=pki,dc=example,dc=com`) will be created when the corresponding subsystems (e.g. CA) are installed.

When all subsystems are created, the tree will look like the following:

----
dc=example,dc=com
+ dc=pki
  + dc=ca
  + dc=kra
  + dc=ocsp
  + dc=tks
  + dc=tps
  + dc=acme
----

= Enabling SSL Connection =

To enable SSL connection, see link:Enabling-SSL-Connection-in-DS[Enabling SSL Connection in DS].

= Removing DS Instance =

To remove DS instance:

----
$ dsctl localhost remove --do-it
----

= Log Files =

DS log files are available in `/var/log/dirsrv/slapd-localhost`:

* access
* audit
* errors

= See Also =

* link:https://www.dogtagpki.org/wiki/DS[DS]
* link:https://www.dogtagpki.org/wiki/DS_SSL[DS SSL]
* link:https://www.dogtagpki.org/wiki/PKI_LDAP[PKI LDAP]
* link:https://www.dogtagpki.org/wiki/Enabling_SSL_Connection_with_Internal_Database[Enabling SSL Connection with Internal Database]
* link:https://directory.fedoraproject.org[389 Directory Server]
* link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[dsctl, dsconf, and dsidm]
