= Overview =

This page describes the process to prepare a DS 1.4 instance or later for PKI server.

For older DS versions see:

* link:https://github.com/dogtagpki/pki/wiki/DS-1.3-Installation[DS 1.3 Installation]

= Installing DS Packages =

----
$ dnf install -y 389-ds-base
----

= Installing DS Instance =

Generate a DS configuration file (e.g. `ds.inf`):

----
$ dscreate create-template ds.inf
----

Customize the DS configuration file as follows:

----
$ sed -i \
    -e "s/;root_password = .*/root_password = Secret.123/g" \
    -e "s/;suffix = .*/suffix = dc=example,dc=com/g" \
    -e "s/;instance_name = .*/instance_name = localhost/g" \
    -e "s/;self_sign_cert = .*/self_sign_cert = False/g" \
    ds.inf
----

where

* *root_password*: password for `cn=Directory Manager`
* *suffix*: root suffix for the DS instance
* *instance_name*: the name of the DS instance
* *self_sign_cert*: flag for creating self-signed DS signing certificate

See the parameter descriptions in the DS configuration file itself (i.e. `ds.inf`) and link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[DS documentation] for further information.

To create the instance:

----
$ dscreate from-file ds.inf
----

= Creating PKI Subtree =

Once the DS instance is created, it's recommended to create a top-level PKI subtree (e.g. `dc=pki,dc=example,dc=com`)
such that all PKI subsystems can be stored under this subtree:

----
dc=example,dc=com
+ dc=pki
  + dc=ca
  + dc=kra
  + dc=ocsp
  + dc=tks
  + dc=tps
  + dc=acme
----

To create the root entry and PKI subtree in the DS instance:

----
$ ldapadd -h $HOSTNAME -x -D "cn=Directory Manager" -w Secret.123 << EOF
dn: dc=example,dc=com
objectClass: domain
dc: example

dn: dc=pki,dc=example,dc=com
objectClass: domain
dc: pki
EOF
----

The PKI subsystem subtrees (e.g. `dc=ca,dc=pki,dc=example,dc=com`) will be created when the subsystem is installed.

= Removing DS Instance =

To remove DS instance:

----
$ dsctl localhost remove --do-it
----

= Log Files =

DS log files are available in /var/log/dirsrv/slapd-localhost:

* access
* audit
* errors

= See Also =

* link:https://www.dogtagpki.org/wiki/DS[DS]
* link:https://www.dogtagpki.org/wiki/DS_SSL[DS SSL]
* link:https://www.dogtagpki.org/wiki/PKI_LDAP[PKI LDAP]
* link:https://www.dogtagpki.org/wiki/Enabling_SSL_Connection_with_Internal_Database[Enabling SSL Connection with Internal Database]
* link:https://directory.fedoraproject.org[389 Directory Server]
* link:https://directory.fedoraproject.org/docs/389ds/design/dsadm-dsconf.html[dsctl, dsconf, and dsidm]
