= Overview =

This document describes the process to configure an existing PKI instance to use SSL connection to DS 1.4 or later.

*Note:* SSL is enabled up by default in DS 1.4 or later using a self-signed certificate.

= Exporting DS CA Certificate =

To find the DS CA certificate nickname:

----
$ certutil -L -d /etc/dirsrv/slapd-<font color="red">localhost</font>

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

Self-Signed-CA                                               CT,, 
Server-Cert                                                  u,u,u
----

To export the DS CA certificate:

----
$ certutil -L -d /etc/dirsrv/slapd-localhost -n Self-Signed-CA -a > ds-ca.pem
----

= Importing DS CA into PKI =

To import the DS CA certificate:

----
$ certutil -A -d /etc/pki/pki-tomcat/alias -n "DS CA" -i ds-ca.pem -t "CT,C,C"
----

To verify the import:

----
$ certutil -L -d /etc/pki/pki-tomcat/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CTu,Cu,Cu
ca_ocsp_signing                                              u,u,u
subsystem                                                    u,u,u
ca_audit_signing                                             u,u,Pu
sslserver                                                    u,u,u
DS CA                                                        CT,C,C
----

Restart PKI server:

----
$ systemctl restart pki-tomcatd@$pki-tomcat.service
----

= Verification =

Verify in DS error log at `/var/log/dirsrv/slapd-localhost/errors` that the DS started succesfully with SSL:

----
INFO - Security Initialization - SSL info: Enabling default cipher set.
INFO - Security Initialization - SSL info: Configured NSS Ciphers
INFO - Security Initialization - SSL info:     TLS_AES_128_GCM_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_CHACHA20_POLY1305_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_AES_256_GCM_SHA384: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_AES_128_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_DSS_WITH_AES_128_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_AES_256_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_DSS_WITH_AES_256_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_RSA_WITH_AES_128_GCM_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_RSA_WITH_AES_128_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_RSA_WITH_AES_128_CBC_SHA256: enabled
INFO - Security Initialization - SSL info:     TLS_RSA_WITH_AES_256_CBC_SHA: enabled
INFO - Security Initialization - SSL info:     TLS_RSA_WITH_AES_256_CBC_SHA256: enabled
INFO - Security Initialization - slapd_ssl_init2 - Configured SSL version range: min: TLS1.0, max: TLS1.3
INFO - main - 389-Directory/1.3.7.8 B2017.324.1651 starting up
...
INFO - slapd_daemon - slapd started.  Listening on All Interfaces port 389 for LDAP requests
INFO - slapd_daemon - Listening on All Interfaces port 636 for LDAPS requests
----

Verify SSL connection with mozldap-tools and NSS database:

----
$ /usr/lib64/mozldap/ldapsearch \
   -Z -h $HOSTNAME -p 636 \
   -D "cn=Directory Manager" -w Secret.123 \
   -P /etc/dirsrv/slapd-localhost \
   -b "dc=example,dc=com" -s base "(objectClass=*)"
----

or with openldap-clients and DS certificate:

----
$ LDAPTLS_CACERT=ca.crt \
    ldapsearch -H ldaps://$HOSTNAME:636 \
    -x -D "cn=Directory Manager" -w Secret.123 \
    -b "dc=example,dc=com" -s base "(objectClass=*)"
----

or with openldap-clients and NSS databsae:

----
$ LDAPTLS_CACERTDIR=/etc/dirsrv/slapd-localhost \
    ldapsearch -H ldaps://$HOSTNAME:636 \
    -x -D "cn=Directory Manager" -w Secret.123 \
    -b "dc=example,dc=com" -s base "(objectClass=*)"
----

= Enabling Secure DS Connection in PKI =

Configure PKI server to use SSL by editing `/var/lib/pki/pki-tomcat/<subsystem>/conf/CS.cfg`:

----
internaldb.ldapconn.host=server.example.com
internaldb.ldapconn.port=636
internaldb.ldapconn.secureConn=true
----

Restart PKI server:

----
$ systemctl restart pki-tomcatd@pki-tomcat.service
----

Verify in DS access log at `/var/log/dirsrv/slapd-localhost/access` that PKI server is connecting using SSL:

----
[29/Jun/2016:23:20:40 +0200] conn=36 fd=64 slot=64 SSL connection from server.example.com to server.example.com
[29/Jun/2016:23:20:40 +0200] conn=36 TLS1.2 128-bit AES
----

Verify PKI server can communicate with the DS with the following command:

----
$ pki ca-cert-find
----

= See Also =

* link:https://www.dogtagpki.org/wiki/PKI_Server_Configuration[PKI Server Configuration]
* link:https://www.dogtagpki.org/wiki/PKI_LDAP_Connection[PKI LDAP Connection]
* link:https://www.dogtagpki.org/wiki/SSL[SSL]
* link:https://www.dogtagpki.org/wiki/Enabling_SSL_Connection_with_Internal_Database[Enabling SSL Connection with Internal Database]
