= Prerequisites =

* Become a Fedora packager by submitting a request to link:https://pagure.io/packager-sponsors/issues?status=all&author=edewata&close_status=[packager-sponsors].

* Install `fedpkg`:

----
$ dnf install fedpkg
----

= Packages =

See link:Fedora-Packages[Fedora Packages].

= Module (Unused) =

The dist-git project for PKI module is located at:

* https://src.fedoraproject.org/modules/pki

See also link:https://www.dogtagpki.org/wiki/Fedora_Modules[Fedora Modules].

= Authentication =

== SSH ==

Make sure the SSH key is set up properly in link:https://accounts.fedoraproject.org[Fedora Account System]. Verify by connecting to `fedorapeople.org`:

----
$ ssh -v <username>@fedorapeople.org
----

Log out from `fedorapeople.org` and continue on the local machine.

== Kerberos ==

Obtain a link:https://www.dogtagpki.org/wiki/Kerberos[Kerberos] ticket for FEDORAPROJECT.ORG:

----
$ kinit <username>@FEDORAPROJECT.ORG
Password for <username>@FEDORAPROJECT.ORG: ********
----

Verify with the following command:

----
$ klist
Ticket cache: KEYRING:persistent:13079:13079
Default principal: <username>@FEDORAPROJECT.ORG

Valid starting       Expires              Service principal
03/15/2018 21:37:11  03/16/2018 21:36:57  krbtgt/FEDORAPROJECT.ORG@FEDORAPROJECT.ORG
	renew until 03/22/2018 21:36:57
----

*Note:* If there's no ticket issued, edit `/etc/krb5.conf.d/kcm_default_ccache`, and comment out the following lines:

----
[libdefaults]
    default_ccache_name = KCM:
----

See also link:https://fedoraproject.org/wiki/Infrastructure/Kerberos[Infrastructure/Kerberos].

= Cloning a Project =

To clone a project into a local repository:

----
$ fedpkg clone <project>
----

If there's a problem, try running it in verbose mode:

----
$ fedpkg -v clone <project>
----

If the Fedora username is different from the local username, specify it using `--user`:

----
$ fedpkg --user <username> clone <project>
----

= Forking a Project =

To fork a project, visit the main Fedora project page (e.g. link:https://src.fedoraproject.org/rpms/dogtag-pki[dogtag-pki]) and click the *Fork* button at the top of the page.
The forked project should appear under `https://src.fedoraproject.org/fork/<username>/rpms/<project>/`.

= Adding Forked Project =

To add the forked package into the local repository, execute:

----
$ git remote add <username> https://src.fedoraproject.org/forks/<username>/rpms/<project>.git
$ git fetch <username>
----

= Creating a Pull Request =

First, commit the changes into a temporary branch, and push the branch into the forked project:

----
$ git checkout -b <branch>
$ git commit -m "..."
$ git push <username> <branch>
----

Then open the forked project page, go to the *Commits* page of the branch,
and click *Create pull request*.

After the request is merged, go back to the original branch and pull the changes:

----
$ git checkout <original branch>
$ git pull
----

= Creating a Scratch Build =

To create a scratch build:

----
$ fedpkg scratch-build
----

The scratch build be created in https://koji.fedoraproject.org.

= Building with Side Tag =

A side tag can be used to update multiple packages at the same time (i.e. avoid partial update).

To list existing side tags:

----
$ fedpkg list-side-tags
----

To request a new side tag:

----
$ fedpkg request-side-tag
----

To build a package with the side tag:

----
$ fedpkg build --target <side tag>
----

Wait for the new package to be available before building the next package:

----
$ koji wait-repo --build <package NVR> <side tag>
----

Once all packages are built, create an update in link:https://bodhi.fedoraproject.org[Bodhi] using the side tag.

See also link:https://fedoraproject.org/wiki/User:Nphilipp/Package_update_HOWTO#Multiple_Packages[Package update HOWTO - Multiple Packages].

= Mailing List =

* link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4EHBACT4I263R4QF75HB3DUJWWANGHAS/#H46IV2EFBZCSOVRSY7POHTGBVD2U32NG[The Death of Java (packages)]
* link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/EIU7CNABRKL5EFZNCFIWQIK2AHIEKWBB[hamcrest update to 2.2 in Fedora rawhide]
* link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MJATR5AVNIP5R5BKURZOPPEEA6GMXKAK[
Tomcat Package Changes in Rawhide]
* link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/A6TLJQZ2Q5HACYXT2YJ7QPXCBD3UFCDU[The Javapocalypse is Monday]
* link:https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/UUYUZUMROYRWYR2ULVVGBOQR3ILO5C5N/[Fedora 💔 Java: The Death of Two SIGs]

= See Also =

* link:https://www.dogtagpki.org/wiki/Fedora[Fedora]
* link:https://www.dogtagpki.org/wiki/Fedora_Packages[Fedora Packages]
* link:https://fedoraproject.org/wiki/Infrastructure/Factory2/Focus/ArbitraryBranching[Infrastructure/Factory2/Focus/ArbitraryBranching]
* link:https://www.dogtagpki.org/wiki/PKI_Fedora_Development[PKI Fedora Development]
* link:https://www.dogtagpki.org/wiki/Procedure_used_to_Release_Dogtag_10.2.1-1_on_Fedora_22[Procedure used to Release Dogtag 10.2.1-1 on Fedora 22]
* link:https://www.dogtagpki.org/wiki/Fedora_Koji_Process[Fedora Koji Process]
* link:https://packager-dashboard.fedoraproject.org[Fedora Packager Dashboard]
* link:Rebasing-a-Package-on-Fedora[Rebasing a Package on Fedora]
