= Overview =

This service can be used to display the latest CRL in CA.

= Request =

* *Operation:* `GET /ca/ee/ca/getCRL`
* *Authentication:* None
* *Parameters:*
** `op`: Operation
*** `displayCRL`
*** `getCRL`
*** `getDeltaCRL`
*** `importCRL`
*** `importDeltaCRL`
*** `checkCRL`
*** `checkCRLcache`
** `crlIssuingPoint`: CRL issuing point

= Response =

== Operation: getCRL ==

----
$ curl -s "http://localhost:8080/ca/ee/ca/getCRL?op=getCRL&crlIssuingPoint=MasterCRL" | openssl crl -inform DER -text
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = EXAMPLE, OU = pki-tomcat, CN = CA Signing Certificate
        Last Update: Oct 16 14:00:00 2023 GMT
        Next Update: Oct 16 18:00:00 2023 GMT
        CRL extensions:
            X509v3 Authority Key Identifier: 
                6E:9A:05:62:E9:98:23:E4:09:8C:91:9D:8A:83:2B:A7:6B:78:50:CC
            X509v3 CRL Number: 
                16
No Revoked Certificates.
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        c3:21:b2:34:6c:bf:35:39:eb:a6:41:1f:42:5d:86:5d:0d:ef:
        08:14:de:e4:b2:95:74:bc:50:53:bd:91:62:45:b7:c7:7b:eb:
        10:22:eb:a2:e9:44:32:17:d5:08:7c:fa:3e:72:69:c7:a6:03:
        4c:45:cf:9f:64:0f:57:ad:62:1d:1f:72:d7:5b:7b:1d:80:da:
        09:f7:fd:50:a4:af:20:37:53:00:ca:55:6c:07:af:8e:09:39:
        8e:eb:51:1e:33:62:3c:5e:c6:f1:3c:6f:aa:df:93:4a:ae:7e:
        8c:17:ac:b5:d8:a6:f0:fc:e0:75:67:31:aa:02:01:d0:b5:6d:
        68:f0:ac:b8:a4:b0:d5:e8:0c:d5:6b:16:b2:6d:9f:d4:f4:13:
        af:b8:3b:45:f9:04:78:50:07:d2:f2:b5:f1:f1:49:85:cf:c7:
        4f:2d:37:f0:8c:4c:ff:20:5d:24:ae:57:cc:9b:a3:80:1d:3e:
        5c:86:d5:13:7e:34:e7:48:93:42:42:9f:04:bc:0b:4c:0b:9b:
        b1:79:62:61:9e:95:60:85:07:78:17:19:b3:80:b1:3b:02:12:
        1a:f9:43:ac:06:6b:25:91:ef:53:13:1a:7d:2e:74:b9:55:e8:
        39:63:9d:46:59:1a:db:34:b0:e9:97:b9:8b:1b:b1:ea:ca:9e:
        05:57:26:6d:f8:41:fc:01:98:a6:56:0a:a1:63:9e:04:fa:a9:
        71:a4:b7:85:e4:63:92:2d:f3:82:c7:38:e4:3c:69:15:d0:06:
        32:58:2c:93:39:e9:77:f0:71:d8:f5:2e:90:89:c6:bd:33:9c:
        d8:a5:b1:9d:c8:fd:30:92:e5:f7:fa:10:69:06:06:5d:6f:aa:
        10:96:e5:d5:35:b5:84:94:c1:34:59:73:e6:4f:aa:94:bf:94:
        cb:fc:5b:dd:83:7f:5d:8e:7a:ac:ef:80:e8:17:82:0b:ac:80:
        6f:b5:31:67:f5:04:1f:26:8a:e8:96:c4:2f:e3:c0:01:d2:d2:
        d7:a1:73:8e:51:0d
-----BEGIN X509 CRL-----
MIICQjCBqwIBATANBgkqhkiG9w0BAQsFADBIMRAwDgYDVQQKDAdFWEFNUExFMRMw
EQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQDDBZDQSBTaWduaW5nIENlcnRpZmlj
YXRlFw0yMzEwMTYxNDAwMDBaFw0yMzEwMTYxODAwMDBaoC8wLTAfBgNVHSMEGDAW
gBRumgVi6Zgj5AmMkZ2Kgyuna3hQzDAKBgNVHRQEAwIBEDANBgkqhkiG9w0BAQsF
AAOCAYEAwyGyNGy/NTnrpkEfQl2GXQ3vCBTe5LKVdLxQU72RYkW3x3vrECLroulE
MhfVCHz6PnJpx6YDTEXPn2QPV61iHR9y11t7HYDaCff9UKSvIDdTAMpVbAevjgk5
jutRHjNiPF7G8Txvqt+TSq5+jBestdim8PzgdWcxqgIB0LVtaPCsuKSw1egM1WsW
sm2f1PQTr7g7RfkEeFAH0vK18fFJhc/HTy038IxM/yBdJK5XzJujgB0+XIbVE340
50iTQkKfBLwLTAubsXliYZ6VYIUHeBcZs4CxOwISGvlDrAZrJZHvUxMafS50uVXo
OWOdRlka2zSw6Ze5ixux6sqeBVcmbfhB/AGYplYKoWOeBPqpcaS3heRjki3zgsc4
5DxpFdAGMlgskznpd/Bx2PUukInGvTOc2KWxncj9MJLl9/oQaQYGXW+qEJbl1TW1
hJTBNFlz5k+qlL+Uy/xb3YN/XY56rO+A6BeCC6yAb7UxZ/UEHyaK6JbEL+PAAdLS
16FzjlEN
-----END X509 CRL-----
----
