= Overview =

This service can be used to check the status of a PKI subsystem.

= Request =

* *Operation:* `GET /<subsystem>/admin/<subsystem>/getStatus`
* *Authentication:* None

The `<subsystem>` is the subsystem type in lower case (e.g. `ca`, `kra`).

= Response =

* *State:* `0` means the server is being installed, `1` means the server is ready.
* *Type:* The subsystem type (e.g. `CA`, `KRA`).
* *Status:* `starting` or `running`.
* *Version:* PKI package version (e.g. `10.10.5-5.fc33`).
* *ProductVersion:* Product name and version (which may not necessarily be the same as PKI package version). If the server theme package (e.g. `dogtag-pki-server-theme`) is not installed, the product name and version will not be returned.

== JSON Response ==

Starting from PKI 11 this service returns a response in JSON format, for example:

----
$ curl -s http://localhost.localdomain:8080/ca/admin/ca/getStatus | python -m json.tool
{
    "Response": {
        "State": "1",
        "Type": "CA",
        "Status": "running",
        "Version": "11.1.0-0.1.alpha2.20220127004241UTC.2ccd9cc8.fc35",
        "ProductVersion": "Dogtag Certificate System"
    }
}
----

== XML Response ==

Prior to PKI 11 this service returns a response in XML format, for example:

----
$ curl -s http://localhost.localdomain:8080/ca/admin/ca/getStatus | xmllint --format -
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<XMLResponse>
  <State>1</State>
  <Type>CA</Type>
  <Status>running</Status>
  <Version>10.10.5-5.fc33</Version>
  <ProductVersion>Dogtag Certificate System</ProductVersion>
</XMLResponse>
----
