= Overview =

This document describes the process to install an ACME responder on a PKI server that already has a CA subsystem using `pkispawn` command.

= Prerequisites =

This document assumes that the following DS service is available to use as ACME database and ACME realm:

* URL: `ldap://ds.example.com:3389`
* Base DN: `dc=acme,dc=pki,dc=example,dc=com`
* Bind DN: `cn=Directory Manager`
* Bind password: `Secret.123`

It also assumes that the following CA service is available to use as ACME issuer:

* URL: `https://pki.example.com:8443`
* Username: `caadmin`
* Password: `Secret.123`

= Setting Up ACME Database =

To import the DS schema for ACME database:

----
$ ldapmodify \
    -H ldap://ds.example.com:3389 \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -f /usr/share/pki/acme/database/ds/schema.ldif
----

To create the DS indexes for ACME database:

----
$ ldapadd \
    -H ldap://ds.example.com:3389 \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -f /usr/share/pki/acme/database/ds/index.ldif
----

To create the DS subtrees for ACME database:

----
$ ldapadd \
    -H ldap://ds.example.com:3389 \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -f /usr/share/pki/acme/database/ds/create.ldif
----

= Setting Up ACME Realm =

To create the DS subtrees for ACME realm:

----
$ ldapadd \
    -H ldap://ds.example.com:3389 \
    -D "cn=Directory Manager" \
    -w Secret.123 \
    -f /usr/share/pki/acme/realm/ds/create.ldif
----

= Installing ACME Responder =

----
$ pkispawn \
    -f /usr/share/pki/server/examples/installation/acme.cfg \
    -s ACME \
    -D acme_database_url=ldap://ds.example.com:3389 \
    -D acme_issuer_url=https://pki.example.com:8443 \
    -D acme_realm_url=ldap://ds.example.com:3389 \
    -v
----

= Verifying ACME Responder =

To verify that the ACME responder is running, execute the following command:

----
$ curl -s -k https://$HOSTNAME:8443/acme/directory | python -m json.tool
{
    "meta": {
        "caaIdentities": [
            "example.com"
        ],
        "externalAccountRequired": false,
        "termsOfService": "https://www.example.com/acme/tos.pdf",
        "website": "https://www.example.com"
    },
    "newAccount": "https://<hostname>:8443/acme/new-account",
    "newNonce": "https://<hostname>:8443/acme/new-nonce",
    "newOrder": "https://<hostname>:8443/acme/new-order",
    "revokeCert": "https://<hostname>:8443/acme/revoke-cert"
}
----

= See Also =

* link:https://github.com/dogtagpki/pki/blob/master/base/acme/database/ds/schema.ldif[/usr/share/pki/acme/database/ds/schema.ldif]
* link:https://github.com/dogtagpki/pki/blob/master/base/acme/database/ds/index.ldif[/usr/share/pki/acme/database/ds/index.ldif]
* link:https://github.com/dogtagpki/pki/blob/master/base/acme/database/ds/indextask.ldif[/usr/share/pki/acme/database/ds/indextask.ldif]
* link:https://github.com/dogtagpki/pki/blob/master/base/acme/database/ds/create.ldif[/usr/share/pki/acme/database/ds/create.ldif]
* link:https://github.com/dogtagpki/pki/blob/master/base/acme/realm/ds/create.ldif[/usr/share/pki/acme/realm/ds/create.ldif]
* link:https://github.com/dogtagpki/pki/blob/master/base/server/examples/installation/acme.cfg[/usr/share/pki/server/examples/installation/acme.cfg]
* link:https://github.com/dogtagpki/pki/blob/master/.github/workflows/acme-basic-test.yml[Basic ACME Test]
