= Overview =

This page describes the process to install a KRA subsystem in PKI 11.6
with existing keys, CSRs, and certificates stored in a PKCS #12 file
which might be exported from an existing KRA.

= Preparing Keys, CSRs, and Certificates =

Export the CA signing certificate with the following command:

----
$ pki-server cert-export ca_signing --cert-file ca_signing.crt
----

New KRA keys, CSRs, and certificates can be created as follows:

* link:Generating-KRA-Storage-Certificate[Generating KRA Storage Certificate]
* link:Generating-KRA-Transport-Certificate[Generating KRA Transport Certificate]
* link:Generating-Audit-Signing-Certificate[Generating Audit Signing Certificate]
* link:Generating-Subsystem-Certificate[Generating Subsystem Certificate]
* link:Generating-SSL-Server-Certificate[Generating SSL Server Certificate]
* link:Generating-Admin-Certificate[Generating Admin Certificate]

Then store the keys and certificates into a PKCS #12 file.

Alternatively, the keys and certificates can be exported from an existing KRA into a PKCS #12 file with the following command:

----
$ pki \
    -d /etc/pki/pki-tomcat/alias \
    -f /etc/pki/pki-tomcat/password.conf \
    pkcs12-export \
    --pkcs12 kra-certs.p12 \
    --password Secret.123 \
    kra_storage \
    kra_transport \
    kra_audit_signing \
    subsystem \
    sslserver
----

If the new KRA is being created on a machine with a different hostname, the subsystem and the SSL server certificates should excluded from above command, or removed from the PKCS #12 file with the following commands:

----
$ pki pkcs12-cert-del --pkcs12-file kra-certs.p12 --pkcs12-password Secret.123 sslserver
$ pki pkcs12-cert-del --pkcs12-file kra-certs.p12 --pkcs12-password Secret.123 subsystem
----

If the existing KRA is using PKI 11.5 later the CSRs can be obtained from the `/etc/pki/pki-tomcat/certs` folder.
Otherwise, the CSRs can be exported with the following commands:

----
$ echo "-----BEGIN CERTIFICATE REQUEST-----" > kra_storage.csr
$ sed -n "/^kra.storage.certreq=/ s/^[^=]*=// p" < /etc/pki/pki-tomcat/kra/CS.cfg >> kra_storage.csr
$ echo "-----END CERTIFICATE REQUEST-----" >> kra_storage.csr

$ echo "-----BEGIN CERTIFICATE REQUEST-----" > kra_transport.csr
$ sed -n "/^kra.transport.certreq=/ s/^[^=]*=// p" < /etc/pki/pki-tomcat/kra/CS.cfg >> kra_transport.csr
$ echo "-----END CERTIFICATE REQUEST-----" >> kra_transport.csr

$ echo "-----BEGIN CERTIFICATE REQUEST-----" > kra_audit_signing.csr
$ sed -n "/^kra.audit_signing.certreq=/ s/^[^=]*=// p" < /etc/pki/pki-tomcat/kra/CS.cfg >> kra_audit_signing.csr
$ echo "-----END CERTIFICATE REQUEST-----" >> kra_audit_signing.csr

$ echo "-----BEGIN CERTIFICATE REQUEST-----" > subsystem.csr
$ sed -n "/^kra.subsystem.certreq=/ s/^[^=]*=// p" < /etc/pki/pki-tomcat/kra/CS.cfg >> subsystem.csr
$ echo "-----END CERTIFICATE REQUEST-----" >> subsystem.csr

$ echo "-----BEGIN CERTIFICATE REQUEST-----" > sslserver.csr
$ sed -n "/^kra.sslserver.certreq=/ s/^[^=]*=// p" < /etc/pki/pki-tomcat/kra/CS.cfg >> sslserver.csr
$ echo "-----END CERTIFICATE REQUEST-----" >> sslserver.csr
----

= Installing KRA Subsystem =

Prepare a file that contains the deployment configuration.
A sample deployment configuration is available at link:../blob/master/base/server/examples/installation/kra.cfg[/usr/share/pki/server/examples/installation/kra.cfg].

Specify the CA signing certificate with the following parameter:

----
pki_cert_chain_path=ca_signing.crt
----

Specify the existing keys and certificates in the PKCS #12 file with the following parameters:

----
pki_server_pkcs12_path=kra-certs.p12
pki_server_pkcs12_password=Secret.123
----

Specify the existing CSRs with the following parameters:

----
pki_storage_csr_path=kra_storage.csr
pki_transport_csr_path=kra_transport.csr
pki_audit_signing_csr_path=kra_audit_signing.csr
pki_subsystem_csr_path=subsystem.csr
pki_sslserver_csr_path=sslserver.csr
----

Specify the existing admin certificate and CSR with the following parameters:

----
pki_admin_cert_path=kra_admin.crt
pki_admin_csr_path=kra_admin.csr
----

Finally, execute the following command:

----
$ pkispawn -f kra.cfg -s KRA
----

It will install KRA subsystem in a Tomcat instance (default is `pki-tomcat`) and create the following NSS databases:

* server NSS database: `/etc/pki/pki-tomcat/alias`
* admin NSS database: `~/.dogtag/pki-tomcat/kra/alias`

= Verifying System Certificates =

Verify that the server NSS database contains the following certificates:

----
$ certutil -L -d /etc/pki/pki-tomcat/alias

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

ca_signing                                                   CT,C,C
kra_transport                                                u,u,u
kra_storage                                                  u,u,u
subsystem                                                    u,u,u
kra_audit_signing                                            u,u,Pu
sslserver                                                    u,u,u
----

= Verifying Admin Certificate =

Prepare a client NSS database (e.g. `~/.dogtag/nssdb`):

----
$ pki client-init
----

Import the CA signing certificate:

----
$ pki client-cert-import ca_signing --ca-cert ca_signing.crt
----

Import admin key and certificate:

----
$ pki pkcs12-import \
    --pkcs12 ~/.dogtag/pki-tomcat/ca_admin_cert.p12 \
    --pkcs12-password Secret.123
----

Verify that the admin certificate can be used to access the KRA subsystem by executing the following command:

----
$ pki -n caadmin kra-user-show kraadmin
---------------
User "kraadmin"
---------------
  User ID: kraadmin
  Full name: kraadmin
  Email: kraadmin@example.com
  Type: adminType
  State: 1
----
