= Overview =

This document describes the process to install an ACME responder on a PKI server that already has a CA subsystem using `pki-server` command.

= Prerequisites =

This document assumes that the following DS service is available to use as ACME database and ACME realm:

* URL: `ldap://ds.example.com:3389`
* Base DN: `dc=acme,dc=pki,dc=example,dc=com`
* Bind DN: `cn=Directory Manager`
* Bind password: `Secret.123`

It also assumes that the following CA service is available to use as ACME issuer:

* URL: `https://pki.example.com:8443`
* Username: `caadmin`
* Password: `Secret.123`

= Creating ACME Responder =

To create ACME responder in a PKI server instance, execute the following command:

----
$ pki-server acme-create
----

The command will create the initial configuration files in `/var/lib/pki/pki-tomcat/conf/acme` folder.

= Setting Up ACME Metadata =

----
$ pki-server acme-metadata-mod
The current value is displayed in the square brackets.
To keep the current value, simply press Enter.
To change the current value, enter the new value.
To remove the current value, enter a blank space.

Enter the location of the terms of service.
  Terms of Service [https://www.example.com/acme/tos.pdf]:

Enter the location of the website.
  Website [https://www.example.com]:

Enter the CAA identities.
  CAA Identities [example.com]:

Enter true/false whether an external account is required.
  External Account Required [false]:
----

See also link:Configuring-ACME-Metadata[Configuring ACME Metadata].

= Configuring ACME Responder =

To configure the ACME responder, see the following documents:


* link:Configuring-ACME-Database[Configuring ACME Database]
* link:Configuring-ACME-Issuer[Configuring ACME Issuer]
* link:Configuring-ACME-Realm[Configuring ACME Realm]

= Deploying ACME Responder =

Once everything is ready, deploy the ACME responder with the following command:

----
$ pki-server acme-deploy
----

The command will create a deployment descriptor at `/var/lib/pki/pki-tomcat/conf/Catalina/localhost/acme.xml`.

The server will start the ACME responder automatically in a few seconds.
It is not necessary to restart PKI server.

= Verifying ACME Responder =

To verify that the ACME responder is running, execute the following command:

----
$ curl -s -k https://$HOSTNAME:8443/acme/directory | python -m json.tool
{
    "meta": {
        "caaIdentities": [
            "example.com"
        ],
        "externalAccountRequired": false,
        "termsOfService": "https://www.example.com/acme/tos.pdf",
        "website": "https://www.example.com"
    },
    "newAccount": "https://<hostname>:8443/acme/new-account",
    "newNonce": "https://<hostname>:8443/acme/new-nonce",
    "newOrder": "https://<hostname>:8443/acme/new-order",
    "revokeCert": "https://<hostname>:8443/acme/revoke-cert"
}
----

= Undeploying ACME Responder =

To undeploy the ACME responder, execute the following command:

----
$ pki-server acme-undeploy
----

The command will remove the deployment descriptor at `/var/lib/pki/pki-tomcat/conf/Catalina/localhost/acme.xml`.

The server will stop the ACME responder automatically in a few seconds.
It is not necessary to restart PKI server.

To restart the ACME responder, execute `pki-server acme-deploy` again.

= Removing ACME Responder =

To remove the ACME responder completely from the server, execute the following command:

----
$ pki-server acme-remove
----

= See Also =

* link:https://github.com/dogtagpki/pki/blob/master/docs/installation/ca/Installing_CA.md[Installing CA]
* link:https://github.com/dogtagpki/pki/blob/master/docs/admin/acme/Managing_PKI_ACME_Responder.md[Managing PKI ACME Responder]
* link:https://github.com/dogtagpki/pki/blob/master/docs/user/acme/Using_PKI_ACME_Responder.md[Using PKI ACME Responder]
* link:https://github.com/dogtagpki/pki/blob/master/docs/manuals/man8/pki-server-acme.8.md[pki-server-acme(8)]
