= Overview =

This page describes the process to install a CA subsystem with link:Random-Certificate-Serial-Numbers-v3[Random Certificate Serial Numbers v3].

= Installation Procedure =

To install CA with random serial numbers v3, follow the normal CA installation procedure, then specify the parameters below.

To use random certificate serial numbers, add the following parameters in the `[CA]` section:

----
pki_cert_id_generator=random
pki_cert_id_length=159
----

The certificate ID length (in bits) can be specified in the `pki_cert_id_length` parameter. The default is `160` bits, but currently NSS/JSS is only able to handle up to `159` bits.

To use random certificate request IDs, add the following parameters in the `[CA]` section:

----
pki_request_id_generator=random
----

The certificate request ID length (in bits) can be specified in the `pki_request_id_length` parameter. The default is `160` bits.

= Verification =

After installation the certificates will have random serial numbers, for example:

----
$ pki ca-cert-find
---------------
6 entries found
---------------
  Serial Number: 0x475d38900180aeafc3c6ec2e723ee697a8d1cad
  Subject DN: CN=CA Audit Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  ...

  Serial Number: 0xf9f46142fc730b83cd1b154cb051eb1a73b45ff
  Subject DN: CN=Subsystem Certificate,OU=pki-tomcat,O=EXAMPLE
  ...

  Serial Number: 0x114fc86ecda95707aebf89ee8f9fdaf243a357e8
  Subject DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  ...

  Serial Number: 0x5a4f00ea59a16f2d6411db76b3c7602326e5dd5c
  Subject DN: CN=pki.example.com,OU=pki-tomcat,O=EXAMPLE
  ...

  Serial Number: 0x5f688c6644b1763830bae4fa61315961d4c04e2f
  Subject DN: CN=CA OCSP Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  ...

  Serial Number: 0x617688896166652ae4e43da7a29b09067ba46b85
  Subject DN: CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE
  ...
----------------------------
Number of entries returned 6
----------------------------
----

The certificate requests will also use random IDs, for example:

----
$ pki -n caadmin ca-cert-request-find
-----------------
6 entries matched
-----------------
  Request ID: 0x12682f58a35a292bab4e34ca761b9082bc101e36
  ...

  Request ID: 0x2fe23d227eac6212069ae943d8eeaafaab71df9f
  ...

  Request ID: 0x7596b17add9cf90344d05bb0e78302cd47e55d12
  ...

  Request ID: 0xa176dbc5e82ac9b1c93162ff8f142a8ad5beadaa
  ...

  Request ID: 0xc14831aa693224b9510793b45afdb22ac8ad5e8d
  ...

  Request ID: 0xd10ec4046e966dc0ea620d2f4c82a5bb3bf5a8ee
  ...
----------------------------
Number of entries returned 6
----------------------------
----
