= Overview =

This page describes the process to issue a user certificate using CMC shared token authentication.

It assumes that:

* Issuance protection certificate has been link:Creating-Issuance-Protection-Certificate[created].
* CMC shared token authentication has been link:Configuring-CMC-Shared-Token-Authentication[configured].
* A shared token has been link:Generating-CMC-Shared-Token[generated] for a user.

= Exporting Issuance Protection Certificate =

To export the issuance protection certificate from CA's NSS database:

----
$ pki-server \
    cert-export \
    --cert-file ca_issuance_protection.crt \
    ca_issuance_protection
----

= Importing Issuance Protection Certificate =

To import the issuance protection certificate into the client's NSS database:

----
$ pki \
    nss-cert-import \
    --cert ca_issuance_protection.crt \
    ca_issuance_protection
----

= Generating Certificate Request =

----
$ pki nss-key-create --output-format json | tee output
$ KEY_ID=$(jq -r '.keyId' output)

$ pki \
    nss-cert-request \
    --key-id $KEY_ID \
    --subject "uid=testuser" \
    --ext /usr/share/pki/tools/certs/testuser.conf \
    --csr testuser.csr
----

= Creating CMC Request =

----
$ cp \
    /usr/share/pki/tools/examples/cmc/testuser-cmc-request.cfg \
    testuser-cmc-request.cfg

$ sed -i \
    -e "s/\(request.privKeyId\)=.*/\1=$KEY_ID/" \
    testuser-cmc-request.cfg

$ CMCRequest \
     testuser-cmc-request.cfg
----

= Issuing User Certificate =

----
$ HttpClient \
     /usr/share/pki/tools/examples/cmc/testuser-cmc-submit.cfg

$ CMCResponse \
    -d /root/.dogtag/nssdb \
    -i testuser.cmc-response \
    -o testuser.p7b
----

= Importing User Certificate Chain =

----
$ pki \
    pkcs7-import \
    --pkcs7 testuser.p7b \
    testuser
----
