= Overview =

Each PKI branch that is actively maintained should have a corresponding COPR repository. When a new PKI branch is created from another branch, a new COPR repository should be forked from the COPR repository corresponding to the original branch.

----
+ master
  + v11.2
  + v11.1
  + v11.0
  + v10
    + v10.12
    + v10.11
----

For example, below is the process to create a new `@pki/11.2` repository for `v11.2` branch in PKI. The repository should be forked from an existing `@pki/master` repository. `v10.x` repositories should be forked from `v10` repository.

= Creating COPR Repository using Web UI =

To create the repository, open the link:https://copr.fedorainfracloud.org/coprs/g/pki/master[@pki/master] repository and click **Fork this project**. Change the **Fork owner** to `@pki` and **Fork name** to `11.2`, then click **Fork it**.

To update the packages, go to **Packages** in `@pki/11.2` repository and change the **Committish** of `pki` package to `v11.2`. Change the **Committish** of other packages as well if necessary. Rebuild the packages to verify the changes.

Finally, go to **Settings** -> **Integrations**, copy the Webhook URL for GitHub, append `?id=@pki/10.12` to the URL to make it easier to identify, then add the URL to each GitHub project.

= Creating COPR Repository using CLI =

To create the repository:

----
$ copr fork @pki/master @pki/11.2
----

To update the packages:

----
$ copr edit-package-scm \
    --name jss \
    --clone-url https://github.com/github/jss.git \
    --commit v5.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name tomcatjss \
    --clone-url https://github.com/github/tomcatjss.git \
    --commit v8.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name ldapjdk \
    --clone-url https://github.com/github/ldap-sdk.git \
    --commit v5.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name idm-console-framework \
    --clone-url https://github.com/github/idm-console-framework.git \
    --commit v2.0 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name pki \
    --clone-url https://github.com/github/pki.git \
    --commit v11.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
----

To build the packages:

----
$ copr build-package --name jss --nowait @pki/11.2
$ copr build-package --name tomcatjss --nowait @pki/11.2
$ copr build-package --name ldapjdk --nowait @pki/11.2
$ copr build-package --name idm-console-framework --nowait @pki/11.2
$ copr build-package --name pki --nowait @pki/11.2
----
