= Overview =

Each PKI branch that is actively maintained should have a corresponding COPR repository:

----
+ master    -->  @pki/master
  + v11.1   -->  @pki/11.1
  + v11.0   -->  @pki/11.0
+ v10       -->  @pki/10
  + v10.12  -->  @pki/10.12
  + v10.11  -->  @pki/10.11
----

When a new branch (e.g. `v11.2`) is created from an existing branch (e.g. `master`), a new COPR repository (i.e. `@pki/11.2`) should be created from the COPR repository corresponding to the existing branch (i.e. `@pki/master`). In general, all `@pki/11.x` repositories should be created from `@pki/master` repository, and all `@pki/10.x` repositories should be created from `@pki/10` repository.

= Creating New Repository =

To create the repository using Web UI, open the link:https://copr.fedorainfracloud.org/coprs/g/pki/master[@pki/master] repository and click **Fork this project**. Change the **Fork owner** to `@pki` and **Fork name** to `11.2`, then click **Fork it**.

To create the repository using CLI:

----
$ copr fork @pki/master @pki/11.2
----

= Dependencies =

* link:JAF-Dependency[JAF Dependency]
* link:JAXB-Dependency[JAXB Dependency]
* link:RESTEasy-Dependency[RESTEasy Dependency]
* link:Jackson-Dependency[Jackson Dependency]

= Updating Packages =

To update the packages using Web UI, go to **Packages** in `@pki/11.2` repository and change the **Committish** of `pki` package to `v11.2`. Change the **Committish** of other packages as well if necessary.

To update the packages using CLI:

----
$ copr edit-package-scm \
    --name jss \
    --clone-url https://github.com/dogtagpki/jss.git \
    --commit v5.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name tomcatjss \
    --clone-url https://github.com/dogtagpki/tomcatjss.git \
    --commit v8.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name ldapjdk \
    --clone-url https://github.com/dogtagpki/ldap-sdk.git \
    --commit v5.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name idm-console-framework \
    --clone-url https://github.com/dogtagpki/idm-console-framework.git \
    --commit v2.0 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
$ copr edit-package-scm \
    --name pki \
    --clone-url https://github.com/dogtagpki/pki.git \
    --commit v11.2 \
    --method make_srpm \
    --webhook-rebuild on \
    @pki/11.2
----

= Building Packages =

To build the packages:

----
$ copr build-package --name jss --nowait @pki/11.2
$ copr build-package --name tomcatjss --nowait @pki/11.2
$ copr build-package --name ldapjdk --nowait @pki/11.2
$ copr build-package --name idm-console-framework --nowait @pki/11.2
$ copr build-package --name pki --nowait @pki/11.2
----

= Configuring GitHub Webhooks =

Go to **Settings** -> **Integrations**, copy the Webhook URL for GitHub (e.g. `https://copr.fedorainfracloud.org/webhooks/github/<ID>/<UUID>/`), append `?id=<repository>` (e.g. `?id=@pki/11.2`) to the URL to make it easier to identify, then open each GitHub project's Webhooks configuration:

* https://github.com/dogtagpki/jss/settings/hooks
* https://github.com/dogtagpki/tomcatjss/settings/hooks
* https://github.com/dogtagpki/ldap-sdk/settings/hooks
* https://github.com/dogtagpki/idm-console-framework/settings/hooks
* https://github.com/dogtagpki/pki/settings/hooks

Click **Add webhook**, then enter:

* **Payload URL**: `https://copr.fedorainfracloud.org/webhooks/github/<ID>/<UUID>/?id=<repository >` 
* **Content type**: `application/json`

Then click **Add webhook**.

= See Also =

* link:https://stackoverflow.com/questions/69478970/how-to-create-a-webhook-from-curl-or-github-cli[How to create a webhook from curl or github cli]