= Creating Database =

See link:https://github.com/dogtagpki/nss/wiki/Creating-NSS-Database[Creating NSS Database].

= Modules =

See link:NSS-Modules[NSS Modules].

= Listing Certificates =

See link:https://github.com/dogtagpki/nss/wiki/Listing-Certificates[Listing Certificates].

= Displaying Certificate Info =

See link:Displaying-Certificate-Info[Displaying Certificate Info].

= Exporting Certificate =

See link:https://github.com/dogtagpki/nss/wiki/Exporting-Certificate[Exporting Certificate].

= Decoding Certificate =

See link:https://github.com/dogtagpki/nss/wiki/Decoding-Certificate[Decoding Certificate].

= Importing Certificate =

See link:https://github.com/dogtagpki/nss/wiki/Importing-Certificate[Importing Certificate].

= Exporting Certificate Chain =

Export each certificate in the certificate chain (see link:https://github.com/dogtagpki/pki/wiki/NSS-Database#Exporting_Certificate[Exporting Certificate]), then create a PKCS #7 file:

----
$ openssl crl2pkcs7 -nocrl -certfile ca1.crt -certfile ca2.crt ... -out cert_chain.p7b
----

Verify with the following command:

----
$ openssl pkcs7 -print_certs -in cert_chain.p7b
----

= Importing Certificate Chain =

Each certificate in the certificate chain can be imported individually:

----
$ certutil -A -d nssdb -a -i -n testcert -i testcert.pem -t CT,C,C
----

Alternatively, the entire certificate chain can be imported as a PKCS #7 file:

----
$ openssl pkcs7 -print_certs -in /tmp/cert_chain.p7b -out /tmp/cert_chain.pem
$ openssl pkcs12 -export -nokeys -in /tmp/cert_chain.pem -out /tmp/cert_chain.p12 -passout file:password.txt
$ pk12util -d nssdb -k password.txt -i /tmp/cert_chain.p12 -w password.txt
$ certutil -M -d nssdb -n <nickname> -t CT,C,C
----

= Exporting into PKCS #12 File =

To export the all keys and certificates in the database:

----
$ PKCS12Export -d nssdb -p password.internal -o output.p12 -w output.password
----

See also link:https://github.com/dogtagpki/nss/wiki/Exporting-PKCS12-File[Exporting PKCS12 File].

= Importing from PKCS #12 File =

See link:https://github.com/dogtagpki/nss/wiki/Importing-PKCS12-File[Importing PKCS12 File].

= Exporting from PKCS #12 File =

Export Cert from a PKCS #12 file:

----
$ openssl pkcs12 -in path.p12 -out newfile.crt.pem -clcerts -nokeys
----

Export encrypted RSA key from a pkics#12 (.p12) file:

----
$ openssl pkcs12 -in path.p12 -out newfile.key.pem -nocerts -nodes
----

Convert encrypted RSA key to unencrypted (pkcs#1):

----
$ openssl rsa -in newfile.key.pem -out newfile.key.pkcs1
----

Convert unencrypted RSA private key (pkcs#1) to pkcs#8 key:

----
$ openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in newfile.key.pkcs1 -out newfile.key
----

== Verify the exported cert and key match ==

----
$ openssl pkey -in privateKey.key -pubout -outform pem | sha256sum
$ openssl x509 -in certificate.crt -pubkey -noout -outform pem | sha256sum 
----

The output from both commands must match.

= Modifying a Certificate =

See link:https://github.com/dogtagpki/nss/wiki/Modifying-Certificate[Modifying Certificate].

= Validating Certificate =

See https://github.com/dogtagpki/nss/wiki/Validating-Certificate[Validating Certificate].

= Deleting Certificate =

See link:https://github.com/dogtagpki/nss/wiki/Deleting-Certificate[Deleting Certificate].

= Listing Keys =

See link:https://github.com/dogtagpki/nss/wiki/Listing-Keys[Listing Keys].

= Deleting a Key =

See link:https://github.com/dogtagpki/nss/wiki/Deleting-Key[Deleting Key].

= Cloning Database =

To clone an NSS database, export all certificates:

----
$ certutil -L -d nssdb -h HSM -n testcert -a > testcert.pem
----

Create the new database with the HSM modules if applicable:

----
$ mkdir clone
$ certutil -N -d nssdb
----

Then reimport all certificates:

----
$ certutil -A -d nssdb -h HSM -f password.HSM -n testcert -i testcert.pem -t "CT,C,C"
----

= Generating Key Pair =

Generate a key pair with the following command:

----
$ openssl rand -out noise.bin 2048
$ certutil -G -d nssdb -h internal -f password.internal -z nssdb/noise.bin


Generating key.  This may take a few moments...
----

= Generating Certificate Request =

== Creating Noise File ==

----
$ openssl rand -out noise.bin 2048
----

== Creating CSR File ==

Generate a CSR with the following command:

----
$ certutil -R \
 -d nssdb \
 -h internal \
 -f password.internal \
 -s "UID=testuser,O=EXAMPLE" \
 -z noise.bin \
 -o testuser.csr.der
$ BtoA testuser.csr.der testuser.csr.pem
$ echo "-----BEGIN NEW CERTIFICATE REQUEST-----" > testuser.csr
$ cat testuser.csr.pem >> testuser.csr
$ echo "-----END NEW CERTIFICATE REQUEST-----" >> testuser.csr
$ rm testuser.csr.der
$ rm testuser.csr.pem
----

= Creating Certificates =

* link:Creating-Self-Signed-CA-Signing-Certificate-with-NSS[Creating Self-Signed CA Signing Certificate with NSS]
* link:Creating-Self-Signed-SSL-Server-Certificate-with-NSS[Creating Self-Signed SSL Server Certificate with NSS]

= See Also =

* link:https://www.dogtagpki.org/wiki/NSS[NSS]
* link:https://www.dogtagpki.org/wiki/OpenSSL[OpenSSL]
* link:https://www.dogtagpki.org/wiki/HSM[HSM]
* link:https://www.dogtagpki.org/wiki/PKCS7[PKCS7]
* link:https://www.dogtagpki.org/wiki/PKCS11[PKCS11]
* link:https://www.dogtagpki.org/wiki/PKCS12[PKCS12]
* link:https://access.redhat.com/documentation/en-US/Red_Hat_Directory_Server/8.1/html/Administration_Guide/Managing_SSL-Using_certutil.html[RHDS 8.1 Administration Guide - Using certutil]
* link:http://adam.younglogic.com/2012/05/signing-certutil/[Generating a Signing Cert using certutil]
* link:https://tools.ietf.org/html/rfc5280#section-4.2.1.1[RFC 5280 - Authority Key Identifier]
* link:https://tools.ietf.org/html/rfc5280#section-4.2.1.2[RFC 5280 - Subject Key Identifier]
* link:http://security.stackexchange.com/questions/27797/what-damage-could-be-done-if-a-malicious-certificate-had-an-identical-subject-k[What damage could be done if a malicious certificate had an identical “Subject Key Identifier”?]
* link:https://knowledge.digicert.com/solution/SO5291.html[Extract cert and private key from pkcs12 file]
* link:https://www.sslshopper.com/certificate-key-matcher.html[Verify cert and key pair]
* link:https://fy.blackhats.net.au/blog/html/pages/nss_and_openssl_command_reference.html[NSS and OpenSSL Command Reference]
