= Overview =

The Certificate System CA supports the Online Certificate Status Protocol as defined in Public-Key Infrastructure (X.509) (PKIX) standard link:http://www.ietf.org/rfc/rfc2560.txt[RFC 2560]. The OCSP protocol enables OCSP-compliant applications to determine the state of a certificate, including the revocation status, without having to directly check a CRL published by a CA to the validation authority. The validation authority, which is also called an OCSP responder, checks for the application.

The Online Certificate Status Protocol (OCSP) subsystem is the component that provides OCSP responder services, which means it stored CRLs for CAs and can distribute the load for verifying certificate status.

= Supported Databases =

* link:https://directory.fedoraproject.org[389 Directory Server]
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server[Red Hat Directory Server]

= Installation =

* link:OCSP-Installation-Guide[OCSP Installation Guide]

= See Also =

* link:OCSPClient[OCSPClient]
* link:https://access.redhat.com/documentation/en-US/Red_Hat_Certificate_System/9/html/Administration_Guide/Online_Certificate_Status_Protocol_Responder.html[RHCS 9: Using the Online Certificate Status Protocol (OCSP) Responder]
* link:https://pagure.io/dogtagpki/issue/2703[Ticket #2703: OCSP subsystem generates invalid response]
* link:OCSP-Specification[OCSP Specification]
* link:https://www.dogtagpki.org/wiki/OCSP_Agent_Tasks[OCSP Agent Tasks]
* link:https://github.com/dogtagpki/tomcatjss[Tomcat JSS]
