= Overview =

OCSP audit events can be configured in log.instance.SignedAudit.events property.

= Default Events =

* link:https://github.com/dogtagpki/pki/blob/master/docs/admin/Default_OCSP_Audit_Events.md[Default OCSP Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_6_BRANCH/docs/admin/Default_OCSP_Audit_Events.md[PKI 10.6 Default OCSP Audit Events]
* link:https://github.com/dogtagpki/pki/blob/DOGTAG_10_5_BRANCH/docs/admin/Default_OCSP_Audit_Events.md[PKI 10.5 Default OCSP Audit Events]

= Signing Info Events =

* link:OCSP_SIGNING_INFO-Audit-Event[OCSP_SIGNING_INFO]

= OCSP Events =

== CONFIG_OCSP_PROFILE ==

* link:CONFIG_OCSP_PROFILE-Audit-Event[CONFIG_OCSP_PROFILE]

== OCSP_ADD_CA_REQUEST ==

* link:OCSP_ADD_CA_REQUEST-Audit-Event[OCSP_ADD_CA_REQUEST]
* link:OCSP_ADD_CA_REQUEST_PROCESSED-Audit-Event[OCSP_ADD_CA_REQUEST_PROCESSED]

== OCSP_REMOVE_CA_REQUEST ==

* link:OCSP_REMOVE_CA_REQUEST-Audit-Event[OCSP_REMOVE_CA_REQUEST]
* link:OCSP_REMOVE_CA_REQUEST_PROCESSED_SUCCESS-Audit-Event[OCSP_REMOVE_CA_REQUEST_PROCESSED_SUCCESS]
* link:OCSP_REMOVE_CA_REQUEST_PROCESSED_FAILURE-Audit-Event[OCSP_REMOVE_CA_REQUEST_PROCESSED_FAILURE]
* link:OCSP_REMOVE_CA_REQUEST_PROCESSED-Audit-Event[OCSP_REMOVE_CA_REQUEST_PROCESSED]

== OCSP_GENERATION ==

Since version 10.5 an OCSP_GENERATION event will be generated for each OCSP response generated by link:https://github.com/dogtagpki/pki/blob/master/docs/installation/ocsp/Installing_OCSP.md[OCSP subsystem].

For example, use the link:Using-OCSPClient[OCSPClient] to submit an OCSP request:

----
$ OCSPClient \
    -d ~/.dogtag/pki-tomcat/ca/alias \
    -h $HOSTNAME \
    -p 8080 \
    -t /ocsp/ee/ocsp \
    -c ca_signing \
    --serial 1
CertID.serialNumber=1
CertStatus=Good
----

The server will generate the following log when the OCSP response generation is complete:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Success] OCSP resp
onse generation
----

If the OCSP response generation fails, the server will log the failure reason:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=<reason>] OCSP response generation
----

For example, if the CA has not published the CRL, the following log will be generated:

----
[AuditEvent=OCSP_GENERATION][SubjectID=$NonRoleUser$][Outcome=Failure][FailureRe
ason=Missing CRL data] OCSP response generation
----

See also link:CA-Audit-Events[OCSP_GENERATION in CA Audit Events].

= See Also =

* link:OCSP-Responder[OCSP Responder]
