= Preparing TPS Clone =

To export the TPS system certificates for cloning, execute the following command:

----
$ pki-server tps-clone-prepare --pkcs12-file tps-clone.p12 --pkcs12-password-file password.txt
----

See also link:https://www.dogtagpki.org/wiki/Installing_TPS_Clone[Installing TPS Clone].

= TPS Database Management =

* link:PKI-Server-Subsystem-Database-CLI[PKI Server Subsystem Database CLI]

== Listing TPS VLVs ==

To list TPS VLV indexes currently in the database execute the following command:

----
$ pki-server tps-db-vlv-find
---------------
4 entries found
---------------
  dn: cn=listActivities,cn=tps,cn=ldbm database,cn=plugins,cn=config
  objectClass: top
  objectClass: vlvsearch
  vlvScope: 1
  vlvFilter: (&(tokenID=*)(tokenUserID=*))
  vlvBase: ou=Activities,dc=tps,dc=pki,dc=example,dc=com
  cn: listActivities

...
----

== Adding TPS VLVs ==

To import TPS VLV indexes from link:https://git.fedorahosted.org/cgit/pki.git/tree/base/tps/shared/conf/vlv.ldif[/usr/share/pki/tps/conf/vlv.ldif] into the database execute the following command:

----
$ pki-server tps-db-vlv-add
----------
VLVs added
----------
----

== Reindexing TPS VLVs ==

To rebuild TPS VLV indexes in the database execute the following command:

----
$ pki-server tps-db-vlv-reindex
----------------
Reindex complete
----------------
----

Depending on the size of the database, the command may take some time to complete.

== Deleting TPS VLVs ==

To remove TPS VLV indexes currently in the database execute the following command:

----
$ pki-server tps-db-vlv-del
------------
VLVs deleted
------------
----

= TPS Audit Management =

* link:PKI-Server-Audit-CLI[PKI Server Audit CLI]

= References =

* link:https://github.com/dogtagpki/pki/wiki/PKI-Server-CLI[PKI Server CLI]
* link:https://www.dogtagpki.org/wiki/DS_Database_Indexes[DS Database Indexes]
* link:https://github.com/dogtagpki/pki/blob/master/docs/upgrade/v10.3/Upgrading_PKI_Database.adoc[Database Upgrade for PKI 10.3.x]
