= Overview =

PKI provides tools to upgrade the internal LDAP database.

= Displaying Database Status (Not Implemented Yet) =

----
$ pki-server db-status
  Hostname: server.example.com
  Port: 636
  SSL: yes
  Client Certificate: subsystemCert pki-tomcat
----

= Database Upgrade =

The pki-server db-upgrade is a tool to upgrade PKI server LDAP database. Currently the upgrade includes:

* link:https://fedorahosted.org/pki/ticket/1667[Ticket #1667: adding issuerName attribute]

See the link:https://git.fedorahosted.org/cgit/pki.git/tree/base/server/python/pki/server/cli/db.py[source code] for details.

This tool is used as part of link:https://github.com/dogtagpki/pki/blob/master/docs/upgrade/v10.2/Upgrading_PKI_Database.adoc[Database Upgrade for PKI 10.2.x]. To run the database upgrade:

----
$ pki-server db-upgrade
----------------
Upgrade complete
----------------
----

= Schema Upgrade =

The pki-server db-schema-upgrade is a tool to upgrade PKI server LDAP schema. Currently the upgrade includes:

* re-applying link:https://git.fedorahosted.org/cgit/pki.git/tree/base/server/share/conf/schema.ldif[/usr/share/pki/server/conf/schema.ldif]

See the link:https://git.fedorahosted.org/cgit/pki.git/tree/base/server/python/pki/server/cli/db.py[source code] for details.

----
$ pki-server db-schema-upgrade -D "cn=Directory Manager" -w Secret.123
----------------
Upgrade complete
----------------
----

See also the following tickets:

* link:https://fedorahosted.org/pki/ticket/2319[Ticket #2319: Add / revise vlv indexes for KRA due to realm changes]
* link:https://fedorahosted.org/pki/ticket/2320[Ticket #2320: Add db migration scripts for schema, vlv and index changes]

= Reference =

* link:https://github.com/dogtagpki/pki/wiki/PKI-Server-CLI[PKI Server CLI]
* link:Upgrading-PKI-Database[Database Upgrade]
