= Overview =

PKI server supports the following directory structures:

* `pki-tomcatd`: This directory structure is used to run PKI server in Fedora which follows the link:http://www.pathname.com/fhs/[Filesystem Hierarchy Standard].
* `tomcat`: This directory structure is used to run PKI server in generic Tomcat environment. The support for this directory structure is still under development.

If not specified, PKI server will use `pki-tomcatd` by default.

= `pki-tomcatd` Directory Structure =

With `pki-tomcatd` directory structure, the files are stored in multiple directories.

The configuration files are stored under `/etc/pki/<instance>`:

----
+ /etc/pki/<instance>
  + alias
  + Catalina
    + localhost
  + <subsystem>
----

The server files are stored under `/var/lib/pki/<instance>`:

----
+ /var/lib/pki/<instance>
  + alias -> /etc/pki/<instance>/alias
  + bin -> /usr/share/tomcat/bin
  + common
    + lib -> /usr/share/pki/server/common/lib
  + conf -> /etc/pki/<instance>
  + lib -> /usr/share/pki/server/lib
  + logs -> /var/log/pki/<instance>
  + temp
  + webapps
  + work
  + <subsystem>
----

The log files are stored under `/var/lib/pki/<instance>`:

----
+ /var/log/pki/<instance>
  + backup
    + <version>
      + <index>
        + oldfiles
        + newfiles
  + pki
  + <subsystem>
    + archive
    + signedAudit
----

The systemd unit file is stored at `/etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@<instance>.service` which is a link to link:https://github.com/dogtagpki/pki/blob/master/base/server/share/lib/systemd/system/pki-tomcatd%40.service[/usr/lib/systemd/system/pki-tomcatd@.service].

The registry files are stored under `/etc/sysconfig/pki/tomcat/<instance>`:

----
+ /etc/sysconfig/pki/tomcat/<instance>
  + <subsystem>
----

= `tomcat` Directory Structure =

With `tomcat` directory structure, all files are stored under a single directory (e.g. `/var/lib/tomcats/<instance>`):

----
+ /var/lib/tomcats/<instance>
  + bin
  + common
    + lib
  + conf
    + <subsystem>
  + lib
  + logs
    + pki
    + <subsystem>
      + archive
      + signedAudit
  + temp
  + webapps
  + work
----

The systemd unit file is stored at `/usr/lib/systemd/system/tomcat@.service`.

= See Also =

* link:PKI-Server-Create-CLI[PKI Server Create CLI]
