= Listing Certificate Records =

To list certificate records in CA:

----
$ pki-server ca-cert-find
----

= Creating Certificate =

To create a certificate from a certificate request in CA:

----
$ pki-server ca-cert-create \
    --request <ID> \
    --profile <ID> \
    --key-ID <ID> \
    --serial <serial>
----

**Availability:** Since PKI 11.3.

= Importing Certificate =

To import a certificate into CA:

----
$ pki-server ca-cert-import \
    --cert <path> \
    --profile <ID> \
    --request <ID>
----

**Availability:** Since PKI 11.3.

= Removing Certificate Record =

To remove a certificate record from CA:

----
$ pki-server ca-cert-del <serial>
----

= Exporting Certificate Chain =

To export certificate chain to install additional subsystems:

----
$ pki-server ca-cert-chain-export --pkcs12-file cert-chain.p12 --pkcs12-password-file password.txt
----

= Finding Certificate Requests =

To find the certificate request for a certificate:

----
$ pki-server ca-cert-request-find --cert-file <cert file>
----

As of PKI 10.4 the content of the certificate has to be formatted as follows:

* The certificate must be base-64 encoded.
* Each line must be 64 bytes long terminated with CRLF.
* There is no BEGIN/END CERTIFICATE header/footer.

For example:

----
MIIDnTCCAoWgAwIBAgIBBTANBgkqhkiG9w0BAQsFADBIMRAwDgYDVQQKDAdFWEFN<CRLF>
UExFMRMwEQYDVQQLDApwa2ktdG9tY2F0MR8wHQYDVQQDDBZDQSBTaWduaW5nIENl<CRLF>
...
EzgqNUFrj/ATV31qVzEb6aka+93bd437Iga68OTz+8fhif8TbILWfJG87rU3w00D<CRLF>
DMK8f1ILzfnK1kUEkBQ9zoiDlQyiUsl6TDJKXFc8Woqi0VTgK2AJ7cVdrwtOiE++<CRLF>
6jk3lUH/goACLP5fIuZWqlM=<CRLF>
----

Note: The certificate format may change in the future.

= Displaying Certificate Request =

----
$ pki-server ca-cert-request-show <request ID>
----

= Exporting System Certificates =

To export system certificates to clone CA:

----
$ pki-server ca-clone-prepare --pkcs12-file ca-clone.p12 --pkcs12-password-file password.txt
----
