= Overview =

This page describes the directory structure of a PKI server instance.

= Default Directory Structure =

By default PKI server is installed with the following directory structure.

Configuration files are stored under `/etc/pki/<instance>`:

----
+ /etc/pki/<instance>
  + alias
  + Catalina
    + localhost
  + <subsystem>
----

Server files are stored under `/var/lib/pki/<instance>`:

----
+ /var/lib/pki/<instance>
  + alias -> /etc/pki/<instance>/alias
  + bin -> /usr/share/tomcat/bin
  + common
    + lib -> /usr/share/pki/server/common/lib
  + conf -> /etc/pki/<instance>
  + lib -> /usr/share/pki/server/lib
  + logs -> /var/log/pki/<instance>
  + temp
  + webapps
  + work
  + <subsystem>
----

Log files are stored under `/var/lib/pki/<instance>`:

----
+ /var/log/pki/<instance>
  + backup
    + <version>
      + <index>
        + oldfiles
        + newfiles
  + pki
  + <subsystem>
    + archive
    + signedAudit
----

The systemd unit file is stored at `/etc/systemd/system/pki-tomcatd.target.wants/pki-tomcatd@<instance>.service` which is a link to link:https://github.com/dogtagpki/pki/blob/master/base/server/share/lib/systemd/system/pki-tomcatd%40.service[/usr/lib/systemd/system/pki-tomcatd@.service].

Registry files are stored under `/etc/sysconfig/pki/tomcat/<instance>`:

----
+ /etc/sysconfig/pki/tomcat/<instance>
  + <subsystem>
----

= Tomcat Directory Structure =

Certain PKI subsystems can be installed with standard Tomcat directory structure. In the future it might be possible to install all subsystems with this directory structure.

All files are stored under `/var/lib/tomcats/<instance>`:

----
+ /var/lib/tomcats/<instance>
  + bin
  + common
    + lib
  + conf
    + <subsystem>
  + lib
  + logs
    + pki
    + <subsystem>
      + archive
      + signedAudit
  + temp
  + webapps
  + work
----

The systemd unit file is stored at `/usr/lib/systemd/system/tomcat@.service`.

= See Also =

* link:PKI-Server-Create-CLI[PKI Server Create CLI]
