= Overview =

The `pki-server create` command can be used to create a PKI Tomcat server or a standard Tomcat server.
Initially the server will not have any PKI subsystems.
The subsystems can be added separately later.
This command can be used to troubleshoot general Tomcat issues (e.g. SSL).

The command supports several server types:

* `pki-tomcatd`: This type indicates that the server will have a layout of a Tomcat server with PKI customizations.
* `tomcat`: This type indicates that the server will have a layout of a standard Tomcat server.

The command can be used as follows:

----
$ pki-server create [<type>@]<name>
----

The **type** indicates the server type. If not specified, the default type is `pki-tomcatd`.

The **name** indicates the name of the instance.

= Creating PKI Tomcat Server =

To create a PKI Tomcat server execute the following command:

----
$ pki-server create pki-tomcatd@<name>
----

or simply:

----
$ pki-server create <name>
----

= Creating Standard Tomcat Server =

To create a standard Tomcat server execute the following command:

----
$ pki-server create tomcat@<name>
----
