= Overview =

PKI 10.6 provides a CLI to manage the secure and unsecure HTTP connectors.

= Listing HTTP Connectors =

----
$ pki-server http-connector-find
-----------------
2 entries matched
-----------------
  Connector ID: Secure
  Scheme: https
  Port: 8443
  Protocol: org.apache.coyote.http11.Http11Protocol
  SSL Implementation: org.apache.tomcat.util.net.jss.JSSImplementation
  SSL Version Range Stream: tls1_0:tls1_2
  SSL Version Range Datagram: tls1_1:tls1_2
  SSL Range Ciphers: -TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_256_CBC_SHA,-TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_DSS_WITH_AES_128_CBC_SHA,-TLS_DHE_DSS_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_AES_128_CBC_SHA256,-TLS_RSA_WITH_AES_256_CBC_SHA256,-TLS_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_3DES_EDE_CBC_SHA,+TLS_RSA_WITH_AES_128_CBC_SHA,+TLS_RSA_WITH_AES_256_CBC_SHA
  NSS Database Directory: /var/lib/pki/pki-tomcat/alias
  NSS Password Class: org.apache.tomcat.util.net.jss.PlainPasswordFile
  NSS Password File: /var/lib/pki-tomcat/conf/password.conf
  Server Cert Nickname File: /var/lib/pki/pki-tomcat/conf/serverCertNick.conf

  Connector ID: Unsecure
  Port: 8080
  Protocol: HTTP/1.1
----

= Displaying HTTP Connector Details =

----
$ pki-server http-connector-show Unsecure
  Connector ID: Unsecure
  Port: 8080
  Protocol: HTTP/1.1
----

= Adding HTTP Connector =

Available since: PKI 10.7

----
$ pki-server http-connector-add Secure \
    --port 8443 \
    --scheme https \
    --secure true \
    --sslEnabled true
----

= Removing HTTP Connector =

Available since: PKI 10.7

----
$ pki-server http-connector-del Secure
----

= Modiying HTTP Connector =

To change connector type or implementation, specify the following parameters:

----
$ pki-server http-connector-mod <Connector ID> --type <type>
----

Valid types are JSS and JSSE.

To modify a connector attribute, specify the parameter corresponding to the attribute to change:

----
$ pki-server http-connector-mod <Connector ID> [<param> <value>...]
----

If the value is non-empty, the attribute will be overwritten.
If the value is an empty string, the attribute will be removed.
Other attributes will not be changed.

== Switching to JSS Connector ==

To configure JSS Connector:

----
$ pki-server http-connector-mod Secure --type JSS
-----------------
Updated connector
-----------------
  Connector ID: Secure
  Scheme: https
  Port: 8443
  Protocol: org.apache.coyote.http11.Http11Protocol
  SSL Implementation: org.apache.tomcat.util.net.jss.JSSImplementation
  SSL Version Range Stream: tls1_0:tls1_2
  SSL Version Range Datagram: tls1_1:tls1_2
  SSL Range Ciphers: -TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_256_CBC_SHA,-TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_DSS_WITH_AES_128_CBC_SHA,-TLS_DHE_DSS_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_AES_128_CBC_SHA256,-TLS_RSA_WITH_AES_256_CBC_SHA256,-TLS_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_3DES_EDE_CBC_SHA,+TLS_RSA_WITH_AES_128_CBC_SHA,+TLS_RSA_WITH_AES_256_CBC_SHA
  NSS Database Directory: /var/lib/pki/pki-tomcat/alias
  NSS Password Class: org.apache.tomcat.util.net.jss.PlainPasswordFile
  NSS Password File: /var/lib/pki/pki-tomcat/conf/password.conf
  Server Cert Nickname File: /var/lib/pki/pki-tomcat/conf/serverCertNick.conf
----

== Switching to JSSE Connector ==

=== Creating password file ===

Store the password for the PKCS #12 files into a file:

----
$ echo Secret.123 > /etc/pki/pki-tomcat/keystore.pwd
$ chown pkiuser.pkiuser /etc/pki/pki-tomcat/keystore.pwd
$ chmod 0660 /etc/pki/pki-tomcat/keystore.pwd
----

=== Exporting SSL server certificate ===

Export the SSL server certificate with the following command:

----
$ pki-server cert-export \
    sslserver \
    --instance "pki-tomcat" \
    --pkcs12-file /etc/pki/pki-tomcat/keystore.p12 \
    --pkcs12-password-file /etc/pki/pki-tomcat/keystore.pwd \
    --cert-encryption "PBE/SHA1/RC2-40" \
    --key-encryption "PBE/SHA1/DES3/CBC"
----

Alternatively, the SSL server certificate can be exported with the following command:

----
$ pk12util \
    -n sslserver \
    -d /var/lib/pki/pki-tomcat/alias \
    -k Secret.123 \
    -o /etc/pki/pki-tomcat/keystore.p12 \
    -w /etc/pki/pki-tomcat/keystore.pwd
----

Then configure the file permission as follows:

----
$ chown pkiuser.pkiuser /etc/pki/pki-tomcat/keystore.p12
$ chmod 0660 /etc/pki/pki-tomcat/keystore.p12
----

=== Configuring JSSE connector ===

To configure JSSE connector:

----
$ pki-server http-connector-mod Secure \
    --type JSSE \
    --keystore-file /etc/pki/pki-tomcat/keystore.p12 \
    --keystore-password-file /etc/pki/pki-tomcat/keystore.pwd
-----------------
Updated connector
-----------------
  Connector ID: Secure
  Scheme: https
  Port: 8443
  Protocol: org.dogtagpki.tomcat.Http11NioProtocol
  SSL Version Range Stream: tls1_0:tls1_2
  SSL Version Range Datagram: tls1_1:tls1_2
  SSL Range Ciphers: -TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDH_RSA_WITH_AES_256_CBC_SHA,-TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,-TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_DSS_WITH_AES_128_CBC_SHA,-TLS_DHE_DSS_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA,-TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,-TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,-TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,-TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_AES_128_CBC_SHA256,-TLS_RSA_WITH_AES_256_CBC_SHA256,-TLS_RSA_WITH_AES_128_GCM_SHA256,-TLS_RSA_WITH_3DES_EDE_CBC_SHA,+TLS_RSA_WITH_AES_128_CBC_SHA,+TLS_RSA_WITH_AES_256_CBC_SHA
  NSS Database Directory: /var/lib/pki/pki-tomcat/alias
  NSS Password Class: org.apache.tomcat.util.net.jss.PlainPasswordFile
  NSS Password File: /var/lib/pki/pki-tomcat/conf/password.conf
  Server Cert Nickname File: /var/lib/pki/pki-tomcat/conf/serverCertNick.conf
  Keystore File: /etc/pki/pki-tomcat/keystore.p12
  Keystore Password File: /etc/pki/pki-tomcat/keystore.pwd
----

= See Also =

* link:PKI-Server-HTTP-Connector-Host-CLI[PKI Server HTTP Connector Host CLI]
* link:PKI-Server-HTTP-Connector-Cert-CLI[PKI Server HTTP Connector Cert CLI]
* link:https://www.dogtagpki.org/wiki/Tomcat_SSL[Tomcat SSL]
* link:https://www.dogtagpki.org/wiki/SSL[SSL]
* link:PKCS12[PKCS12]
* link:https://tomcat.apache.org/tomcat-8.5-doc/config/http.html[The HTTP Connector]
