= Overview =

PKI provides CLI to access various TPS services.

To list all available TPS services:

----
$ pki tps
Commands:
 tps-activity            Activity management commands
 tps-audit               Audit management commands
 tps-authenticator       Authenticator management commands
 tps-cert                Certificate management commands
 tps-config              Configuration management commands
 tps-connection          Connection management commands
 tps-group               Group management commands
 tps-profile             Profile management commands
 tps-selftest            Selftest management commands
 tps-token               Token management commands
 tps-user                User management commands
----

Type `pki <service>` to see all available commands for the TPS service.
Type `pki <command> --help` to see the command usage.

= Commands =

* link:PKI-Audit-CLI[PKI Audit CLI]
* link:PKI-Group-CLI[PKI Group CLI]
* link:PKI-Selftest-CLI[PKI Selftest CLI]
* link:PKI-User-CLI[PKI User CLI]
* link:PKI-TPS-Activity-CLI[PKI TPS Activity CLI]
* link:PKI-TPS-Authenticator-CLI[PKI TPS Authenticator CLI]
* link:PKI-TPS-Certificate-CLI[PKI TPS Certificate CLI]
* link:https://github.com/dogtagpki/pki/blob/master/docs/user/tools/Using-PKI-TPS-Configuration-CLI.adoc[PKI TPS Configuration CLI]
* link:PKI-TPS-Connector-CLI[PKI TPS Connector CLI]
* link:PKI-TPS-Profile-CLI[PKI TPS Profile CLI]
* link:PKI-TPS-Profile-Mapping-CLI[PKI TPS Profile Mapping CLI]
* link:PKI-TPS-Token-CLI[PKI TPS Token CLI]

= See Also =

* link:PKI-CLI[PKI CLI]
* link:https://www.dogtagpki.org/wiki/TPS[TPS]
