= Overview =

This page describes the CLI commands to manage keys in KRA.
It assumes link:https://github.com/dogtagpki/pki/blob/master/docs/installation/kra/Installing_KRA.md[KRA] is already installed.
All key operations have to be executed with link:https://www.dogtagpki.org/wiki/KRA_Agent_Setup[KRA Agent] credentials.

A request has the following properties:

* request ID
* key ID
* type
* status

A key has the following properties:

* key ID
* client key ID
* status: active or inactive
* owner
* type
* type-specific properties

A key ID is an ID generated by the server which is unique for each key stored in the server. A client key ID is an ID provided by the client while generating or archiving a key. The client key ID does not have to be unique, but there can only be one active key for each client key ID. To generate/archive a new key with the same client key ID, the existing active key will need to be deactivated first.

= Key Request Templates =

* link:PKI-KRA-Key-Template-CLI[PKI KRA Key Template CLI]

= Key Request Management =

* link:PKI-KRA-Key-Request-CLI[PKI KRA Key Request CLI]

= Key Management =

All key operations should be executed as KRA agent.

== Listing Keys ==

* link:Listing-Keys-in-KRA[Listing Keys in KRA]

== Generating Key ==

* link:Generating-Key-in-KRA[Generating Key in KRA]

== Archiving Key ==

* link:Archiving-Key-in-KRA[Archiving Key in KRA]

== Recovering Key ==

* link:Recovering-Key-in-KRA[Recovering Key in KRA]

== Retrieving Key ==

* link:Retrieving-Key-in-KRA[Retrieving Key in KRA]

== Displaying Key Info ==

* link:Displaying-Key-Info-in-KRA[Displaying Key Info in KRA]

== Changing Key Status ==

* link:Changing-Key-Status-in-KRA[Changing Key Status in KRA]

= See Also =

* link:https://github.com/dogtagpki/pki/wiki/PKI-CLI[PKI CLI]
* link:https://www.dogtagpki.org/wiki/Key_Management[Key Management]
* link:https://www.dogtagpki.org/wiki/Certificate_Key_Archival[Certificate Key Archival]
