= Overview =

PKI server provides a tool to manage link:Access-Banner[Access Banner].

By default PKI server does not have any banner installed. To install a banner, create `/etc/pki/pki-tomcat/banner.txt` and store the banner message in this file, for example:

----
WARNING!
Access to this service is restricted to those individuals with
specific permissions. If you are not an authorized user, disconnect
now. Any attempts to gain unauthorized access will be prosecuted to
the fullest extent of the law.
----

The banner message must be UTF-8 encoded.

To uninstall the banner, simply remove `/etc/pki/pki-tomcat/banner.txt`.

= Displaying Banner =

By default the PKI server does not have any banner installed:

----
$ pki-server banner-show
ERROR: Banner is not installed
----

If a banner is installed, it can be displayed with this command:

----
$ pki-server banner-show
WARNING!
Access to this service is restricted to those individuals with
specific permissions. If you are not an authorized user, disconnect
now. Any attempts to gain unauthorized access will be prosecuted to
the fullest extent of the law.
----

If the banner contains invalid characters or empty, it will be displayed as is:

----
$ pki-server banner-show
3▒K~▒▒E▒O▒.涯▒▒~▒▒
----

= Installing Banner  (Not Yet Implemented) =

To install banner file:

----
$ pki-server banner-install --file <path>
----

= Uninstalling Banner (Not Yet Implemented) =

To uninstall banner:

----
$ pki-server banner-uninstall
----

= Validating Banner =

To validate banner that has been installed on the server:

----
$ pki-server banner-validate
---------------
Banner is valid
---------------
----

If the installed banner is invalid:

----
$ pki-server banner-validate
ERROR: Banner contains invalid character(s)
----

If the server does not have any banner installed:

----
$ pki-server banner-validate
-----------------------
Banner is not installed
-----------------------
----

To validate banner file that has not been installed:

----
$ pki-server banner-validate --file <path>
---------------
Banner is valid
---------------
----

= See Also =

* link:PKI-Server-CLI[PKI Server CLI]
* link:Access-Banner[Access Banner]
