= Overview =

The `pki-server <subsystem>-user` commands provide a way to manage users in subsystem database even when PKI server is offline.
These commands can only be executed by the system administrator.

= Listing Subsystem Users =

To list the users in the subsystem:

----
$ pki-server <subsystem>-user-find
  User ID: CA-localhost.localdomain-8443
  Full Name: CA-localhost.localdomain-8443
  Type: agentType 
  State: 1 

  User ID: caadmin
  Full Name: caadmin
  Email: caadmin@example.com 
  Type: adminType 
  State: 1 

  User ID: pkidbuser
  Full Name: pkidbuser
  Type: agentType 
  State: 1 
----

= Displaying Subsystem User Info =

To display the subsystem user info:

----
$ pki-server <subsystem>-user-show pkidbuser
  User ID: pkidbuser
  Full Name: pkidbuser
  Type: agentType 
  State: 1 
----

= Adding Subsystem User =

To add a subsystem user, specify the user ID, the full name, and the type:

----
$ pki-server <subsystem>-user-add \
    --full-name "Test User" \
    --type adminType \
    testuser 
----

In PKI 11.6 or later the user certificate can be specified with the `--cert <path>` option.

= Modifying Subsystem User =

To modify a subsystem user, specify the user ID and the attributes to change:

----
$ pki-server <subsystem>-user-mod testuser --add-see-also uid=testuser
----

= Resetting Subsystem User Password =

To reset user password, specify the new password as follows:

----
$ pki-server <subsystem>-user-mod testuser --password Secret.123
----

Alternatively, the new password can be specified in a file:

----
$ pki-server <subsystem>-user-mod testuser --password-file password.txt
----

**Availability:** Since PKI 11.5

= Removing Subsystem User =

To remove a subsystem user, specify the user ID:

----
$ pki-server <subsystem>-user-del testuser
----

**Availability:** Since PKI 11.1

= See Also =

* link:PKI-Server-Subsystem-User-Certificate-CLI[PKI Server Subsystem User Certificate CLI]
* link:PKI-Server-Subsystem-User-Role-CLI[PKI Server Subsystem User Role CLI]
