= Overview =

This proposal introduces a new mechanism for generating certificate serial numbers based purely on a random number.

The serial number field on X509 certificates are allotted 160 bits (20 bytes) maximum. Current link:https://cabforum.org/2016/03/31/ballot-164[CA/BF guidelines] place this at 64 bits (8 bytes) of entropy. Other requirements are at least 20.

This proposal suggests using 128 bits (16 bytes) of random data from JSS's internal SecureRandom source. This would become the only option supported on PKI 10.11+. The older random serial number ranges would be removed and not supported.

Note that two earlier proposals exist: link:https://www.dogtagpki.org/wiki/Random_Certificate_Serial_Numbers_v1[v1 which was implemented] and link:https://www.dogtagpki.org/wiki/Random_Certificate_Serial_Numbers_v2[v2 which was not]. These are provided as justification for random serial numbers in general. 

== Benefits ==

No risk of serial number range replication conflicts: these would be ignored, support would be removed from the code, and eventually removed from the DS instance as well. This also includes removal of RSNv1 support.

Low risk of collision: collision would have to occur prior to replication on distributed ranges. This would occur with instantaneous probability `$num_replicas / 2**$bits_entropy`. However, we also have to contend with other certificates issued by replicas that haven't yet replicated. This roughly translates to `$num_replicas * $avg_rate_of_issuance * $replication_delay`. IPA caps replications at 50, so this should always be sufficiently small with 128 bits of entropy: 10^-26 given 50 replicas, 1000 certs/sec, and a year of replication delay -- about 11PB of data assuming 8k/cert. (Note that due to our DN structure in LDAP, we are prevented from issuing certificates with duplicate serial numbers by LDAP outside of the aforementioned replication conflict zone. Only certificates which haven't yet been replicated across the entire environment are subject to collisions.)

Easy to generate: pull from `SecureRandom`, put into serial number field. Stateless. Helps with containerization efforts. (Doesn't rely on replica id like serial number ranges do).

Above current standards: 128-bits exceeds the random size most CAs currently issue with. Since CA/BF targets 64-bits of entropy and we push that to 128-bits, we likely meet their next target for doubling. Above this, since the field is limited to 160-bits, it is unlikely to have another doubling without further modifications to other RFCs. By leaving the remaining 32 bits, if there's a need to change serial number issuance in the future, we just need to ensure it is consistently over 128-bits (but still within the allotted 160 bits).

By removing incremental and RSNv1 formats, we can simplify the code and database significantly.

== Risks ==

To our knowledge, nobody (between IPA and customers) is dependent on the current serial number mechanism. Additionally, we've already had RSNv1 implemented for a while, so any external systems should theoretically be able to support either.

As discussed above, it is unlikely that collision poses a viable risk except when replication fails for an extended period of time.

Also, not mentioned above, there's a risk of colliding with existing serial numbers from earlier schemes. Assuming the same rate of issuance and same number of replicas above, but issuing for 10 years prior, this produces a collision risk of 10^-25. However, the likelihood of anyone reaching this is low as that's ~114PB of data using above 8k/cert assumption.

If existing logic exists for retrying issuance under a different serial number, it should be left in place. However, the likelihood of colliding with an existing certificate is sufficiently low not to warrant adding retry logic, in my opinion.

= Older v3 Proposals =

Note that these proposals are deprecated in favor of the above. 

This proposal introduces a new mechanism for generating random certificate serial number based on UUID or a purely random number.
UUID is a 128-bit number defined in link:https://www.ietf.org/rfc/rfc4122.txt[RFC 4122].
The UUID is practically guaranteed to be unique globally without relying on a shared database or communication between replicas.
It has approximately 120 bits of random entropy.

== UUID Version 4 ==

Java provides a UUIDv4 implementation which can be generated as follows:

----
UUID serialNumber = UUID.randomUUID();
----

Internally, the UUID will be generated using Java SecureRandom class.
If Java is configured with JSS security provider, the UUID will eventually be generated by NSS pkcs11prng.

See also:

* https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/UUID.java#L147-L157
* https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/UUID.java#L102

== UUID Version 5 ==

A Java implementation of UUID version 5 is described in link:https://stackoverflow.com/questions/40230276/how-to-make-a-type-5-uuid-in-java[this page].

== UUID Version 6 ==

UUID version 6 is proposed in link:http://gh.peabody.io/uuidv6[this page].

== Non-UUID 128-bit value ==

An alternative to using a UUID library is using a purely unique 128-bit random value. This gives us a full 128-bits of entropy (as would likely be the next target for a CA/BF update) without losing any to UUID format specification. Additionally, we could call JSS's pk11prng directly.

== Other Considerations ==

A numeric prefix could be assigned to different serial number versions.

* `00` could be grandfathered as incremental serial numbers.
* `01` could be grandfathered (and modified) as link:https://github.com/dogtagpki/pki/wiki/Random-Certificate-Serial-Numbers-v1[Random Certificate Serial Numbers v1] proposal.
* `03` could be assigned to this proposal.

This could be prepended in front of the random number discussed above. This would take a single byte, on top of the 128-bit UUID or random value, for a total of 17 bytes out of a 20-byte field.

= See Also =

* link:https://www.ietf.org/rfc/rfc4122.txt[RFC 4122: A Universally Unique IDentifier (UUID) URN Namespace]
