= Overview =

This proposal introduces a new mechanism for generating fully random serial numbers for certificates, keys, and requests in PKI. Currently PKI supports the following mechanisms to generate serial numbers:

* range-based sequential serial numbers (this is the default)
* link:Random-Certificate-Serial-Numbers-v1[range-based random serial number] (a.k.a. v1)

There are also older proposals that were never implemented:

* link:Random-Certificate-Serial-Numbers-v2[hybrid random serial numbers] (a.k.a. v2)
* link:UUID-based-Random-Certificate-Serial-Numbers[UUID-based random serial numbers] (a.k.a. old v3)

The current proposal (i.e. new v3) is similar to the old v3 proposal except that it will use a full 128 bit (16 bytes) random number from PKCS #11 PRNG instead of UUID.

This proposal will be implemented as a new option, so the existing range-based sequential serial numbers and range-based random serial number should continue to work.

== Standard Compliance ==

According to link:https://tools.ietf.org/html/rfc5280[RFC 5280] section 4.1.2.2 the serial number field on X.509 certificates are allotted 160 bits (20 bytes) maximum.

>  Given the uniqueness requirements above, serial numbers can be
>  expected to contain long integers.  Certificate users MUST be able to
>  handle serialNumber values up to 20 octets.  Conforming CAs MUST NOT
>  use serialNumber values longer than 20 octets.

Current link:https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.4.pdf[CA/BF Baseline Requirements] section 7.1 place this at 64 bits (8 bytes) of entropy.

>  CAs SHALL generate non‐sequential Certificate serial numbers greater
>  than zero (0) containing at least 64 bits of output from a CSPRNG.

Other requirements are at least 20 bits.

== Benefits ==

No risk of serial number range replication conflicts: these would be ignored, support would be removed from the code, and eventually removed from the DS instance as well. This also includes removal of RSNv1 support.

Low risk of collision: collision would have to occur prior to replication on distributed ranges. This would occur with instantaneous probability `$num_replicas / 2**$bits_entropy`. However, we also have to contend with other certificates issued by replicas that haven't yet replicated. This roughly translates to `$num_replicas * $avg_rate_of_issuance * $replication_delay`. IPA caps replications at 50, so this should always be sufficiently small with 128 bits of entropy: 10^-26 given 50 replicas, 1000 certs/sec, and a year of replication delay -- about 11PB of data assuming 8k/cert. (Note that due to our DN structure in LDAP, we are prevented from issuing certificates with duplicate serial numbers by LDAP outside of the aforementioned replication conflict zone. Only certificates which haven't yet been replicated across the entire environment are subject to collisions.)

Easy to generate: pull from `SecureRandom`, put into serial number field. Stateless. Helps with containerization efforts. (Doesn't rely on replica id like serial number ranges do).

Above current standards: 128-bits exceeds the random size most CAs currently issue with. Since CA/BF targets 64-bits of entropy and we push that to 128-bits, we likely meet their next target for doubling. Above this, since the field is limited to 160-bits, it is unlikely to have another doubling without further modifications to other RFCs. By leaving the remaining 32 bits, if there's a need to change serial number issuance in the future, we just need to ensure it is consistently over 128-bits (but still within the allotted 160 bits).

By removing incremental and RSNv1 formats, we can simplify the code and database significantly.

== Risks ==

To our knowledge, nobody (between IPA and customers) is dependent on the current serial number mechanism. Additionally, we've already had RSNv1 implemented for a while, so any external systems should theoretically be able to support either.

As discussed above, it is unlikely that collision poses a viable risk except when replication fails for an extended period of time.

Also, not mentioned above, there's a risk of colliding with existing serial numbers from earlier schemes. Assuming the same rate of issuance and same number of replicas above, but issuing for 10 years prior, this produces a collision risk of 10^-25. However, the likelihood of anyone reaching this is low as that's ~114PB of data using above 8k/cert assumption.

If existing logic exists for retrying issuance under a different serial number, it should be left in place. However, the likelihood of colliding with an existing certificate is sufficiently low not to warrant adding retry logic, in my opinion.

= Older Proposals =

See link:UUID-based-Random-Certificate-Serial-Numbers[UUID-based Random Certificate Serial Numbers].

= See Also =

* link:https://www.ietf.org/rfc/rfc4122.txt[RFC 4122: A Universally Unique IDentifier (UUID) URN Namespace]
* link:https://access.redhat.com/documentation/en-us/red_hat_directory_server/11/html/administration_guide/managing_replication-solving_common_replication_conflicts[RHDS 11: Solving Common Replication Conflicts]
