= Overview =

This page describes the process to rebase (as opposed to patching) a package on Fedora.

As an example, we'll try to rebase the `dogtag-pki` package on Fedora 35 to upstream PKI 11.0.0-beta1.

= Prerequisites =

Get the following information from link:Fedora-Packages[Fedora Packages] (i.e. link:Fedora-35-Packages[Fedora 35 Packages]) page:

* Upstream project repository and branch/tag (i.e. link:https://github.com/dogtagpki/pki/tree/master[pki/master])
* Package dist-git repository and branch (i.e. link:https://src.fedoraproject.org/rpms/dogtag-pki/tree/f35[dogtag-pki/f35])

= Authentication =

Make sure you have a Kerberos ticket:

```
$ kinit <username>@FEDORAPROJECT.ORG
```

= Getting the Sources =

Clone the above repositories into the local machine:

* Upstream project repository (i.e. `git clone https://github.com/dogtagpki/pki.git`)
* Package dist-git repository (i.e. `fedpkg clone dogtag-pki Fedora/dogtag-pki`)

You can reuse existing repositories on your local machine if they are already checked out. It's not necessary to clone new ones every time.

= Updating Upstream Version Number =

First, make sure the upstream project branch has a new version number to rebase to.

According to the link:Fedora-35-Packages[Fedora 35 Packages] page the upstream source for `dogtag-pki` package can be obtained from link:https://github.com/dogtagpki/jss/tree/master[master] branch in upstream `pki` project repository.

In the local upstream repository check out the upstream branch/tag (i.e. `master`):

```
$ git checkout master
$ git pull
```

Make sure the version/release number in the spec file (i.e. `pki.spec`) is higher than the latest one in link:https://koji.fedoraproject.org/koji/packageinfo?packageID=9999[Koji], for example:

```
Version:          11.0.0
Release:          0.4.beta1%{?_timestamp}%{?_commit_id}%{?dist}
```

Commit the change:

```
$ git commit -a -m "Update version number to 11.0.0-beta1"
$ git push origin master
```

Then create a tag with the new version number:

```
$ git tag v11.0.0-beta1
```

*Notes:*

* Do not include the release number since this is an upstream tag.
* Do not push the tag to origin just yet in case it needs to be redone.

# Creating a Source Tarball

Create a source tarball with the new tag:

```
$ ./build.sh --source-tag=v11.0.0-beta1 src
```

In this case the source tarball will be stored in `pki-11.0.0-beta1.tar.gz`.

= Adding the Source Tarball =

According to the link:Fedora-35-Packages[Fedora 35 Packages] page the packaging source for `pki` package can be obtained from the link:https://src.fedoraproject.org/rpms/dogtag-pki/tree/f35[f35] branch in `dogtag-pki` package dist-git repository.

In the local dist-git repository check out the dist-git branch:

```
$ git checkout f35
$ git pull
```

Import the tarball into dist-git with this command:

```
$ fedpkg new-sources <path to>/pki-11.0.0-beta1.tar.gz
```

= Merge the Spec Files =

Next, merge the upstream spec file into the dist-git spec file.

Use a merging tool such as `meld` to merge the files, for example:

```
$ meld <upstream>/pki.spec <dist-git>/dogtag-pki.spec
```

In general most changes in upstream spec file should be merged into dist-git spec file,
and most changes in dist-git spec file should be removed.
If there are dist-git changes that cannot be removed, try to merge and commit it upstream if possible.
Ideally the files should become identical except for platform specific macros, patch files, and change logs.

= Remove Unused Patch Files =

Next, remove any patch files that are already included in the upstream branch from dist-git spec file:

```
Patch1: <filename>
```

Also remove the patch files from dist-git:

```
$ git rm <filename>
```

= Adding a Change Log =

Add a change log entry to describe the bug being fixed.

Find the following line in the spec file:

```
%changelog
```

Add the new entry (newest log at the top):

```
* Fri Sep 03 2021 Dogtag PKI Team <devel@lists.dogtagpki.org> - 11.0.0-0.4.beta1
- Rebase to PKI 11.0.0-beta1
```

= Testing Dist-Git Changes =

Next, make sure the changes do not break anything.

Run the following command in the local dist-git repository:

```
$ fedpkg prep
```

= Committing Dist-Git Changes =

Commit the changes to dist-git repository with the following commands:

```
$ git add dogtag-pki.spec
$ git commit
```

Enter a short (i.e. one line) summary:

```
Rebase to PKI 11.0.0-beta1
```

= Pushing Dist-Git Changes =

Push the changes to dist-git repository:

```
$ git push origin f35
```

= Starting the Build =

Before starting the build, make sure any dependencies that have been built but not yet released are added into the BuildRoot, for example:

```
$ bodhi overrides save jss-5.0.0-1.fc35
$ koji wait-repo f35-build --build=jss-5.0.0-1.fc35
```

Then start the build with the following command:

```
$ fedpkg build
```

If there's a problem with the build, fix it in the upstream branch and start over, or add a patch.

= Pushing Upstream Tag =

If everything went well, push the upstream tag to origin:

```
$ git push origin v11.0.0-beta1
```

= Creating Bodhi Update =

To actually release the build in Fedora, create a Bodhi update so the package will be included in Fedora testing repository, for example:

```
$ bodhi updates new \
   --request=testing \
   --type=enhancement \
   --notes="Update to PKI 11.0.0-0.4.beta1" \
dogtag-pki-11.0.0-0.4.beta1.fc35
```

Once the update receives enough Karma points, it will be released into Fedora stable repository.

*Note:* This is required for all Fedora versions except Rawhide.

= See Also =

* link:https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning[Fedora Versioning Guidelines]
