= Overview =

This page describes the procedure to renew system certificates used by PKI server.

Depending on the subsystems installed, PKI server uses several system certificates, for example:

* CA signing certificate
* OCSP signing certificate
* SSL server certificate
* Subsystem certificate
* Audit signing certificate

In order for the server to operate properly all of these certificates must be valid. The CA signing certificate usually has the longest validity range (default is 20 years). The other certificates usually have shorter validity range (e.g. 2 years). To avoid service interruption any expiring certificate should be renewed while it's still valid.

Note that the default PKI user certificate also has a shorter validity range.

Also note that the renewal procedure requires a running CA. If the expired system certificate was issued by a CA running on the same server, the server might fail to start and the certificate cannot be renewed since the CA is not available. If that happens, the system date needs to be moved back to a time where all system certificates were still valid before starting the renewal process.

This document describes the renewal procedure using CLI in PKI 10.x. In PKI 9.x the renewal procedure needs to be done using legacy servlet interface, but it still follows the same general idea.

= Checking Current Certificates =

First, identify the serial numbers of the certificates that are about to expire. This can be done with the following command:

----
$ pki-server subsystem-cert-find ca
-----------------
5 entries matched
-----------------
  Cert ID: signing
  Nickname: ca_signing
  Token: Internal Key Storage Token
  Serial number: 0x1
  Issuer: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Subject: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Not valid before: 2016-12-06 12:49:43
  Not valid after: 2036-12-06 12:49:43

  Cert ID: ocsp_signing
  Nickname: ca_ocsp_signing
  Token: Internal Key Storage Token
  Serial number: 0x2
  Issuer: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Subject: CN=CA OCSP Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Not valid before: 2016-12-06 12:49:43
  Not valid after: 2018-11-26 12:49:43

  Cert ID: sslserver
  Nickname: sslserver
  Token: Internal Key Storage Token
  Serial number: 0x3
  Issuer: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Subject: CN=vm-058-091.abc.idm.lab.eng.brq.redhat.com, OU=pki-tomcat, O=EXAMPLE
  Not valid before: 2016-12-06 12:49:44
  Not valid after: 2018-11-26 12:49:44

  Cert ID: subsystem
  Nickname: subsystem
  Token: Internal Key Storage Token
  Serial number: 0x4
  Issuer: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Subject: CN=Subsystem Certificate, OU=pki-tomcat, O=EXAMPLE
  Not valid before: 2016-12-06 12:49:44
  Not valid after: 2018-11-26 12:49:44

  Cert ID: audit_signing
  Nickname: ca_audit_signing
  Token: Internal Key Storage Token
  Serial number: 0x5
  Issuer: CN=CA Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Subject: CN=CA Audit Signing Certificate, OU=pki-tomcat, O=EXAMPLE
  Not valid before: 2016-12-06 12:49:44
  Not valid after: 2018-11-26 12:49:44
----

For PKI 10.3 or earlier, see link:PKI-10.3-Identifying-Certificates-to-Renew[PKI 10.3 Identifying Certificates to Renew].

= Renewing SSL Server Certificate =

If the SSL server certificate used by the CA service has already expired, it needs to be renewed first before renewing other certificates.
See link:Renewing-SSL-Server-Certificate[Renewing SSL Server Certificate].

= Renewing Other Certificates =

== Submitting Renewal Requests ==

For each expiring system certificate, submit a renewal request using the serial number.
Each renewal request will generate a request ID.
This can be done with the following commands:

----
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x2  --renewal  # OCSP signing
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x4  --renewal  # subsystem
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x5  --renewal  # audit signing
----

For PKI 10.3 or earlier, see link:PKI-10.3-Submitting-Renewal-Requests[PKI 10.3 Submitting Renewal Requests].

See also link:Submitting-Certificate-Renewal-Request[Submitting Certificate Renewal Request].

== Approving Renewal Requests ==

As the CA agent, approve each renewal request using the request ID:

----
$ pki -n caadmin -c Secret.123 ca-cert-request-review 8 --action approve
$ pki -n caadmin -c Secret.123 ca-cert-request-review 9 --action approve
$ pki -n caadmin -c Secret.123 ca-cert-request-review 10 --action approve
----

Each approval will generate a new certificate with a new serial number.

See also link:Handling-Certificate-Request[Handling Certificate Request].

== Retrieving New Certificates ==

Download the renewed certificates into files using the new serial numbers:

----
$ pki ca-cert-show 0x8 --output ca_ocsp_signing.crt
$ pki ca-cert-show 0x9 --output subsystem.crt
$ pki ca-cert-show 0xa --output ca_audit_signing.crt
----

See also link:Retrieving-Certificate[Retrieving Certificate].

== Installing New Certificates ==

The new certificates need to be imported into the NSS database and the copy of the certificates in the CS.cfg need to be updated as well. While NSS should be able to handle multiple certificates (both old and new) in the NSS database it is recommended that the old one is removed. To prevent NSS database or CS.cfg corruption, shutdown the server before making the changes.

First, shutdown the server:

----
$ systemctl stop pki-tomcatd@pki-tomcat.service
----

Update the NSS database and CS.cfg with the following commands:

----
$ pki-server subsystem-cert-update ca ocsp_signing --cert ca_ocsp_signing.crt
$ pki-server subsystem-cert-update ca subsystem --cert subsystem.crt
$ pki-server subsystem-cert-update ca audit_signing --cert ca_audit_signing.crt
----

Finally, restart the server:

----
$ pki-server restart --wait
----

For PKI 10.3 or earlier, see link:PKI-10.3-Updating-System-Certificates[PKI 10.3 Updating System Certificates].
