= Overview =

This page describes the process to renew an SSL server certificate used by a PKI server instance.

For an instance that has a CA, if the current SSL server certificate used by the instance has already expired, the server itself might not start or might not be accessible, so the CA cannot be used to renew certificates including the expired SSL server certificate itself. In this case create a temporary (short-lived) SSL server certificate to restore the CA, then use the CA to create the permanent certificate.

For an instance that does not have a CA, use the CA (on another instance) to create a new permanent SSL server certificate.

= Checking Current Certificate =

To check the current SSL server certificate:

----
$ pki-server cert-show sslserver
  Cert ID: sslserver
  Nickname: sslserver
  Token: internal
  Serial Number: 0x235131ac57d6dc14706338af68fce2b6
  Subject DN: CN=pki.example.com,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: Wed Oct 25 15:39:35 2023
  Not Valid After: Tue Oct 14 15:39:35 2025
  Trust Flags: u,u,u
----

= Creating Temporary SSL Server Certificate =

To create a temporary SSL server certificate execute the following command:

----
$ pki-server cert-create sslserver --temp
----

The certificate will be stored in `/etc/pki/<instance>/certs/sslserver.crt`.

Next, delete the current SSL server certificate in PKI server's NSS database:

----
$ pki-server cert-del sslserver
----

Then import the temporary certificate into the NSS database:

----
$ pki-server cert-import sslserver
----

If the CA has other expired system certificates, disable the selftests temporarily before restarting the server:

----
$ pki-server selftest-disable
----

Finally, restart the server with the temporary certificate:

----
$ pki-server restart --wait
----

= Creating Permanent SSL Server Certificate =

To create a permanent certificate, submit a renewal request to the CA by executing the following command:

----
$ pki ca-cert-request-submit \
    --profile caManualRenewal \
    --serial 0x235131ac57d6dc14706338af68fce2b6 \
    --renewal
-----------------------------
Submitted certificate request
-----------------------------
  Request ID: 0x139860c571ad8a59dc5375fe344f5432
  Type: renewal
  Request Status: pending
  Operation Result: success
  Creation Time: Thu Oct 26 17:28:13 CDT 2023
  Modification Time: Thu Oct 26 17:28:13 CDT 2023
----

Next, as a CA agent approve the renewal request:

----
$ pki <CA agent authentication> ca-cert-request-approve 0x139860c571ad8a59dc5375fe344f5432 --force
---------------------------------------------------------------
Approved certificate request 0x139860c571ad8a59dc5375fe344f5432
---------------------------------------------------------------
  Request ID: 0x139860c571ad8a59dc5375fe344f5432
  Type: renewal
  Request Status: complete
  Operation Result: success
  Certificate ID: 0x4e62aba6ad321857fcc93c20be4ee4c5
  Creation Time: Thu Oct 26 17:28:13 CDT 2023
  Modification Time: Thu Oct 26 17:29:56 CDT 2023
----

The CA agent can authenticate using a client certificate or a username and password.
If necessary, the password can be link:Resetting-User-Password[reset] by the system administrator.

Next, retrieve the new certificate from the CA:

----
$ pki ca-cert-export 0x4e62aba6ad321857fcc93c20be4ee4c5 --output-file sslserver.crt
----

Delete the current/temporary certificate from PKI server's NSS database:

----
$ pki-server cert-del sslserver
----

Then import the new certificate into the NSS database:

----
$ pki-server cert-import sslserver --import sslserver.crt
----

Check the new certificate with the following command:

----
$ pki-server cert-show sslserver
  Cert ID: sslserver
  Nickname: sslserver
  Token: internal
  Serial Number: 0x4e62aba6ad321857fcc93c20be4ee4c5
  Subject DN: CN=pki.example.com,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: Thu Oct 26 17:28:13 2023
  Not Valid After: Wed Oct 15 17:28:13 2025
  Trust Flags: u,u,u
----

If the CA has no more expired system certificates, restore the selftests with the following command before restarting the server:

----
$ pki-server selftest-enable
----

Finally, restart the server with the following command:

----
$ pki-server restart --wait
----
