= Overview =

This page describes the process to renew an SSL server certificate used by PKI server.

= Checking Current Certificate =

To check the current SSL server certificate:

----
$ pki-server cert-show sslserver
  Cert ID: sslserver
  Nickname: sslserver
  Token: internal
  Serial Number: 0x235131ac57d6dc14706338af68fce2b6
  Subject DN: CN=fedora,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: Wed Oct 25 15:39:35 2023
  Not Valid After: Tue Oct 14 15:39:35 2025
  Trust Flags: u,u,u
----

= Online Renewal Procedure =
 
The online renewal procedure can be used if the SSL server certificate used by the CA service is still valid, so the CA service can be used to issue a new SSL certificate for the CA service itself or for other PKI services.

First, submit a renewal request:

----
$ pki ca-cert-request-submit \
    --profile caManualRenewal \
    --serial 0x235131ac57d6dc14706338af68fce2b6 \
    --renewal
-----------------------------
Submitted certificate request
-----------------------------
  Request ID: 0x139860c571ad8a59dc5375fe344f5432
  Type: renewal
  Request Status: pending
  Operation Result: success
  Creation Time: Thu Oct 26 17:28:13 CDT 2023
  Modification Time: Thu Oct 26 17:28:13 CDT 2023
----

Next, approve the renewal request:

----
$ pki -n caadmin ca-cert-request-approve 0x139860c571ad8a59dc5375fe344f5432
---------------------------------------------------------------
Approved certificate request 0x139860c571ad8a59dc5375fe344f5432
---------------------------------------------------------------
  Request ID: 0x139860c571ad8a59dc5375fe344f5432
  Type: renewal
  Request Status: complete
  Operation Result: success
  Certificate ID: 0x4e62aba6ad321857fcc93c20be4ee4c5
  Creation Time: Thu Oct 26 17:28:13 CDT 2023
  Modification Time: Thu Oct 26 17:29:56 CDT 2023
----

Retrieve the new SSL server certificate:

----
$ pki ca-cert-export 0x4e62aba6ad321857fcc93c20be4ee4c5 --output sslserver.crt
----

Then install the new SSL server certificate:

----
$ pki-server subsystem-cert-update ca sslserver --cert sslserver.crt
----

Finally, restart PKI server in order to use the new certificate:

----
$ pki-server restart --wait
----

Check the new SSL server certificate:

----
$ pki-server cert-show sslserver
  Cert ID: sslserver
  Nickname: sslserver
  Token: internal
  Serial Number: 0x4e62aba6ad321857fcc93c20be4ee4c5
  Subject DN: CN=fedora,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: Thu Oct 26 17:28:13 2023
  Not Valid After: Wed Oct 15 17:28:13 2025
  Trust Flags: u,u,u
----

= Offline Renewal Procedure =

The offline renewal procedure needs to be used if the current SSL server certificate used by the CA service has already expired so the service might not be accessible anymore.

Use this procedure to create a temporary SSL server certificate (which will be short-lived and not stored in CA database) to restore the CA service, then use the online renewal procedure to create the permanent certificate.

First, create a temporary SSL server certificate which will be stored in `/etc/pki/<instance>/certs/sslserver.crt`.

----
$ pki-server cert-create sslserver --temp
----

Next, delete the current SSL server certificate in PKI server's NSS database:

----
$ pki-server cert-del sslserver
----

Then import the temporary certificate into the NSS database:

----
$ pki-server cert-import sslserver
----

Finally, restart PKI server in order to use the temporary certificate:

----
$ pki-server restart --wait
----

Follow the online renewal procedure to create the permanent certificate.
