= Overview =

This page describes the procedure to renew system certificates used by PKI server.

Depending on the subsystems installed, PKI server uses several system certificates, for example:

* CA signing certificate
* OCSP signing certificate
* SSL server certificate
* Subsystem certificate
* Audit signing certificate

In order for the server to operate properly all of these certificates must be valid. The CA signing certificate usually has the longest validity range (default is 20 years). The other certificates usually have shorter validity range (e.g. 2 years). To avoid service interruption any expiring certificate should be renewed while it's still valid.

Note that the default PKI user certificate also has a shorter validity range.

Also note that the renewal procedure requires a running CA. If the expired system certificate was issued by a CA running on the same server, the server might fail to start and the certificate cannot be renewed since the CA is not available. If that happens, the system date needs to be moved back to a time where all system certificates were still valid before starting the renewal process.

This document describes the renewal procedure using CLI in PKI 10.x. In PKI 9.x the renewal procedure needs to be done using legacy servlet interface, but it still follows the same general idea.

= Checking Current Certificates =

First, identify the serial numbers of the certificates that are about to expire. This can be done with the following command:

----
$ pki-server cert-find
  Cert ID: ca_signing
  Nickname: ca_signing
  Token: Internal Key Storage Token
  Serial Number: 0x1
  Subject DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: 2016-12-06 12:49:43
  Not Valid After: 2036-12-06 12:49:43

  Cert ID: ca_ocsp_signing
  Nickname: ca_ocsp_signing
  Token: Internal Key Storage Token
  Serial Number: 0x2
  Subject DN: CN=CA OCSP Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: 2016-12-06 12:49:43
  Not Valid After: 2018-11-26 12:49:43

  Cert ID: sslserver
  Nickname: sslserver
  Token: Internal Key Storage Token
  Serial Number: 0x3
  Subject DN: CN=pki.example.com,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: 2016-12-06 12:49:44
  Not Valid After: 2018-11-26 12:49:44

  Cert ID: subsystem
  Nickname: subsystem
  Token: Internal Key Storage Token
  Serial Number: 0x4
  Subject DN: CN=Subsystem Certificate,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: 2016-12-06 12:49:44
  Not Valid After: 2018-11-26 12:49:44

  Cert ID: ca_audit_signing
  Nickname: ca_audit_signing
  Token: Internal Key Storage Token
  Serial Number: 0x5
  Subject DN: CN=CA Audit Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Issuer DN: CN=CA Signing Certificate,OU=pki-tomcat,O=EXAMPLE
  Not Valid Before: 2016-12-06 12:49:44
  Not Valid After: 2018-11-26 12:49:44
----

For PKI 10.3 or earlier, see link:PKI-10.3-Identifying-Certificates-to-Renew[PKI 10.3 Identifying Certificates to Renew].

= Renewing SSL Server Certificate =

If the SSL server certificate used by the CA service has already expired, it needs to be renewed first before renewing other certificates.
See link:Renewing-SSL-Server-Certificate-Manually[Renewing SSL Server Certificate Manually].

= Renewing Other Certificates =

== Submitting Renewal Requests ==

For each expiring system certificate, submit a renewal request using the serial number.
Each renewal request will generate a request ID.
This can be done with the following commands:

----
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x2  --renewal  # OCSP signing
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x4  --renewal  # subsystem
$ pki ca-cert-request-submit --profile caManualRenewal --serial 0x5  --renewal  # audit signing
----

For PKI 10.3 or earlier, see link:PKI-10.3-Submitting-Renewal-Requests[PKI 10.3 Submitting Renewal Requests].

See also link:Submitting-Certificate-Renewal-Request[Submitting Certificate Renewal Request].

== Approving Renewal Requests ==

As the CA agent, approve each renewal request using the request ID:

----
$ pki -n caadmin ca-cert-request-review 8 --action approve
$ pki -n caadmin ca-cert-request-review 9 --action approve
$ pki -n caadmin ca-cert-request-review 10 --action approve
----

Each approval will generate a new certificate with a new serial number.

See also link:Handling-Certificate-Request[Handling Certificate Request].

== Retrieving New Certificates ==

Retrieve the renewed certificates into files using the new serial numbers:

----
$ pki ca-cert-export 0x8 --output-file ca_ocsp_signing.crt
$ pki ca-cert-export 0x9 --output-file subsystem.crt
$ pki ca-cert-export 0xa --output-file ca_audit_signing.crt
----

See also link:Retrieving-Certificate[Retrieving Certificate].

== Installing New Certificates ==

Remove the current certificates with the following commands:

----
$ pki-server cert-del ca_ocsp_signing
$ pki-server cert-del subsystem
$ pki-server cert-del ca_audit_signing
----

Import the new certificates with the following commands:

----
$ pki-server cert-import ca_ocsp_signing --input ca_ocsp_signing.crt
$ pki-server cert-import subsystem --input subsystem.crt
$ pki-server cert-import ca_audit_signing --input ca_audit_signing.crt
----

Finally, restart the server:

----
$ pki-server restart --wait
----

For PKI 10.3 or earlier, see link:PKI-10.3-Updating-System-Certificates[PKI 10.3 Updating System Certificates].
