= Overview =

WARNING: This document is still under construction.

This document describes several procedures to renew PKI admin certificate.

= Using CMSGateway =

NOTE: This procedure may require using Firefox earlier than version 69 that still supports `<keygen>`.

To renew the admin certificate using CMSGateway, configure the following parameter in `/etc/pki/pki-tomcat/ca/CS.cfg`:

----
cmsgateway.enableAdminEnroll=true
----

Restart the server, then follow the procedure at https://localhost.localdomain:8443/ca/admin/ca/adminEnroll.html.

= Using pki-server cert-fix =

NOTE: This procedure may require setting the system clock back to when the admin certificate was still valid.

To renew the admin certificate and system certificates, execute the following command and provide the admin certificate serial number:

----
$ pki-server cert-fix \
    --ldap-url ldap://localhost.localdomain \
    --agent-uid caadmin \
    --extra-cert <serial number>
----

If the DS connection was configured to use client certificate authentication, but the certificate has already expired, and the DS server is running locally, the command can be executed with LDAPI instead:

----
$ pki-server cert-fix \
    --ldapi-socket /var/run/slapd-localhost.socket \
    --agent-uid caadmin \
    --extra-cert <serial number>
----

Then assign the new certificate to the admin user with the following command:

----
$ pki \
    -U https://localhost.localdomain:8443 \
    -d ~/.dogtag/nssdb \
    -c Secret.123 \
    -n caadmin \
    ca-user-cert-add \
    --input /etc/pki/pki-tomcat/certs/<serial number>-renewed.crt \
    caadmin
----

= Using pki nss CLI =

NOTE: This procedure requires RSNv3. Available since PKI 11.5.

Generate a new admin key and certificate request:

----
$ pki nss-cert-request \
    --subject "CN=Administrator" \
    --ext /usr/share/pki/server/certs/admin.conf \
    --csr admin.csr
----

Issue a new admin certificate using the existing CA signing certificate:

----
$ pki \
    -d /etc/pki/pki-tomcat/alias \
    -f /etc/pki/pki-tomcat/password.conf \
    nss-cert-issue \
    --issuer ca_signing \
    --csr admin.csr \
    --ext /usr/share/pki/server/certs/admin.conf \
    --cert admin.crt
----

Import the new admin certificate:

----
$ pki nss-cert-import admin --cert admin.crt
----

Find the existing admin certificate in the admin user record:

----
$ pki-server ca-user-cert-find caadmin
----

Remove the existing admin certificate from the admin user record:

----
$ pki-server ca-user-cert-del caadmin <cert ID>
----

Import the new admin certificate to the admin user record:

----
$ cat admin.crt | pki-server ca-user-cert-add caadmin
----

= See Also =

* link:https://github.com/dogtagpki/pki/blob/master/docs/admin/Offline_System_Certificate_Renewal.md[Offline System Certificate Renewal]
