= Installation =

To install Eclipse on Fedora:

----
$ dnf install eclipse-jdt
----

It will add an icon in the desktop's *Favorites*.

= Starting Eclipse =

To start Eclipse, click the *Eclipse* icon in the desktop's Favorites or execute the following command:

----
$ eclipse
----

It may ask you to select a workspace to store project metadata.

= Adding a Java Project =

To add the Java project into Eclipse, first clone the project into a local repository, for example:

----
$ git clone git@github.com:dogtagpki/pki.git
----

Install the build dependencies, for example:

----
$ dnf builddep pki-core
----

Then execute the following steps in Eclipse:

* Click *File* -> *New* -> *Java Project*.
* Enter the *Project name*, e.g. `pki`.
* Uncheck *Use default location*.
* In *Location* enter the path to the cloned project repository, e.g. `/home/<username>/Projects/pki`.
* Click *Finish*.

If the project already has the `.project` and `.classpath` files in the project's main folder, the project build path is already set up so Eclipse can build the code automatically, and there should be no errors. The project can be used immediately.

If the project doesn't have the `.project` and `.classpath` files, it may be necessary to configure the project build path manually before the project can be used.

= Switching Branch =

To switch to a different branch, execute the following command:

----
$ git checkout <branch>
----

In Eclipse right-click on the project, then select *Refresh*.

= Troubleshooting =

== Eclipse Keeps Crashing ==

If Eclipse keeps crashing on start, try removing the `~/.eclipse` folder. It's not necessary to remove the workspace folder.

== Missing JRE System Library ==

The following error message may appear after upgrading Java:

----
The container 'JRE System Library [...]' references non existing library '...'
----

To fix the problem, try restarting Eclipse.

If the problem persists, try the following steps:

* Right-click on the project and open *Properties*.
* Select *Java Build Path* -> *Libraries*.
* Select *JRE System Library*.
* Click *Remove*.
* Click *Add Library...*.
* Select *JRE System Library*.
* Select *Workspace default JRE*.
* Click *Finish*.
* Click *Apply and Close*.

= See Also =

* link:https://www.eclipse.org/mat[Eclipse Memory Analyzer]
