= Overview =

This page describes audit events that are common in all PKI subsystems. The complete list of events, the message format, and the event description are stored in link:https://github.com/dogtagpki/pki/blob/master/base/server/cmsbundle/src/audit-events.properties[audit-events.properties].

Subsystem-specific audit events are described in the following pages:

* link:https://github.com/dogtagpki/pki/wiki/CA-Audit-Events[CA Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/KRA-Audit-Events[KRA Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/OCSP-Audit-Events[OCSP Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/TKS-Audit-Events[TKS Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/TPS-Audit-Events[TPS Audit Events]

See also link:https://www.dogtagpki.org/wiki/PKI_Server_Audit_Events_Design[PKI Server Audit Events Design].

= Authentication Events =

== AUTH_SUCCESS ==

See link:AUTH_SUCCESS-Audit-Event[AUTH_SUCCESS Audit Event].

== AUTH_FAIL ==

See link:AUTH_FAIL-Audit-Event[AUTH_FAIL Audit Event].

== AUTH ==

See link:AUTH-Audit-Event[AUTH Audit Event].

= Authorization Events =

== AUTHZ_SUCCESS ==

See link:AUTHZ_SUCCESS-Audit-Event[AUTHZ_SUCCESS Audit Event].

== AUTHZ_FAIL ==

See link:AUTHZ_FAIL-Audit-Event[AUTHZ_FAIL Audit Event].

== AUTHZ ==

See link:AUTHZ-Audit-Event[AUTHZ Audit Event].

== ROLE_ASSUME ==

See link:ROLE_ASSUME-Audit-Event[ROLE_ASSUME Audit Event].

= Configuration Events =

== CONFIG_AUTH ==

See link:CONFIG_AUTH-Audit-Event[CONFIG_AUTH Audit Event].

== CONFIG_ROLE ==

See link:CONFIG_ROLE-Audit-Event[CONFIG_ROLE Audit Event].

== CONFIG_SIGNED_AUDIT ==

See link:CONFIG_SIGNED_AUDIT-Audit-Event[CONFIG_SIGNED_AUDIT Audit Event].

== CONFIG_TRUSTED_PUBLIC_KEY ==

See link:CONFIG_TRUSTED_PUBLIC_KEY-Audit-Event[CONFIG_TRUSTED_PUBLIC_KEY Audit Event].

= Access Session Events =

== ACCESS_SESSION_ESTABLISH_SUCCESS ==

See link:ACCESS_SESSION_ESTABLISH_SUCCESS-Audit-Event[ACCESS_SESSION_ESTABLISH_SUCCESS Audit Event].

== ACCESS_SESSION_ESTABLISH_FAILURE ==

See link:ACCESS_SESSION_ESTABLISH_FAILURE-Audit-Event[ACCESS_SESSION_ESTABLISH_FAILURE Audit Event].

== ACCESS_SESSION_ESTABLISH ==

See link:ACCESS_SESSION_ESTABLISH-Audit-Event[ACCESS_SESSION_ESTABLISH Audit Event].

== ACCESS_SESSION_TERMINATED ==

See link:ACCESS_SESSION_TERMINATED-Audit-Event[ACCESS_SESSION_TERMINATED Audit Event].

= Outbound Connection Events =

== OUTBOUND_CONNECTION_ESTABLISH ==

== OUTBOUND_CONNECTION_TERMINATED ==

= Random Number Generator Events =

== RANDOM_GENERATION ==

See link:RANDOM_GENERATION-Audit-Event[RANDOM_GENERATION Audit Event].

= See Also =

* link:Configuring-Signed-Audit[Configuring Signed Audit]
* link:Signed-Audit-Event-Filters[Signed Audit Event Filters]
