= Overview =

This page describes audit events that are common in all PKI subsystems. The complete list of events, the message format, and the event description are stored in link:https://github.com/dogtagpki/pki/blob/master/base/server/cmsbundle/src/audit-events.properties[audit-events.properties].

Subsystem-specific audit events are described in the following pages:

* link:https://github.com/dogtagpki/pki/wiki/CA-Audit-Events[CA Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/KRA-Audit-Events[KRA Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/OCSP-Audit-Events[OCSP Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/TKS-Audit-Events[TKS Audit Events]
* link:https://github.com/dogtagpki/pki/wiki/TPS-Audit-Events[TPS Audit Events]

See also link:https://www.dogtagpki.org/wiki/PKI_Server_Audit_Events_Design[PKI Server Audit Events Design].

= Authentication Events =

== AUTH_SUCCESS ==

See link:AUTH_SUCCESS-Audit-Event[AUTH_SUCCESS Audit Event].

== AUTH_FAIL ==

See link:AUTH_FAIL-Audit-Event[AUTH_FAIL Audit Event].

== AUTH ==

See link:AUTH-Audit-Event[AUTH Audit Event].

= Authorization Events =

== AUTHZ_SUCCESS ==

This event is triggered when authorization is successful.

Properties:

* `Outcome` must be `Success` for this event
* `aclResource` must be the ACL resource ID as defined in ACL resource list
* `Op` must be one of the operations as defined with the ACL statement, e.g. `read` for an ACL statement containing `(read,write)`

For example, use CLI to authenticate as admin user:

----
$ pki -n caadmin ca-user-find
----

The server will generate the following logs:

----
[AuditEvent=ACCESS_SESSION_ESTABLISH_SUCCESS][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success] access session establish success
[AuditEvent=AUTH_SUCCESS][SubjectID=caadmin][Outcome=Success][AuthMgr=certUserDBAuthMgr] authentication success
[AuditEvent=AUTHZ_SUCCESS][SubjectID=caadmin][Outcome=Success][aclResource=certServer.ca.account][Op=login][Info=AccountResource.login] authorization success
[AuditEvent=ACCESS_SESSION_TERMINATED][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success][Info=CLOSE_NOTIFY] access session terminated
[AuditEvent=ACCESS_SESSION_ESTABLISH_SUCCESS][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success] access session establish success
[AuditEvent=AUTHZ_SUCCESS][SubjectID=caadmin][Outcome=Success][aclResource=certServer.ca.users][Op=execute][Info=UserResource.findUsers] authorization success
[AuditEvent=ACCESS_SESSION_TERMINATED][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success][Info=CLOSE_NOTIFY] access session terminated
[AuditEvent=ACCESS_SESSION_ESTABLISH_SUCCESS][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success] access session establish success
[AuditEvent=AUTHZ_SUCCESS][SubjectID=caadmin][Outcome=Success][aclResource=certServer.ca.account][Op=logout][Info=AccountResource.logout] authorization success
[AuditEvent=ACCESS_SESSION_TERMINATED][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success][Info=CLOSE_NOTIFY] access session terminated
----

In PKI 10.5 this event is renamed to `AUTHZ`.

== AUTHZ_FAIL ==

This event is triggered when authorization has failed.

Properties:

* `Outcome` must be `Failure` for this event
* `aclResource` must be the ACL resource ID as defined in ACL resource list
* `Op` must be one of the operations as defined with the ACL statement, e.g. `read` for an ACL statement containing `(read,write)`

For example, execute the following command:

----
$ pki -n caadmin ca-audit-file-find
----

The server will generate the following logs:

----
[AuditEvent=ACCESS_SESSION_ESTABLISH_SUCCESS][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success] access session establish success
[AuditEvent=AUTH_SUCCESS][SubjectID=caadmin][Outcome=Success][AuthMgr=certUserDBAuthMgr] authentication success
[AuditEvent=AUTHZ_SUCCESS][SubjectID=caadmin][Outcome=Success][aclResource=certServer.ca.account][Op=login][Info=AccountResource.login] authorization success
[AuditEvent=ACCESS_SESSION_TERMINATED][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success][Info=CLOSE_NOTIFY] access session terminated
[AuditEvent=ACCESS_SESSION_ESTABLISH_SUCCESS][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success] access session establish success
[AuditEvent=AUTHZ_FAIL][SubjectID=caadmin][Outcome=Failure][aclResource=certServer.log.content.signedAudit][Op=read][Info=Authorization Error] authorization failure
[AuditEvent=ACCESS_SESSION_TERMINATED][ClientIP=10.34.78.30][ServerIP=10.34.78.30][SubjectID=CN=PKI Administrator,E=caadmin@example.com,OU=pki-tomcat,O=EXAMPLE][Outcome=Success][Info=CLOSE_NOTIFY] access session terminated
----

In PKI 10.5 this event is renamed to `AUTHZ`.

== AUTHZ ==

In PKI 10.5 the `AUTHZ_SUCCESS` and `AUTHZ_FAIL` events have been merged into `AUTHZ` event.

== ROLE_ASSUME ==

See link:ROLE_ASSUME-Audit-Event[ROLE_ASSUME Audit Event].

= Configuration Events =

== CONFIG_AUTH ==

See link:CONFIG_AUTH-Audit-Event[CONFIG_AUTH Audit Event].

== CONFIG_ROLE ==

See link:CONFIG_ROLE-Audit-Event[CONFIG_ROLE Audit Event].

== CONFIG_SIGNED_AUDIT ==

See link:CONFIG_SIGNED_AUDIT-Audit-Event[CONFIG_SIGNED_AUDIT Audit Event].

== CONFIG_TRUSTED_PUBLIC_KEY ==

See link:CONFIG_TRUSTED_PUBLIC_KEY-Audit-Event[CONFIG_TRUSTED_PUBLIC_KEY Audit Event].

= Access Session Events =

== ACCESS_SESSION_ESTABLISH_SUCCESS ==

See link:ACCESS_SESSION_ESTABLISH_SUCCESS-Audit-Event[ACCESS_SESSION_ESTABLISH_SUCCESS Audit Event].

== ACCESS_SESSION_ESTABLISH_FAILURE ==

See link:ACCESS_SESSION_ESTABLISH_FAILURE-Audit-Event[ACCESS_SESSION_ESTABLISH_FAILURE Audit Event].

== ACCESS_SESSION_ESTABLISH ==

See link:ACCESS_SESSION_ESTABLISH-Audit-Event[ACCESS_SESSION_ESTABLISH Audit Event].

== ACCESS_SESSION_TERMINATED ==

See link:ACCESS_SESSION_TERMINATED-Audit-Event[ACCESS_SESSION_TERMINATED Audit Event].

= Outbound Connection Events =

== OUTBOUND_CONNECTION_ESTABLISH ==

== OUTBOUND_CONNECTION_TERMINATED ==

= Random Number Generator Events =

== RANDOM_GENERATION ==

See link:RANDOM_GENERATION-Audit-Event[RANDOM_GENERATION Audit Event].

= See Also =

* link:Configuring-Signed-Audit[Configuring Signed Audit]
* link:Signed-Audit-Event-Filters[Signed Audit Event Filters]
