= Overview =

Dogtag PKI subsystems such as a Data Recovery Managers (DRMs) and an Online Certificate Status Protocol (OCSP) Managers have always required the presence of a Certificate Authority (CA) to be part of a PKI deployment.

Recently, however, it has been determined that it would be beneficial to be able to allow some of these PKI subsystems (e.g. DRM and OCSP) to be setup as stand-alone systems which do not include a CA in their PKI deployment.

It should be *emphasized* that these stand-alone PKI subsystems are *not* expected to communicate with any other PKI subsystems (with the exception of their clones).

= Associated Bugs and Tickets =

* link:https://github.com/dogtagpki/pki/issues/1237[Ticket #1237: provide option for ca-less drm install]
* link:https://github.com/dogtagpki/pki/issues/1284[Ticket #1284: Review panel for configuration wizard]
* link:https://github.com/dogtagpki/pki/issues/1289[Ticket #1289: Provide option for a stand-alone OCSP Manager]

= Use Cases =

See link:Standalone-Subsystems-Use-Cases[Standalone Subsystems Use Cases].
