= Overview =

The TPS database contains several tables/resources. Each resource consists of attributes. The resources are searchable using a keyword. The keyword will be matched against some predetermined list of attributes. 

For most resources that are stored in LDAP, the search will be done using an LDAP filter generated from the search keyword. One exception is the group member resource since the members being searched are actually stored in the same entry, so the search is done using string comparison. The other resources are stored in TPS configuration file, so the search will also be done using string comparison.

Not all resource attributes are searchable because not all attributes are indexed or contain useful information to search.

Currently it's not possible to search against a specific attribute or do complex filter.

The search keyword must be at least 3 characters long. In the future this restriction will be configurable.

Currently the searchable attributes are fixed, but in the future this will be configurable.

= Tokens =

See link:TPS-Token-Database[TPS Token Database].

= Certificates =

See link:TPS-Certificate-Database[TPS Certificate Database].

= Activities =

See link:TPS-Activity-Database[TPS Activity Database].

= Users =

See link:User-Database[User Database].

= Groups =

See link:Group-Database[Group Database].

= Authentication Sources =

This resource is stored in CS.cfg. Search will be done using a string comparison: `authenticatorID.contains(keyword)`.

* Authenticator ID (searchable)
* Status
* Properties

= Subsystem Connections =

This resource is stored in CS.cfg. Search will be done using a string comparison: `connectionID.contains(keyword)`.

* Connector ID (searchable)
* Status
* Properties

See also link:https://www.dogtagpki.org/wiki/Connector_Database[Connector Database].

= Profiles =

This resource is stored in CS.cfg. Search will be done using a string comparison: `profileID.contains(keyword)`.

* Profile ID (searchable)
* Status
* Properties

= Profile Mappings =

This resource is stored in CS.cfg. Search will be done using a string comparison: `profileMappingID.contains(keyword)`.

* Profile Mapping ID (searchable)
* Status
* Properties

= Self Tests =

This resource is stored in CS.cfg. Search will be done using a string comparison: `selfTestID.contains(keyword)`.

* Self Test ID (searchable)
* Enabled At Startup
* Critical At Startup
* Enabled On Demand
* Critical On Demand
