= Managing Tokens =

== Listing tokens ==

* Click Tokens tab.

== Viewing a token ==

* Click Tokens tab.
* Click the token ID.

== Searching tokens ==

* Click Tokens tab.
* Enter search keyword in Search box.
* Click Enter.

== Adding a token ==

By default tokens are added automatically during format or enrollment operations. To add a token without formatting or enrolling the token:

* Click Tokens tab.
* Click Add.
* Enter Token ID and optionally User ID and Policy.
* Click Save.

== Modify a token ==

* Click Tokens tab.
* Click the token ID.
* Click Edit.
* Make the changes.
* Click Save.

== Deleting tokens ==

* Click Tokens tab.
* Select the checkboxes of the the tokens to be deleted.
* Click Remove.
* Click OK.

== Changing Token Status ==

* Click Tokens tab.
* Click the current status of the token to be updated.
* Select the new status.
* Click Save.

Alternatively:

* Click Tokens tab.
* Click the token to be updated.
* Click Change Status.
* Select the new status.
* Click Save.

= Managing Token Certificates =

To list all certificates:

* Click Certificates tab.

To view a specific certificate:

* Click Certificates tab.
* Click the certificate ID.

To search for certain certificates:

* Click Certificates tab.
* Enter search keyword in the Search box.
* Click Enter.

To list certificates belonging to a token:

* Click Tokens tab.
* Click the token ID.
* Click Show Certificates.

= Managing Token Activities =

To list all activities:

* Click Activities tab.

To view a specific activity:

* Click Activities tab.
* Click the activity of interest.

To search for certain activities:

* Click Activities tab.
* Enter search keyword in the Search box.
* Click Enter.

= Managing Users =

== Listing users ==

* Click Accounts tab.
* Click Users.

== Viewing a user ==

* Click Accounts tab.
* Click Users.
* Click user ID.

== Searching for users ==

* Click Accounts tab.
* Click Users.
* Enter search keyword in Search box.
* Click Enter.

== Adding a user ==

* Click Accounts tab.
* Click Users.
* Click Add.
* Enter User ID and Full Name, and optionally Email.
* To add a profiles, click Add, select a profile from the drop down list, click Add.
* Click Save.

== Configuring profiles for a user ==

* Click Accounts tab.
* Click Users.
* Click the user ID.
* Click Edit.
* To add a profile, click Add, select a profile from the drop down list, click Add.
* To remove profiles, select checkboxes of the profiles to be deleted, click Remove, click OK.
* Click Save.

== Deleting a user ==

* Click Accounts tab.
* Click Users.
* Select the checkboxes of the users to be deleted.
* Click Remove.
* Click OK.

= Managing User Roles =

== Listing User Roles ==

* Click Accounts tab.
* Click Users.

== Adding a User Role ==

* Click Accounts tab.
* Click Users.
* Click the user ID.
* Click Show Roles.
* Click Add.
* Specify the role ID.
* Click Add.

== Deleting User Roles ==

* Click Accounts tab.
* Click Users.
* Click the user ID.
* Click Show Roles.
* Select checkboxes of the roles to be deleted.
* Click Remove.
* Click OK.

= Managing General Configuration =

* Click System tab.
* Click General Configuration.
* Click Edit.
* To edit a proprty, click the property name, enter the new value, click Save.
* To add a property, click Add, enter the name and value, click Add.
* To remove a property, select checkboxes of the property to delete, click Remove, click OK.
* Click Save.

= Managing Profiles =

== Listing profiles ==

To list properties:

* Click System tab.
* Click Profiles.

== Viewing a profile ==

To view a specific profile:

* Click System tab.
* Click Profiles.
* Click the profile ID.

By default the profile properties will be displayed in a table view. To view all properties once, click the Switch View button. To go back to the table view, click the Switch View button again.

== Enabling/disabling a profile ==

* Click System tab.
* Click Profiles.
* Click the profile ID.
* To enable the profile, click the Enable link, then click OK.
* To disable the profile, click the Disable link, then click OK.

== Adding a profile ==

To add a new profile, fist prepare the profile properties, possibly from an existing profile, then follow these steps:

* Click System tab.
* Click Profiles.
* Click Add button.
* Enter an ID for the new profile.
* Add properties:
** To add the properties one-by-one, click the Add button, enter the name and value, then click Add.
** To add the properties in bulk, click the Switch View button, copy and paste the properties into the text area.
* Click Save.

Finally, enable the profile.

== Modify a profile ==

To modify a profile, first disable the profile, then follow these steps:

* Click System tab.
* Click Profiles.
* Click the profile ID.
* Click Edit.
* Edit the properties:
** To edit the properties one-by-one, click the property, enter the new value, then click Add.
** To edit the properties in bulk, click the Switch View button, edit the properties in the text area.
* Click Save.

Finally, re-enable the profile.

== Deleting profiles ==

To delete a profile, first the profile must be disabled, then follow these steps:

* Click System tab.
* Click Profiles.
* Select the checkboxes of the profiles to be deleted.
* Click Remove.
* Click OK.

= Managing Mapping Resolvers =

== Listing mapping resolvers ==

To list mapping resolvers:

* Click System tab.
* Click Profile Mappings.

== Viewing a mapping resolvers ==

To view a specific mapping resolver:

* Click System tab.
* Click Profile Mappings.
* Click the mapping resolver ID.

By default the mapping resolver properties will be displayed in a table view. To view all properties once, click the Switch View button. To go back to the table view, click the Switch View button again.

== Enabling/disabling a mapping resolver ==

* Click System tab.
* Click Profile Mappings.
* Click the mapping resolver ID.
* To enable the mapping resolver, click the Enable link, then click OK.
* To disable the mapping resolver, click the Disable link, then click OK.

== Adding a mapping resolver ==

To add a new mapping resolver, fist prepare the mapping resolver properties, possibly from an existing mapping resolver, then follow these steps:

* Click System tab.
* Click Profile Mappings.
* Click Add button.
* Enter an ID for the new mapping resolver.
* Add properties:
** To add the properties one-by-one, click the Add button, enter the name and value, then click Add.
** To add the properties in bulk, click the Switch View button, copy and paste the properties into the text area.
* Click Save.

Finally, enable the mapping resolver.

== Modify a mapping resolver ==

To modify a mapping resolver, first disable the mapping resolver, then follow these steps:

* Click System tab.
* Click Profile Mappings.
* Click the mapping resolver ID.
* Click Edit.
* Edit the properties:
** To edit the properties one-by-one, click the property, enter the new value, then click Add.
** To edit the properties in bulk, click the Switch View button, edit the properties in the text area.
* Click Save.

Finally, re-enable the mapping resolver.

== Deleting mapping resolvers ==

To delete a mapping resolver, first the mapping resolver must be disabled, then follow these steps:

* Click System tab.
* Click Profile Mappings.
* Select the checkboxes of the mapping resolvers to be deleted.
* Click Remove.
* Click OK.

= Managing Subsystem Connections =

== Listing subsystem connections ==

To list subsystem connections:

* Click System tab.
* Click Subsystem Connections.

== Viewing a subsystem connection ==

To view a specific subsystem connection:

* Click System tab.
* Click Subsystem Connections.
* Click the subsystem connection ID.

By default the subsystem connection properties will be displayed in a table view. To view all properties once, click the Switch View button. To go back to the table view, click the Switch View button again.

== Enabling/disabling a subsystem connection ==

* Click System tab.
* Click Subsystem Connections.
* Click the subsystem connection ID.
* To enable the subsystem connection, click the Enable link, then click OK.
* To disable the subsystem connection, click the Disable link, then click OK.

== Adding a subsystem connection ==

To add a new subsystem connection, fist prepare the subsystem connection properties, possibly from an existing subsystem connection, then follow these steps:

* Click System tab.
* Click Subsystem Connections.
* Click Add button.
* Enter an ID for the new subsystem connection.
* Add properties:
** To add the properties one-by-one, click the Add button, enter the name and value, then click Add.
** To add the properties in bulk, click the Switch View button, copy and paste the properties into the text area.
* Click Save.

Finally, enable the subsystem connection.

== Modify a subsystem connection ==

To modify a subsystem connection, first disable the subsystem connection, then follow these steps:

* Click System tab.
* Click Subsystem Connections.
* Click the subsystem connection ID.
* Click Edit.
* Edit the properties:
** To edit the properties one-by-one, click the property, enter the new value, then click Add.
** To edit the properties in bulk, click the Switch View button, edit the properties in the text area.
* Click Save.

Finally, re-enable the subsystem connection.

== Deleting subsystem connections ==

To delete a subsystem connection, first the subsystem connection must be disabled, then follow these steps:

* Click System tab.
* Click Subsystem Connections.
* Select the checkboxes of the profiles to be deleted.
* Click Remove.
* Click OK.

= Managing Authentication Sources =

== Listing authentication sources ==

To list authentication sources:

* Click System tab.
* Click Authentication Sources.

== Viewing an authentication source ==

To view a specific authentication source:

* Click System tab.
* Click Authentication Sources.
* Click the authentication source ID.

By default the authentication source properties will be displayed in a table view. To view all properties once, click the Switch View button. To go back to the table view, click the Switch View button again.

== Enabling/disabling an authentication source ==

* Click System tab.
* Click Authentication Sources.
* Click the authentication source ID.
* To enable the authentication source, click the Enable link, then click OK.
* To disable the authentication source, click the Disable link, then click OK.

== Adding an authentication source ==

To add a new authentication source, fist prepare the authentication source properties, possibly from an existing authentication source, then follow these steps:

* Click System tab.
* Click Authentication Sources.
* Click Add button.
* Enter an ID for the new authentication source.
* Add properties:
** To add the properties one-by-one, click the Add button, enter the name and value, then click Add.
** To add the properties in bulk, click the Switch View button, copy and paste the properties into the text area.
* Click Save.

Finally, enable the authentication source.

== Modify an authentication source ==

To modify an authentication source, first disable the authentication source, then follow these steps:

* Click System tab.
* Click Authentication Sources.
* Click the authentication source ID.
* Click Edit.
* Edit the properties:
** To edit the properties one-by-one, click the property, enter the new value, then click Add.
** To edit the properties in bulk, click the Switch View button, edit the properties in the text area.
* Click Save.

Finally, re-enable the authentication source.

== Deleting authentication sources ==

To delete an authentication source, first the authentication source must be disabled, then follow these steps:

* Click System tab.
* Click Authentication Sources.
* Select the checkboxes of the authentication sources to be deleted.
* Click Remove.
* Click OK.

= Managing Audit Logging =

== Enabling/disabling audit logging ==

To enable/disable audit logging:

* Click System tab.
* Click Audit Logging.
* To enable audit logging, click Enable.
* To disable audit logging, click Disable.
* Click OK.

== Modifying audit logging configuration ==

To modify audit logging configuration, first disable the audit logging, then follow these steps:

* Click System tab.
* Click Audit Logging.
* Click Edit.
* Make the changes as needed.
* To change event logging, click the event to change, enter the new value, click Save.
* Click Save.

Finally, re-enable the audit logging.
