= Overview =

The TPS database contains several tables/resources. Each resource consists of attributes. The resources are searchable using a keyword. The keyword will be matched against some predetermined list of attributes. 

For most resources that are stored in LDAP, the search will be done using an LDAP filter generated from the search keyword. One exception is the group member resource since the members being searched are actually stored in the same entry, so the search is done using string comparison. The other resources are stored in TPS configuration file, so the search will also be done using string comparison.

Not all resource attributes are searchable because not all attributes are indexed or contain useful information to search.

Currently it's not possible to search against a specific attribute or do complex filter.

The search keyword must be at least 3 characters long. In the future this restriction will be configurable.

Currently the searchable attributes are fixed, but in the future this will be configurable.

= Tokens =

See link:TPS-Token-Database[TPS Token Database].

= Certificates =

See link:TPS-Certificate-Database[TPS Certificate Database].

= Activities =

The resource is stored in LDAP. Search will be done with this LDAP filter: `(|(tokenID=*<keyword>*)(tokenUserID=*<keyword>*))`.

|===
| LDAP Attribute | REST Attribute | Indexed | Searchable | Example

| cn
| Activity ID
| Yes
| No. The attribute doesn't contain useful information to search.
| 20140403112248865475.abf44b40

| tokenID
| Token ID
| Yes
| Yes
| 534E0650000100000108

| tokenUserID
| User ID
| Yes
| Yes
| testuser

| tokenIP
| IP
|
|
| 127.0.0.1

| tokenOp
| Operation
|
|
| enrollment

| tokenResult
| Result
|
|
| success

| tokenMsg
| Message
|
|
| applet_version=1.4.52CF1C58 tokenType=userKey userid=testuser

| tokenType
| Type
|
|
| userKey

| extensions
| Extensions
|
|
|

| dateOfCreate
| Date
| Yes
| No. The attribute doesn't contain useful information to search.
| 20140403112248Z

| dateOfModify
| 
| Yes
| No. The attribute is not used.
| 20140403112248Z
|===

= Users =

The resource is stored in LDAP. Search will be done with this LDAP filter: `(|(uid=*<keyword>*)(cn=*<keyword>*)(mail=*<keyword>*))`.

|===
| LDAP Attribute | REST Attribute | Indexed | Searchable | Example

| uid
| User ID
| Yes
| Yes
| testuser

| cn
| Full Name
| Yes
| Yes
| Test User

| mail
| Email
| Yes
| Yes
|

| userPassword
| Password
|
|
| e1NTSEF9UEY...

| telephoneNumber
| Phone
|
|
|

| userType
| Type
|
|
|

| userState
| State
|
|
|

| profileID
| TPS Profiles
|
|
| All Profiles
|===

= Groups =

The resource is stored in LDAP. Search will be done with this LDAP filter: `(cn=*<keyword>*)`.

|===
| LDAP Attribute | REST Attribute | Indexed | Searchable | Example

| cn
| Group ID
| Yes
| Yes
| TUS Administrators

| description
| Description
|
| No. The attribute is not indexed.
| Administrators for TUS
|===

= Group Members =

The resource is stored in LDAP. But since the group ID is known, the member ID search will be done with string comparison: `memberID.contains(keyword)`.

|===
| LDAP Attribute | REST Attribute | Indexed | Searchable | Example

| cn
| Group ID
| Yes
| No. The group ID must be specified in order to search a member ID.
| TUS Administrators

| uniqueMember
| Member ID
| Yes
| Yes
| uid=admin,ou=People,dc=example,dc=com
|===

= Authentication Sources =

This resource is stored in CS.cfg. Search will be done using a string comparison: `authenticatorID.contains(keyword)`.

* Authenticator ID (searchable)
* Status
* Properties

= Subsystem Connections =

This resource is stored in CS.cfg. Search will be done using a string comparison: `connectionID.contains(keyword)`.

* Connector ID (searchable)
* Status
* Properties

See also link:https://www.dogtagpki.org/wiki/Connector_Database[Connector Database].

= Profiles =

This resource is stored in CS.cfg. Search will be done using a string comparison: `profileID.contains(keyword)`.

* Profile ID (searchable)
* Status
* Properties

= Profile Mappings =

This resource is stored in CS.cfg. Search will be done using a string comparison: `profileMappingID.contains(keyword)`.

* Profile Mapping ID (searchable)
* Status
* Properties

= Self Tests =

This resource is stored in CS.cfg. Search will be done using a string comparison: `selfTestID.contains(keyword)`.

* Self Test ID (searchable)
* Enabled At Startup
* Critical At Startup
* Enabled On Demand
* Critical On Demand
